// Generates the published procurement risk-flag spec from src/lib/riskFlagCatalog.ts.
//
//   npm run gen:risk            # rewrite the artifacts
//   npm run gen:risk -- --check # exit 1 if either is stale (the gate)
//
// Emits two files:
//   docs/methodology/procurement-risk-flags.md   the handbook a person reads
//   public/risk-flags.json                       the catalogue a machine reads
//
// WHY GENERATE THEM. The flags are a published artifact: a journalist is invited
// to cite "flag set vX.Y.Z", and a flag that fires on a named company is a public
// claim. A hand-written spec beside a live implementation is the same
// "computed in two places" failure the catalogue itself exists to end, with the
// worse failure mode — the code stays right and the DOCUMENT becomes the lie,
// which is the copy people quote.
//
// IT IS DELIBERATELY NOT NAMED `db:gen-*`. That prefix means "writes a committed
// artifact FROM POSTGRES and therefore belongs in db:refresh", and
// refresh_coverage.test.ts enumerates every such script. This one derives
// documents from TypeScript, runs when a human edits the catalogue, and would be
// meaningless inside a data reload. `--check` is what the test runs.
//
// The same reasoning as scripts/db/gen_sql/shlyo_query_fold.ts, one artifact kind
// over.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  ALIGNMENT_SOURCES,
  AWARDER_EXPOSURE_LIST,
  CATALOG_VERSION,
  CONCENTRATION_MIN_AWARDER_TOTAL_EUR,
  CONTRACT_DISPLAY_ORDER,
  CONTRACT_FLAG_LIST,
  CONTRACT_GRADE_BANDS,
  FIRED_COUNT_CORPUS,
  FIRED_COUNT_DISTRIBUTION,
  FLAG_FRAMING,
  LEGALLY_SINGLE_SOURCE_CPV_PREFIX,
  NEUTRAL_DISCLOSURES,
  RISK_MASK_BITS,
  SUPPLIER_EXPOSURE_LIST,
  TENDER_FLAG_LIST,
  contractFlag,
  contractThreshold,
  tenderThreshold,
  type ContractFlagDef,
  type TenderFlagDef,
} from "../../src/lib/riskFlagCatalog";

const ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
);
const HANDBOOK = path.join(ROOT, "docs/methodology/procurement-risk-flags.md");
const JSON_OUT = path.join(ROOT, "public/risk-flags.json");

const GENERATED_BANNER =
  "<!-- GENERATED by `npm run gen:risk` from src/lib/riskFlagCatalog.ts — do not edit by hand. -->";

/** Escape a markdown table cell: pipes would split it, newlines would end it. */
const cell = (s: string | undefined): string =>
  (s ?? "—").replace(/\|/g, "\\|").replace(/\n+/g, " ");

const thresholdText = (f: ContractFlagDef | TenderFlagDef): string => {
  const t = f.threshold;
  if (!t) return "—";
  switch (t.kind) {
    case "gteRatio":
      return `≥ ${(t.value * 100).toFixed(0)}%`;
    case "ltDays":
      return `< ${t.value} days`;
    case "lteDays":
      return `≤ ${t.value} days`;
    case "ltMonths":
      return `< ${t.value} months`;
    case "gteMultiple":
      return `> ${((t.value - 1) * 100).toFixed(0)}% over`;
    case "gteEur":
      return `≥ €${t.value.toLocaleString("en-US")}`;
    case "cpvPrefix":
      return `CPV ${t.value}`;
  }
};

// ---------------------------------------------------------------------------
// The handbook
// ---------------------------------------------------------------------------

const perFlagSection = (): string => {
  const rows = CONTRACT_DISPLAY_ORDER.map((id) => {
    const f = contractFlag(id);
    return `| \`${f.id}\` | ${f.bit} | ${cell(thresholdText(f))} | ${cell(f.citation)} | ${cell(f.availability)} | ${cell(f.baseRate)} |`;
  }).join("\n");

  const basis = CONTRACT_DISPLAY_ORDER.map((id) => {
    const f = contractFlag(id);
    return f.threshold
      ? `**\`${f.id}\`** — ${thresholdText(f)}. ${f.threshold.basis}`
      : null;
  })
    .filter(Boolean)
    .join("\n\n");

  const caveats = [...CONTRACT_FLAG_LIST, ...TENDER_FLAG_LIST]
    .filter((f) => f.caveat)
    .map((f) => `- **\`${f.id}\`** — ${f.caveat}`)
    .join("\n");

  const tenderRows = TENDER_FLAG_LIST.map(
    (f) =>
      `| \`${f.id}\` | ${cell(thresholdText(f))} | ${cell(f.citation)} | ${cell(f.availability)} | ${cell(f.baseRate)} |`,
  ).join("\n");

  const tenderBasis = TENDER_FLAG_LIST.map((f) =>
    f.threshold
      ? `**\`${f.id}\`** — ${thresholdText(f)}. ${f.threshold.basis}`
      : null,
  )
    .filter(Boolean)
    .join("\n\n");

  return `## Per-flag reference

### Contract grain — ${CONTRACT_FLAG_LIST.length} checks

Ordered as the site's own check ledger orders them (heaviest first), **not** in bit order.

| flag | bit | threshold | legal basis / citation | when it is evaluable | measured base rate |
|---|---:|---|---|---|---|
${rows}

${
  caveats
    ? `#### ⚠️ Caveats on individual checks

Read these before reproducing any of them. A check listed here is implemented but is inert, uncalibrated or unsettled, and saying so is part of the specification rather than a footnote to it.

${caveats}
`
    : ""
}

Weights are deliberately absent from this table. The published contract index is
\`cri = 100 × fired / available\` — **unweighted**. An additive weight per flag does exist in the
implementation, but it drives an internal sort key that nothing renders, and publishing it here
would invite a reader to reproduce a number we do not compute. It is in \`risk-flags.json\` as
\`legacyWeight\`, labelled as such.

#### Threshold provenance

${basis}

Two carve-outs sit inside \`weakCompetition\` rather than beside it, and both matter for anyone
reproducing the flag:

- **The statutory sole-source exemption.** CPV \`${LEGALLY_SINGLE_SOURCE_CPV_PREFIX}\` (textbooks)
  is awarded by law to the copyright holder under ЗОП чл.79 ал.1 т.3. Every such contract is
  single-bid by statute, not by choice, and the flag is suppressed regardless of the division's
  aggregate share.
- **Two different CPV grains in one flag.** The structural suppression reads the **2-digit
  division**'s single-bid share; the graded "materially fewer bidders than this market" arm reads
  the **5-digit prefix** median (competitive markets only, median ≥ 3). Restating this as one
  grain is the single most common error in describing the flag.

### Tender grain — ${TENDER_FLAG_LIST.length} checks (ex-ante, per procedure)

These score the PROCEDURE, so a signal can fire while bids are still open, and they make a
statement about the buyer's conduct rather than about any winner. They have no bit mask, no
weights and no server-side cache — they are computed live from the procedure row.

| flag | threshold | citation | when it is evaluable | measured base rate |
|---|---|---|---|---|
${tenderRows}

#### Threshold provenance

${tenderBasis}

### Neutral disclosure — never scored

${NEUTRAL_DISCLOSURES.map(
  (d) => `**\`${d.id}\`** — ${d.note} ${d.availability}`,
).join("\n\n")}

Foreign funding is lawful disclosure. Rendering it as a red flag would be a "foreign agent"
framing this project does not make, so it touches neither the CRI nor the fired count nor any
grade. It is listed here so its absence from the scored set is a stated decision rather than
something a reader has to infer.`;
};

const exposureSection =
  (): string => `## Exposure grades — two weight sets, not one

An exposure grade is an entity-level figure: a buyer's or a supplier's whole record, scored as an
**availability-weighted mean** of share components and banded A–F. A component whose input is
unknown is DROPPED from the denominator, never scored zero.

The two roles use **different components and different weights**, and conflating them is the
error most likely to be made by someone copying this section.

### Buyer (awarder)

| component | weight |
|---|---:|
${AWARDER_EXPOSURE_LIST.map((c) => `| \`${c.key}\` | ${c.weight} |`).join("\n")}

These weights sum to ${AWARDER_EXPOSURE_LIST.reduce((t, c) => t + c.weight, 0).toFixed(2)} when
every component is available — the denominator of the weighted mean, not a normalisation to 1.

They were rebalanced on 2026-07-18: \`direct\` from 0.20 to its present value and \`singleBid\`
from 0.25 to its present value, with the total deliberately unchanged so the score scale did not
move. The evidence is the EC Single Market Scoreboard —
Bulgaria's genuine outlier is "no calls for bids" (~20% against an EU median of 5%), while
single-bidding (36%) sits below its CEE peers and therefore does not discriminate. Measured
effect: of 1,149 ranked buyers 234 changed grade (226 better, 8 worse); the two worst were
unchanged.

⚠️ **The Scoreboard does not measure corruption.** It measures procedural characteristics. That
caveat travels with these weights wherever they are reused.

### Supplier

| component | weight | always available? |
|---|---:|---|
${SUPPLIER_EXPOSURE_LIST.map(
  (c) => `| \`${c.key}\` | ${c.weight} | ${c.alwaysAvailable ? "yes" : "no"} |`,
).join("\n")}

Three differences from the buyer arm, all deliberate to state:

1. **There is no upheld-appeal component.** A КЗК decision is an integrity signal about the
   *buyer's* procedure; it is not folded into a supplier's grade.
2. **These are the pre-rebalance \`direct\` / \`singleBid\` weights.** The 2026-07-18 change moved
   the buyer arm only.
3. **\`connectedSelf\` is unconditionally available**, so its weight sits in the denominator on
   every row, unlike every other component.

⚠️ **Open question, stated rather than resolved.** Whether the supplier arm's un-rebalanced
weights are a deliberate exception — a supplier does not choose the procedure type, which is what
the Scoreboard argument is about — or drift that survived the buyer-side change, has not been
decided. This spec therefore publishes both sets as facts and does not assert a rationale for the
supplier one. A reader reproducing the supplier grade should know it is under review.`;

const gradesSection =
  (): string => `## The three A–F grades, and what each is banded on

Three different letters are published, on three grains and three bases. A reader who assumes they
are one scale will mis-read all three.

| grade | grain | banded on |
|---|---|---|
| buyer exposure | a buyer, over all its contracts | availability-weighted mean of 5 share components, 0–100 |
| supplier exposure | a contractor | the same shape, 4 components, un-rebalanced weights |
| contract | one contract | the **fired COUNT**, not the CRI |

### Why the contract grade is not banded on the CRI

The CRI is not a continuous score — it is a small lattice, because \`fired\` never exceeds 6 and
\`available\` only varies across a narrow range. Fed to the entity-grade bands it put 99% of the
corpus in A/B and made **F mathematically unreachable**: the corpus maximum CRI is 60, so the
eleven most-flagged contracts in the country would have read "E". A grade nobody can score is not
a grade.

Banding on the fired count gives every letter a real population and a one-sentence meaning:

| grade | checks fired |
|---|---|
${CONTRACT_GRADE_BANDS.map((b) => `| ${b.grade} | ${b.fired} |`).join("\n")}

### What the corpus actually looks like

Measured ${FIRED_COUNT_CORPUS.measuredOn} over ${FIRED_COUNT_CORPUS.contracts.toLocaleString("en-US")} contracts:

| checks fired | contracts | share |
|---:|---:|---:|
${FIRED_COUNT_DISTRIBUTION.map(
  (d) => `| ${d.fired} | ${d.contracts.toLocaleString("en-US")} | ${d.share} |`,
).join("\n")}

A reader who does not know that **${FIRED_COUNT_DISTRIBUTION[0].share} of contracts fire nothing
at all** cannot calibrate a contract that fires two.

### Why a contract letter is weaker evidence than an entity letter

It is published anyway, because the contracts browser needs a sortable, filterable severity
handle — but the caveat is not decoration. A contract is n=1. The World Bank's own study of this
corpus (PRWP 10444) puts it directly: corruption-risk indices at the individual contract level
"may be quite noisy", while aggregating to the organisation "identif[ies] more robust patterns".

### One known wrinkle, not hidden

Because the CRI divides by a varying denominator it is *almost* monotone in the fired count, but
not quite: a 4-of-11 contract scores 36 while a 3-of-8 scores 38. The grade itself is unaffected
(it reads the fired count directly), and the leaderboard orders by fired count first for this
reason.`;

const alignmentSection = (): string => {
  const all = [...CONTRACT_FLAG_LIST, ...TENDER_FLAG_LIST];

  // ONE TABLE PER SCHEME rather than one table carrying both.
  //
  // A combined table needs a single "how we differ" cell, and the two notes then
  // run together into a sentence that reads as one thought about the wrong
  // scheme ("…a separate person-layer concern. No debarment indicator in the
  // 11-indicator set."). Splitting keeps each difference attached to the scheme
  // it is actually about.
  const table = (
    scheme: "ocp" | "imonitor",
    heading: string,
    idHeading: string,
  ): string => {
    const rows = all
      .map((f) => {
        const c = f[scheme];
        const ref = c.id
          ? "`" + c.id + "`" + (c.name ? " — " + c.name : "")
          : "**unmapped**";
        return `| \`${f.id}\` | ${cell(ref)} | ${cell(c.note)} |`;
      })
      .join("\n");
    const unmapped = all.filter((f) => !f[scheme].id).length;
    return [
      `### ${heading}`,
      "",
      `${unmapped} of our ${all.length} checks have no equivalent there.`,
      "",
      `| our flag | ${idHeading} | how we differ |`,
      "|---|---|---|",
      rows,
    ].join("\n");
  };

  return [
    "## Alignment with OCP and iMonitor",
    "",
    "The point of these tables is **comparability, not compliance**. They let somebody already",
    "working in either scheme see this Bulgarian calibration through their lens, and they mark the",
    "places we deliberately deviate.",
    "",
    "**`unmapped` means somebody read the source and found no equivalent** — not that nobody looked.",
    "",
    `Verified ${ALIGNMENT_SOURCES.ocp.verifiedOn} against the documents themselves:`,
    "",
    `- **${ALIGNMENT_SOURCES.ocp.title}** — ${ALIGNMENT_SOURCES.ocp.flagCount} flags.`,
    `  <${ALIGNMENT_SOURCES.ocp.url}>`,
    `  *Method:* ${ALIGNMENT_SOURCES.ocp.method}`,
    `- **${ALIGNMENT_SOURCES.imonitor.title}** — ${ALIGNMENT_SOURCES.imonitor.indicatorCount} indicators.`,
    `  <${ALIGNMENT_SOURCES.imonitor.url}>`,
    `  *Method:* ${ALIGNMENT_SOURCES.imonitor.method}`,
    "",
    table("ocp", "OCP, *Red Flags for Integrity* (2024)", "OCP flag"),
    "",
    table("imonitor", "iMonitor 2.0 / OpenTender", "iMonitor indicator"),
    "",
    "### What these tables are for",
    "",
    "1. **The political-connection flags have no counterpart in either scheme.** `mpConnected`,",
    "   `pepConnected` and `nkidMismatch` are unmapped on both sides. That is the genuinely local",
    "   part of this catalogue — and also the part making the strongest claim about named people,",
    "   which is why it is gated on a resolved identity layer rather than on name matching.",
    "2. **Where we are stricter, it is usually a legal anchor rather than a better statistic.**",
    "   `annexGrowth` is bound to ЗОП чл.116 ал.2's cumulative cap and `splitPurchase` to чл.20",
    "   ал.4's ceilings by date and category. Neither external scheme fixes a value, because",
    "   neither is written for one jurisdiction.",
    "3. **Where we are looser, we say so.** `weakCompetition` suppresses in structurally single-bid",
    "   CPV divisions and on the statutory sole-source CPV; OCP's R018 and iMonitor's single-bidder",
    "   indicator do not. That is a deliberate false-positive reduction, and it means **our",
    "   single-bid rate is not comparable to theirs** until the suppression is undone.",
    "",
    "⚠️ **Both external schemes band several indicators (iMonitor scores 0/50/100 throughout) where",
    "we fire a boolean.** A cross-country comparison that reads our booleans as their scores will",
    "overstate the difference between Bulgaria and its peers, in both directions.",
  ].join("\n");
};

const buildHandbook = (): string => `${GENERATED_BANNER}

# Bulgarian public-procurement red flags — the methodology

**Flag set v${CATALOG_VERSION}.**

This is the specification behind every risk flag, contract index and exposure grade published at
electionsbg.com. It exists so the flags can be checked, argued with and reused: the definitions
used to live only in code, which made a claim about a named company unfalsifiable from outside.

Licensed MIT (see [LICENSE](../../LICENSE)). The data the flags are computed over keeps its own
terms.

⚠️ **Cite the version the MASKS were computed under, not this one.** The number above is what the
code declares. The flags a reader sees are served from a cache, rebuilt on its own schedule, and
the two diverge across the window between a deploy and a rebuild. \`/api/db/risk-catalog-version\`
reports the version stamped at the last rebuild; where that reads "not stamped", the served flags
cannot be attributed to a catalogue version at all. (A \`/procurement/methodology\` page carrying
the same figure is planned and not yet live — until it ships, that route and this document are
the published spec.)

---

## How to read a flag

${FLAG_FRAMING.ocp}

That ordering is from the Open Contracting Partnership's *Red Flags for Integrity* (2024), and it
names the two innocent explanations before the guilty one. It is a presentation order, **not** a
claim about relative frequency — the published research is explicit that validated red flags
correlate weakly with corruption at the level of a single contract.

${FLAG_FRAMING.publisher}

${FLAG_FRAMING.denominator}

That last rule is the one most often lost in reuse. A contract with no recorded bid count is not
scored zero on competition — the check is removed from its denominator entirely, so a data-poor
contract is neither penalised nor flattered. It is also why two contracts with the same CRI can
have been evaluated on different numbers of checks, and why the site renders the ratio
("2 of 9 checks") rather than a bare number.

---

${perFlagSection()}

---

${exposureSection()}

---

${gradesSection()}

---

${alignmentSection()}

---

## Legal thresholds

- **ЗОП чл.116 ал.2** — the 50% cap is **cumulative** ("общата стойност на измененията"), which is
  stricter than the EU per-modification rule in Directive 2014/24 Art. 72. The ал.3 inflation
  indexation carries its **own** separate 50% that does not count against ал.2, and чл.116 ал.6
  exempts sectoral awarders. \`annexGrowth\` detects the cumulative change; it cannot say which
  ground was used, and this spec does not claim otherwise.
- **The concentration floor is ours, not a legal one.** \`awarderConcentration\` only considers
  buyers whose lifetime spend clears **€${CONCENTRATION_MIN_AWARDER_TOTAL_EUR.toLocaleString("en-US")}**;
  below that, a supplier taking 100% of a buyer's spend is arithmetic rather than concentration.
  The 30% share bar is likewise a house threshold following the conventional CEE oversight bar,
  not a statutory one.
- **ЗОП чл.20 ал.4** — the direct-award ceilings, which are date- and category-dependent.
  \`splitPurchase\` compares a group of all-direct awards against the ceiling in force. чл.21's
  anti-splitting rule permits genuinely separate recurring needs, and the data cannot distinguish
  those from splitting — which is why the flag is framed as a question and carries an irreducible
  false-positive floor.
- **ЗОП чл.79 ал.1 т.3** — the statutory sole-source ground behind the CPV
  \`${LEGALLY_SINGLE_SOURCE_CPV_PREFIX}\` carve-out above.
- **EU Directive 2014/24 Art. 27** — the source the CONTRACT-grain \`shortTenderPeriod\`'s
  ${contractThreshold("shortTenderPeriod")}-day cut was lifted from. ⚠️ Read the caveat above
  before reusing it: Art. 27's own minima are longer and tiered, so this is our simplification of
  the Directive rather than a rule it states, and it is a legal minimum rather than a calibrated
  risk threshold. The TENDER-grain \`rushedDeadline\` deliberately differs — tier-conditional at
  ${tenderThreshold("rushedDeadline")} days, because on low-value tiers a short window is
  statutory rather than anomalous. Two thresholds that look like one is a real trap; they are
  different rules on different objects.
- **The 10%/15% de minimis is EU, not ЗОП.** It is not transposed, and attributing it to ЗОП is a
  mistake this spec makes explicit because it is a common one.

---

## Reconciliation — how the corpus is kept from lying

Thresholds are the easy part to copy. What makes the flags trustworthy is the data work
underneath, and almost nobody documents it:

- **Four feeds, never summed.** The contracts corpus is built from four sources distinguished by
  release-id prefix (АОП annual CSV, ЦАИС ЕОП flat договори, the АОП OCDS export, and РОП). Each
  splits a contract's value across its own view of the supplier set, so when one contract arrives
  from two feeds the rows **cannot be added together**. A dedicated cross-source pass removes the
  duplicates before anything is scored, and permanently refuses — printing them in full — the two
  shapes it cannot safely resolve.
- **The join key does not exist at parse time.** The identity the reconciliation runs on is the
  УНП, which the OCDS export does not carry; it is written onto the records afterwards. Run out of
  order the pass is a silent no-op, so it preflights its own precondition.
- **Amendments are events, not duplicates.** Rows tagged as contract amendments are distinct
  events, carry zero weight in every money rollup, and must never be folded into the base
  contract. A tag-blind deduplication pairs a contract with its own amendment and deletes the
  contract.
- **Annex identity is resolved with three guards** — value continuity, a magnitude cap, and
  supplier-set membership — because an annex that cannot be matched to its parent is worse than
  an annex that is skipped.
- **Missing data is never scored.** Stated again here because it is a data-quality rule as much as
  a scoring one, and because the alternative — treating absence as innocence — is what makes a
  poorly-documented corpus look cleanest.

---

## Known limits

Published because a methodology that lists only its strengths is a press release.

- **Validated red flags are weakly related to corruption at the contract level.** Decarolis &
  Giorgiantonio (EPJ Data Science 11:16, 2022) validated red flags against firm-level
  police-investigation data on a near-population of Italian roadwork contracts and found the most
  scrutinised flags either uncorrelated with corruption or negatively associated with it, with a
  best realistic model F ≈ 0.6. Urgency procedures and publicity ran backwards. This is the
  strongest published argument against reading any single flag as evidence.
- **A published flag is a specification for evading it.** This is the Goodhart problem, and it is
  in direct tension with the transparency argument for publishing at all. We publish anyway, and
  say so deliberately: the mitigations are that flags fire *for review*, that exposure is measured
  at entity grain where a pattern is harder to stage than a single contract, and that the
  context panels stay judgement-free.
- **Construct validity.** These flags measure procedural characteristics that are *associated*
  with weak competition and discretion. They do not measure corruption, and no threshold in this
  document should be read as a corruption probability.
- **Coverage is uneven across checks.** Some checks are evaluable on nearly every contract and
  others on a small minority; the per-flag table above states each one's availability rule, and
  the CRI's denominator reflects it per contract.

---

## Reusing this

The catalogue is published as [\`risk-flags.json\`](../../public/risk-flags.json) — the same source
this document is generated from, so the two cannot disagree.

Cite it as:

> Наясно / electionsbg.com, *Bulgarian procurement red-flag catalogue*, flag set v${CATALOG_VERSION}.
> https://github.com/atanasster/electionsbg

The version is semantic: a flag added, reweighted or re-thresholded is a minor bump; a flag
removed, or a bit position renumbered, is a major one. Bit positions are **append-only** —
renumbering silently re-maps every historic mask, so it is never a compatible change.
`;

// ---------------------------------------------------------------------------
// The JSON catalogue
// ---------------------------------------------------------------------------

const buildJson = (): string =>
  `${JSON.stringify(
    {
      $comment:
        "GENERATED by `npm run gen:risk` from src/lib/riskFlagCatalog.ts. " +
        "The handbook at docs/methodology/procurement-risk-flags.md is generated from the same source. " +
        "MIT licensed; see LICENSE. Flags are pattern signals for review, NOT findings of wrongdoing.",
      version: CATALOG_VERSION,
      framing: FLAG_FRAMING,
      contractIndex: {
        formula: "cri = 100 * fired / available",
        weighted: false,
        note: "Unweighted by design. `legacyWeight` below feeds an internal sort key that nothing renders.",
      },
      bitOrder: RISK_MASK_BITS,
      bitOrderNote:
        "APPEND-ONLY. Renumbering re-maps every historic mask; it is a major version change and requires a full cache rebuild.",
      contractFlags: CONTRACT_FLAG_LIST.map((f) => ({
        id: f.id,
        bit: f.bit,
        legacyWeight: f.legacyWeight,
        threshold: f.threshold ?? null,
        citation: f.citation ?? null,
        availability: f.availability,
        baseRate: f.baseRate ?? null,
        caveat: f.caveat ?? null,
        ocp: f.ocp,
        imonitor: f.imonitor,
      })),
      contractGradeBands: CONTRACT_GRADE_BANDS,
      firedCountDistribution: {
        corpus: FIRED_COUNT_CORPUS,
        buckets: FIRED_COUNT_DISTRIBUTION,
      },
      tenderFlags: TENDER_FLAG_LIST.map((f) => ({
        id: f.id,
        threshold: f.threshold ?? null,
        citation: f.citation ?? null,
        availability: f.availability,
        baseRate: f.baseRate ?? null,
        caveat: f.caveat ?? null,
        ocp: f.ocp,
        imonitor: f.imonitor,
      })),
      alignmentSources: ALIGNMENT_SOURCES,
      exposureGrades: {
        note: "TWO weight sets. Availability-weighted mean; an unavailable component is dropped from the denominator, never scored 0.",
        awarder: AWARDER_EXPOSURE_LIST,
        supplier: SUPPLIER_EXPOSURE_LIST,
        supplierOpenQuestion:
          "The supplier arm carries the pre-2026-07-18 direct/singleBid weights and has no upheld-appeal component. Whether that is a deliberate exception or unreviewed drift is undecided; both sets are published as facts.",
      },
      neutralDisclosures: NEUTRAL_DISCLOSURES,
      constants: {
        concentrationMinAwarderTotalEur: CONCENTRATION_MIN_AWARDER_TOTAL_EUR,
        legallySingleSourceCpvPrefix: LEGALLY_SINGLE_SOURCE_CPV_PREFIX,
      },
    },
    null,
    2,
  )}\n`;

// ---------------------------------------------------------------------------

const OUTPUTS: { file: string; build: () => string }[] = [
  { file: HANDBOOK, build: buildHandbook },
  { file: JSON_OUT, build: buildJson },
];

const main = (): void => {
  const check = process.argv.includes("--check");
  const stale: string[] = [];

  for (const { file, build } of OUTPUTS) {
    const next = build();
    const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
    if (current === next) continue;
    if (check) {
      stale.push(path.relative(ROOT, file));
      continue;
    }
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, next);
    console.log(`  wrote ${path.relative(ROOT, file)}`);
  }

  if (check && stale.length) {
    console.error(
      `✗ stale generated artifact(s): ${stale.join(", ")}\n` +
        "  Run `npm run gen:risk` and commit the result.",
    );
    process.exit(1);
  }
  console.log(check ? "✓ generated artifacts are current" : "done");
};

main();
