#!/usr/bin/env python3
"""Generate the prompt assets a local model needs: the compact taxonomy and
the GBNF grammar that constrains its output.

⚠️⚠️ THE GRAMMAR IS THE POINT, more than the choice of model.
`analyze_articles.py` rejects a WHOLE record on any schema or taxonomy
violation, and a 12B asked to free-form nested JSON with enum labels trips
that gate often enough to matter. GBNF makes an invalid label
UNREPRESENTABLE rather than merely rejected afterwards — a wrong token cannot
be sampled.

⚠️ Both outputs are DERIVED. `analyze_schema.gbnf` comes from the same
constants `analyze_articles.py` validates against, and `taxonomy_compact.json`
from `news/topics.json`. Hand-editing either is how a grammar comes to permit
a label the validator rejects — the model then produces records that are
grammatically perfect and refused 100% of the time, which reads as a model
problem.

Run:  python3 news/scripts/build_prompts.py [--check]
"""

import argparse
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import analyze_articles as aa  # noqa: E402

ROOT = Path(os.environ.get("DATA_BG_ROOT") or
            Path(__file__).resolve().parents[2])
PROMPTS = ROOT / "news" / "prompts"
TOPICS = ROOT / "news" / "topics.json"
SYSTEM_SOURCE = PROMPTS / "analyze_system.source.md"

# ⚠️ 6,000 characters. Measured over the 4,280-article corpus: p50 is 1,754,
# p90 is 6,213 and p99 is 14,882 — so this touches ~10.5% of articles and only
# their TAILS. The one thing it must never do is truncate the lede, which is
# where a Bulgarian news article states its framing; taking the head is
# therefore correct and taking a middle window would not be.
MAX_BODY_CHARS = 6000


def compact_taxonomy(doc: dict) -> list:
    """Ids and Bulgarian labels only.

    ⚠️ The full topics.json is 23,032 characters; this is 3,190 (14%). At a
    12B's context that difference is most of the budget the article itself
    needs. Keyword hints are dropped deliberately — they exist to help a
    human skim, and a model given keywords starts keyword-matching, which is
    exactly what the rubric forbids.
    """
    return [{
        "id": c["id"],
        "label": c["label"]["bg"],
        "subcategories": [s["id"] for s in c.get("subcategories") or []],
    } for c in doc.get("categories") or []]


def gbnf_alt(values) -> str:
    """A GBNF alternation of quoted literals."""
    return " | ".join('"\\"' + v + '\\""' for v in sorted(values))


def build_grammar(doc: dict) -> str:
    cats = [c["id"] for c in doc.get("categories") or []]
    subs = sorted({s["id"] for c in doc.get("categories") or []
                   for s in c.get("subcategories") or []})
    return f'''# GENERATED by news/scripts/build_prompts.py — do not edit.
#
# ⚠️ Every enum here mirrors a constant analyze_articles.py validates against.
# A grammar that permits a label the validator rejects produces records that
# are grammatically perfect and refused 100% of the time — which reads as a
# model problem and is not one.
#
# ⚠️ The category/subcategory PAIRING is NOT expressible in GBNF: this
# grammar permits any subcategory under any category, and only the validator
# knows which pairs exist. That is a real limit, stated rather than hidden.

root        ::= "{{" ws quality "," ws summaries "," ws leaning "," ws russia "," ws ai "," ws entities "," ws tones "," ws topics "," ws relevant ws "}}"

quality     ::= "\\"quality\\"" ws ":" ws "{{" ws "\\"verdict\\"" ws ":" ws qverdict "," ws "\\"notes\\"" ws ":" ws str0 ws "}}"
qverdict    ::= {gbnf_alt(aa.QUALITY_VERDICTS)}

summaries   ::= "\\"summary_bg\\"" ws ":" ws string "," ws "\\"summary_en\\"" ws ":" ws string

leaning     ::= "\\"leaning\\"" ws ":" ws "{{" ws "\\"label\\"" ws ":" ws lean_lab "," ws conf "," ws evid ws "}}"
lean_lab    ::= {gbnf_alt(aa.LEANING_LABELS)}

russia      ::= "\\"russia_stance\\"" ws ":" ws "{{" ws "\\"label\\"" ws ":" ws ru_lab "," ws conf "," ws evid ws "}}"
ru_lab      ::= {gbnf_alt(aa.RUSSIA_LABELS)}

ai          ::= "\\"ai_generated\\"" ws ":" ws "{{" ws "\\"verdict\\"" ws ":" ws ai_lab "," ws conf "," ws "\\"signals\\"" ws ":" ws strings ws "}}"
ai_lab      ::= {gbnf_alt(aa.AI_VERDICTS)}

conf        ::= "\\"confidence\\"" ws ":" ws prob
evid        ::= "\\"evidence\\"" ws ":" ws string

entities    ::= "\\"entities\\"" ws ":" ws "{{" ws "\\"people\\"" ws ":" ws strings "," ws "\\"parties\\"" ws ":" ws strings "," ws "\\"institutions\\"" ws ":" ws strings "," ws "\\"companies\\"" ws ":" ws strings "," ws "\\"places\\"" ws ":" ws strings ws "}}"

tones       ::= "\\"party_tones\\"" ws ":" ws "[" ws (tone (ws "," ws tone)*)? ws "]"
tone        ::= "{{" ws "\\"party\\"" ws ":" ws string "," ws "\\"tone\\"" ws ":" ws tone_lab "," ws conf "," ws evid ws "}}"
tone_lab    ::= {gbnf_alt(aa.TONE_LABELS)}

topics      ::= "\\"topics\\"" ws ":" ws "[" ws (topic (ws "," ws topic)*)? ws "]"
topic       ::= "{{" ws "\\"category\\"" ws ":" ws cat "," ws "\\"subcategory\\"" ws ":" ws (sub | "null") "," ws "\\"primary\\"" ws ":" ws bool ws "}}"
cat         ::= {gbnf_alt(cats)}
sub         ::= {gbnf_alt(subs)}

relevant    ::= "\\"site_relevant\\"" ws ":" ws bool

# ⚠️ A probability, not a number. Written as a free float, a model emits
# `0.85` and also `85`, `1.5` and `-0`, every one of which the validator
# rejects for being outside [0,1].
prob        ::= "0" | "1" | "0." [0-9]+ | "1.0"
bool        ::= "true" | "false"
# ⚠️ `str0` inside: an entity list may be empty, but `analyze_articles.py`
# requires every ELEMENT to be a non-empty string — so the list uses
# `string`, and only the fields that permit "" use `str0`.
strings     ::= "[" ws (string (ws "," ws string)*)? ws "]"
# ⚠️ NON-EMPTY. The obvious `(...)*` derives `""`, and the validator demands
# a non-empty string for summary_bg, summary_en, both evidence fields and
# every party name — so the grammar could produce records it would then
# reject, most likely on exactly the paywall_shell / too_short articles the
# rubric tells the model not to analyse.
string      ::= "\\"" char+ "\\""
# A string that MAY be empty, for the fields where the validator allows it.
str0        ::= "\\"" char* "\\""
char        ::= [^"\\\\] | "\\\\" ["\\\\/bfnrt] | "\\\\u" [0-9a-fA-F]{{4}}
ws          ::= [ \\t\\n]*
'''


def _obj(props: dict) -> dict:
    """A closed object — every property required, no extras.

    ⚠️ `additionalProperties: false` AND a full `required` list, on EVERY
    object. OpenAI-style structured outputs treat an absent `required` as
    „all optional", so a provider may legally return `{}` — which validates
    against the schema and is refused by `analyze_articles.py`, i.e. the
    exact grammatically-perfect-and-always-refused failure the GBNF header
    warns about.
    """
    return {"type": "object", "properties": props,
            "required": sorted(props), "additionalProperties": False}


def build_json_schema(doc: dict) -> dict:
    """The same contract as the GBNF, for providers that have no GBNF.

    ⚠️ DERIVED FROM THE SAME CONSTANTS as build_grammar — never hand-written
    beside it. Two copies of one schema drift, and the way they drift is that
    one permits a label the validator rejects, producing records that are
    perfectly formed and refused 100% of the time.

    ⚠️ It carries the SAME stated limit: the category/subcategory PAIRING is
    not expressible here either. JSON Schema could express it as a oneOf over
    26 categories, but no provider guarantees oneOf support in structured
    outputs, and a schema a provider silently downgrades is worse than one
    that states its limit. The validator knows which pairs exist.

    ⚠️ `prob` is bounded [0,1] by `minimum`/`maximum`, which is STRICTER than
    the GBNF can be — the grammar has to spell the range out as literals. A
    provider that ignores numeric bounds degrades to the GBNF's own coverage,
    never below it.
    """
    cats = [c["id"] for c in doc.get("categories") or []]
    subs = sorted({s["id"] for c in doc.get("categories") or []
                   for s in c.get("subcategories") or []})
    string = {"type": "string", "minLength": 1}
    str0 = {"type": "string"}
    strings = {"type": "array", "items": string}
    prob = {"type": "number", "minimum": 0, "maximum": 1}
    labelled = lambda vals: _obj({
        "label": {"type": "string", "enum": sorted(vals)},
        "confidence": prob, "evidence": string})
    return _obj({
        "quality": _obj({
            "verdict": {"type": "string",
                        "enum": sorted(aa.QUALITY_VERDICTS)},
            "notes": str0}),
        "summary_bg": string,
        "summary_en": string,
        "leaning": labelled(aa.LEANING_LABELS),
        "russia_stance": labelled(aa.RUSSIA_LABELS),
        "ai_generated": _obj({
            "verdict": {"type": "string", "enum": sorted(aa.AI_VERDICTS)},
            "confidence": prob, "signals": strings}),
        "entities": _obj({k: strings for k in
                          ("people", "parties", "institutions",
                           "companies", "places")}),
        "party_tones": {"type": "array", "items": _obj({
            "party": string,
            "tone": {"type": "string", "enum": sorted(aa.TONE_LABELS)},
            "confidence": prob,
            "evidence": string})},
        "topics": {"type": "array", "items": _obj({
            "category": {"type": "string", "enum": sorted(cats)},
            # ⚠️ NULLABLE, and expressed as a type UNION rather than as an
            # enum containing None — a topic with no subcategory is the
            # common case, and an enum of strings cannot admit null.
            "subcategory": {"type": ["string", "null"], "enum":
                            sorted(subs) + [None]},
            "primary": {"type": "boolean"}})},
        "site_relevant": {"type": "boolean"},
    })


def write(check: bool) -> int:
    doc = json.loads(TOPICS.read_text(encoding="utf-8"))
    outputs = {
        PROMPTS / "analyze_system.md": SYSTEM_SOURCE.read_text(
            encoding="utf-8"),
        PROMPTS / "taxonomy_compact.json": json.dumps(
            {"version": doc.get("version"),
             "categories": compact_taxonomy(doc)},
            ensure_ascii=False, indent=1) + "\n",
        PROMPTS / "analyze_schema.gbnf": build_grammar(doc),
        PROMPTS / "analyze_schema.json": json.dumps(
            build_json_schema(doc), ensure_ascii=False, indent=1) + "\n",
    }
    stale = []
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        stale.append(path.name)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    result = {"prompts": str(PROMPTS), "stale": stale,
              "taxonomy_version": doc.get("version"),
              "max_body_chars": MAX_BODY_CHARS}
    print(json.dumps(result, ensure_ascii=False))
    # ⚠️ --check exits non-zero on drift so a gate can fail rather than a
    # human noticing. A generated file edited by hand is how a grammar comes
    # to permit a label the validator rejects.
    return 1 if (check and stale) else 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="report drift and exit 1 instead of writing")
    return write(ap.parse_args().check)


if __name__ == "__main__":
    sys.exit(main())
