// The generated client artifacts are current with the Python that produced them.
//
// ⚠️⚠️ THIS FILE EXISTS BECAUSE THE PYTHON GATE NEVER RUNS IN CI.
// `test_gen_bucket_ts.py` is the only thing that compares
// `newsapp/app/sentimentScale.ts` + its vector fixture against
// `news/scripts/jev_scales.py`, and it reaches a runner only through
// `npm run news:test`, which appears only inside the operator-run
// `news:release:gate`. `.github/workflows/test.yml` has no Python step.
//
// The TypeScript half DOES run in CI — and it cannot catch this, because it
// compares the two GENERATED files against each other. A forgotten
// regeneration leaves both stale, in perfect agreement, and green. That is
// exactly the drift the generator exists to prevent, arrived at one step later.
//
// `news/scripts/**/*.test.mjs` is already in the vitest `node` project's
// include list, so this runs on every `npm run test:ci`.

import { describe, it, expect } from "vitest";
import { execFileSync } from "node:child_process";
import { readFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const GENERATOR = "news/scripts/gen_bucket_ts.py";
const OUT_TS = path.join(ROOT, "newsapp/app/sentimentScale.ts");
const OUT_VECTORS = path.join(ROOT, "newsapp/app/sentimentScale.vectors.json");

const python = () => {
  for (const bin of ["python3", "python"]) {
    try {
      execFileSync(bin, ["--version"], { stdio: "ignore" });
      return bin;
    } catch {
      /* try the next one */
    }
  }
  return null;
};

describe("generated sentiment-scale artifacts", () => {
  it("are current with jev_scales.py", () => {
    const bin = python();
    // ⚠️ SKIPPING IS NOT PASSING, and it must be loud. A silent skip on a
    // machine with no Python turns the one cross-language gate into a no-op
    // that reports success — which is the failure mode this file is about.
    if (!bin) {
      console.warn(
        `[gen_bucket_ts] no python on PATH — the staleness gate did NOT run. ` +
          `Run \`python3 ${GENERATOR} --check\` before trusting this suite.`,
      );
      expect(existsSync(OUT_TS)).toBe(true);
      return;
    }
    let failure = null;
    try {
      execFileSync(bin, [GENERATOR, "--check"], { cwd: ROOT, stdio: "pipe" });
    } catch (error) {
      failure = `${error.stderr ?? ""}${error.stdout ?? ""}`.trim() || String(error);
    }
    expect(
      failure,
      `The committed artifacts disagree with news/scripts/jev_scales.py.\n` +
        `Run \`python3 ${GENERATOR}\` and commit the result.\n${failure ?? ""}`,
    ).toBeNull();
  });

  it("both exist and announce that they are generated", () => {
    expect(existsSync(OUT_TS)).toBe(true);
    expect(existsSync(OUT_VECTORS)).toBe(true);
    const ts = readFileSync(OUT_TS, "utf8");
    expect(ts).toContain("GENERATED by");
    expect(ts).toContain(GENERATOR);
  });

  it("the .ts is formatted the way Prettier would write it", () => {
    // ⚠️ The gate that actually rewrites this file is Prettier, not
    // `Number.toString()`. They disagree on exponents (`1e+21` vs `1e21`), and
    // targeting the wrong one puts `eslint --fix` and `--check` in a standoff
    // where each undoes the other for ever. Checked against the tool here
    // rather than asserted in a docstring.
    let failure = null;
    try {
      execFileSync(
        "npx",
        ["prettier", "--check", "newsapp/app/sentimentScale.ts"],
        { cwd: ROOT, stdio: "pipe" },
      );
    } catch (error) {
      failure = `${error.stdout ?? ""}${error.stderr ?? ""}`.trim();
    }
    expect(
      failure,
      `The generator's output is not Prettier-clean, so \`eslint --fix\` will ` +
        `rewrite it and the staleness gate will then fail. Fix \`_num\` or the ` +
        `template in ${GENERATOR}.\n${failure ?? ""}`,
    ).toBeNull();
  }, 30_000);
});
