#!/usr/bin/env python3
"""The generated TypeScript twin is in sync with the Python it comes from.

Without this, editing `jev_scales.BUCKET_EDGES` and forgetting to regenerate
leaves the producer and the client bucketing on two different rules — the exact
failure the generator exists to prevent, arrived at one step later. Nothing else
reports it: both sides compile, both render, and only articles near an edge
disagree.
"""
import json
import sys
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import gen_bucket_ts as gen  # noqa: E402
import jev_axes as ax  # noqa: E402
import jev_scales as js  # noqa: E402


class Generated(unittest.TestCase):
    def test_both_artifacts_are_byte_identical_to_what_the_generator_emits(self):
        self.assertTrue(gen.OUT_TS.exists(), gen.OUT_TS)
        self.assertTrue(gen.OUT_VECTORS.exists(), gen.OUT_VECTORS)
        self.assertEqual(gen.OUT_TS.read_text(encoding="utf-8"), gen.build_ts())
        self.assertEqual(gen.OUT_VECTORS.read_text(encoding="utf-8"), gen.build_vectors())

    def _check(self):
        argv = sys.argv
        try:
            sys.argv = ["gen_bucket_ts.py", "--check"]
            return gen.main()
        finally:
            sys.argv = argv

    def test_check_mode_passes_on_the_files_on_disk(self):
        self.assertEqual(self._check(), 0)

    def test_check_mode_can_actually_fail(self):
        # ⚠️ A gate nobody has seen fail is a gate nobody knows works. The
        # assertion above is satisfied by a `--check` that returns 0
        # unconditionally, which is the one implementation that would let the
        # drift through.
        original = gen.OUT_TS.read_text(encoding="utf-8")
        try:
            gen.OUT_TS.write_text(original + "// drift\n", encoding="utf-8")
            self.assertEqual(self._check(), 1)
        finally:
            gen.OUT_TS.write_text(original, encoding="utf-8")
        self.assertEqual(self._check(), 0)

    def test_the_file_says_it_is_generated_and_names_the_command(self):
        # A generated file that does not announce itself gets hand-edited once.
        text = gen.OUT_TS.read_text(encoding="utf-8")
        self.assertIn("GENERATED by", text)
        self.assertIn(gen.GENERATOR, text)
        self.assertIn("Do not edit by hand", text)

    def test_the_emitted_edges_and_tolerance_are_the_python_ones(self):
        text = gen.OUT_TS.read_text(encoding="utf-8")
        # Through `_num`, because Python and JS spell exponents differently
        # and the literal in the file is the JS spelling.
        self.assertIn(f"[{', '.join(gen._num(e) for e in js.BUCKET_EDGES)}]", text)
        self.assertIn(f"EDGE_TOLERANCE = {gen._num(js.EDGE_TOLERANCE)}", text)

    def test_number_literals_are_spelled_the_way_PRETTIER_writes_them(self):
        # ⚠️ TWO GATES IN A STANDOFF, and the target is PRETTIER — not
        # `Number.toString()`. `repr(1e-09)` is "1e-09" and prettier writes
        # "1e-9"; JS writes "1e+21" and prettier writes "1e21". Emitting the
        # runtime's spelling leaves `eslint --fix` rewriting the file, which
        # makes it stale against `--check`, which rewrites it back — they then
        # fail alternately for ever. The `.test.mjs` sibling runs prettier
        # itself, so this claim is checked against the tool too.
        text = gen.OUT_TS.read_text(encoding="utf-8")
        self.assertNotRegex(text, r"e[+-]?0\d", "zero-padded exponent")
        self.assertNotRegex(text, r"e\+", "prettier strips a positive exponent sign")
        self.assertEqual(gen._num(1e-9), "1e-9")
        self.assertEqual(gen._num(-0.75), "-0.75")
        self.assertEqual(gen._num(1e21), "1e21")
        self.assertEqual(gen._num(1.5e-7), "1.5e-7")

    def test_the_emitted_vocabularies_have_no_array_holes(self):
        # ⚠️ The generator joined entries that already carried their trailing
        # comma WITH a comma, emitting `"a",,` — which TypeScript reads as an
        # array HOLE, so a 5-label vocabulary arrived as 9 entries and
        # `bucketLabel` refused it. Invisible to every Python test; caught only
        # by the cross-language fixture.
        text = gen.OUT_TS.read_text(encoding="utf-8")
        self.assertNotIn(",,", text)
        for name, labels in (("TONE_BUCKET_ORDER", ax.SUBJECT_TONE.labels),
                             ("LEANING_BUCKET_ORDER", ax.LEANING.labels),
                             ("RUSSIA_BUCKET_ORDER", ax.RUSSIA_STANCE.labels)):
            start = text.index(f"export const {name} = [")
            block = text[start:text.index("] as const;", start)]
            self.assertEqual(block.count('"') // 2, len(labels), name)

    def test_every_display_vocabulary_is_emitted_in_order(self):
        doc = json.loads(gen.OUT_VECTORS.read_text(encoding="utf-8"))
        self.assertEqual(doc["vocabularies"]["TONE_BUCKET_ORDER"],
                         list(ax.SUBJECT_TONE.labels))
        self.assertEqual(doc["vocabularies"]["LEANING_BUCKET_ORDER"],
                         list(ax.LEANING.labels))
        self.assertEqual(doc["vocabularies"]["RUSSIA_BUCKET_ORDER"],
                         list(ax.RUSSIA_STANCE.labels))


    def test_the_vector_fixture_is_protected_from_prettier(self):
        # ⚠️ LOAD-BEARING, NOT HOUSEKEEPING. Prettier collapses short JSON
        # arrays onto one line and rewrites `1e-09`, which this generator
        # cannot reproduce — so without the ignore entry, formatting the file
        # makes it stale against `--check`, which rewrites it back. The
        # sibling `.ts` is deliberately NOT ignored: it is imported source and
        # the generator emits it Prettier-clean.
        ignore = (gen.ROOT / ".prettierignore").read_text(encoding="utf-8")
        rel = str(gen.OUT_VECTORS.relative_to(gen.ROOT))
        self.assertIn(rel, ignore)
        self.assertNotIn(str(gen.OUT_TS.relative_to(gen.ROOT)), ignore)


class Vectors(unittest.TestCase):
    """The fixture is the half a hand-edited `.ts` cannot satisfy."""

    def setUp(self):
        self.doc = json.loads(gen.OUT_VECTORS.read_text(encoding="utf-8"))

    def test_every_case_reproduces_the_python_implementation(self):
        scales = {5: ax.SUBJECT_TONE, 9: ax.SUBJECT_TONE_9}
        for case in self.doc["cases"]:
            scale = scales[case["levels"]]
            self.assertEqual(js.bucket_index(case["value"], scale), case["bucket"],
                             case)
            self.assertAlmostEqual(js.normalize(case["value"], scale),
                                   case["normalized"], places=12)

    def test_it_covers_both_anchor_counts_and_every_bucket(self):
        # A fixture that only ever lands in the middle bucket would pass any
        # implementation that always returned 2.
        levels = {case["levels"] for case in self.doc["cases"]}
        self.assertEqual(levels, {5, 9})
        for n in levels:
            buckets = {c["bucket"] for c in self.doc["cases"] if c["levels"] == n}
            self.assertEqual(buckets, set(range(len(js.BUCKET_EDGES) + 1)), n)

    def test_it_carries_the_edge_neighbourhoods_a_round_number_sweep_misses(self):
        # The asymmetry this rule actually had lived a few ULPs from an edge,
        # where a sweep of hundredths never lands.
        near = 0
        for case in self.doc["cases"]:
            n = abs(case["normalized"])
            for edge in js.BUCKET_EDGES:
                if 0 < abs(n - abs(edge)) < 1e-5:
                    near += 1
                    break
        self.assertGreaterEqual(near, 20, "no edge-neighbourhood cases")

    def test_no_case_is_an_exact_duplicate(self):
        # The edge neighbourhoods overlap the round-number sweep at eps = 0,
        # so the count was ten higher than the coverage it described.
        keys = [(c["levels"], repr(c["value"])) for c in self.doc["cases"]]
        self.assertEqual(len(keys), len(set(keys)))

    def test_every_case_carries_the_label_python_computed(self):
        scales = {5: ax.SUBJECT_TONE, 9: ax.SUBJECT_TONE_9}
        for case in self.doc["cases"]:
            scale = scales[case["levels"]]
            expected = ax.SUBJECT_TONE.labels[js.bucket_index(case["value"], scale)]
            self.assertEqual(case["label"], expected, case)

    def test_it_carries_the_live_float_reproduction(self):
        # value 0.49999999999999994 and its exact negation must bucket as
        # mirrors; they did not before the tolerance was made two-sided.
        drifted = [c for c in self.doc["cases"]
                   if c["levels"] == 5 and abs(abs(c["value"]) - 0.5) < 1e-15
                   and abs(c["value"]) != 0.5]
        self.assertTrue(drifted, "the 0.49999999999999994 case is missing")
        by_value = {c["value"]: c["bucket"] for c in drifted}
        for value, bucket in by_value.items():
            if -value in by_value:
                self.assertEqual(bucket, len(js.BUCKET_EDGES) - by_value[-value], value)


if __name__ == "__main__":
    unittest.main()
