// Resolve НЗОК procedure codes to their official НРД name. The clinical-activity
// feed (nhif.bg monthly reports) carries only the CODE and its type — P→КП
// (клинична пътека), A→АПр (амбулаторна процедура), K→КПр (клинична процедура). The
// names come from data/budget/nzok/procedures.json, generated by
// scripts/nzok/write_procedure_names.ts from НЗОК's НРД Приложение 17 (клинични
// пътеки) + 18 (амбулаторни процедури) + the клинични-процедури list.
//
// Codes look like "P240", "P265.1", "P050B1", "A06E", "K03". The ".N" suffix
// (P004.1, P265.3) marks a DISTINCT named pathway variant and is kept. A trailing
// billing MODIFIER shares the base entry's name and is stripped on a miss:
//   ·  "A99"     diagnosis-group variant   P240A99 → P240
//   ·  "B1"/"B2"                            P050B1  → P050
//   ·  "E"       extended                   A06E    → A06
// The source publishes no English name (these are Bulgarian health-system
// designations), so the same БГ name is returned regardless of UI language — it is
// far more legible than a bare code.

export type NzokProcedureNames = Record<string, string>;

// Standalone per-procedure page (/procedure/:code). Codes can carry dots and
// Cyrillic letters — encodeURIComponent handles both; react-router decodes the
// param back to the exact stored string the DB function matches on.
export const procedureHref = (code: string): string =>
  `/procedure/${encodeURIComponent(code)}`;

// The three НЗОК activity kinds, derived upstream from the code's first letter
// (P→КП, A→АПр, K→КПр). The source ships only the abbreviation; we spell it out.
export const PROC_TYPE_LABEL: Record<string, { bg: string; en: string }> = {
  КП: { bg: "Клинична пътека", en: "Clinical pathway" },
  АПр: { bg: "Амбулаторна процедура", en: "Ambulatory procedure" },
  КПр: { bg: "Клинична процедура", en: "Clinical procedure" },
};
export const procTypeLabel = (t: string, bg: boolean): string => {
  const l = PROC_TYPE_LABEL[t];
  return l ? (bg ? l.bg : l.en) : t;
};

const MODIFIER = /(A99|B[12]|E)$/;

/** The official НРД name for a procedure code, or null when it isn't in the
 *  dictionary (caller falls back to showing the code). */
export const resolveProcedureName = (
  names: NzokProcedureNames | null | undefined,
  code: string,
): string | null => {
  if (!names) return null;
  const c = code.trim().toUpperCase();
  if (names[c]) return names[c];
  const base = c.replace(MODIFIER, "");
  if (base !== c && names[base]) return names[base];
  return null;
};
