// `buildAdminFlow()` reads the ministries DIRECTORY (fs.readdirSync) rather than the
// `ministryRollups` array the same run just produced, so it is only correct while the
// two agree. They stop agreeing the moment a node id is RETIRED: the old file is still
// on disk until `pruneDir(MINISTRIES_DIR, …)` runs, and the unit gets summed twice —
// once under each id.
//
// Measured 2026-08-14, when a slugify fix folded МРРБ's soft-hyphen node into the
// canonical one and the prune still ran afterwards: FY2019's `plannedTotalEur` came out
// €4,991,621,668 against the true €4,727,440,425 — over by exactly МРРБ's €264,181,243,
// with both node ids listed. The ingest exited 0 and nothing else moved.
//
// ⚠ THE TWO OBVIOUS ASSERTIONS DO NOT CATCH IT, and both were proposed in review before
// being run against the bad build:
//   • "no duplicate nodeId per year" — the whole point is that the two ids DIFFER
//     (`…-blago-ustroystvoto` vs `…-blagoustroystvoto`). Measured: does not fire.
//   • "Σ(units) == plannedTotalEur" — `plannedTotalEur` is ACCUMULATED from the same
//     rows (derived_admin_flow.ts:167), so it agrees with their sum by construction and
//     cannot disagree with it for any input. Measured: does not fire, and it is vacuous
//     rather than merely weak.
// What actually discriminates is the id's PROVENANCE: a retired id is one the registry
// no longer emits. That is asserted first below, and it fires whatever the retired
// node happened to be called.

import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

const ROOT = path.resolve("data/budget");
const ADMIN_FLOW = path.join(ROOT, "derived/admin_flow.json");
const ADMIN_REGISTRY = path.join(ROOT, "classification/admin.json");

const INVISIBLE = /[\p{Cf}͏︀-️]/u;

interface Unit {
  nodeId: string;
  nameBg?: string;
  plannedEur: number | null;
}
interface Year {
  ministries?: Unit[];
  plannedTotalEur?: number | null;
}

const read = <T>(p: string): T | null =>
  fs.existsSync(p) ? (JSON.parse(fs.readFileSync(p, "utf8")) as T) : null;

const flow = read<{ fiscalYears: Record<string, Year> }>(ADMIN_FLOW);
const registry = read<{ nodes: { id: string }[] }>(ADMIN_REGISTRY);

// Both are generated by `npm run budget:ingest`; a fresh clone that has never run it
// has nothing to check.
describe.skipIf(!flow || !registry)("admin_flow.json", () => {
  const years = Object.entries(flow?.fiscalYears ?? {});
  const known = new Set((registry?.nodes ?? []).map((n) => n.id));

  it("has years and a registry to check against", () => {
    // Without this every per-year loop below is absence-equivalent: an empty
    // fiscalYears map satisfies all of them and the file passes greener than ever.
    expect(years.length).toBeGreaterThan(5);
    expect(known.size).toBeGreaterThan(40);
  });

  it("names only spending units the registry still emits", () => {
    // THE gate. A node id in the flow that the registry has retired means
    // buildAdminFlow() read a stale file — i.e. it ran before the prune — and that
    // unit is in the year twice, under its old id and its new one.
    const orphans: string[] = [];
    for (const [fy, y] of years)
      for (const m of y.ministries ?? [])
        if (!known.has(m.nodeId)) orphans.push(`FY${fy}: ${m.nodeId}`);
    expect(orphans).toEqual([]);
  });

  it("lists each spending unit once per year, by name as well as by id", () => {
    // The same defect reached through the other door: two ids for one unit are
    // still two rows with one name. Catches a re-slug even if both ids are
    // somehow live.
    const dupes: string[] = [];
    for (const [fy, y] of years) {
      const seen = new Map<string, string>();
      for (const m of y.ministries ?? []) {
        const key = (m.nameBg ?? m.nodeId).replace(INVISIBLE, "").trim();
        const prev = seen.get(key);
        if (prev) dupes.push(`FY${fy}: ${key} — ${prev} + ${m.nodeId}`);
        seen.set(key, m.nodeId);
      }
    }
    expect(dupes).toEqual([]);
  });

  it("carries no invisible formatting marks in a rendered name", () => {
    // The display half of the slug defect: ids can be correct while the label a
    // reader sees still holds the U+00AD that split them.
    const bad: string[] = [];
    for (const [fy, y] of years)
      for (const m of y.ministries ?? [])
        if (INVISIBLE.test(m.nameBg ?? ""))
          bad.push(`FY${fy}: ${JSON.stringify(m.nameBg)}`);
    expect(bad).toEqual([]);
  });
});
