import { useChatNavigation } from "./navigation";
import { SITE_ORIGIN, SITE_HOST } from "@/lib/siteOrigin";
import { chatPath } from "./navigationPaths";
import { ToolGradSection } from "./ToolGradSection";
// Current production-router measurements; historical experiments stay explicitly separate.
import { useContext, useEffect, useState } from "react";
import { Logo } from "@/layout/header/Logo";
import { Button } from "@/components/ui/button";
import { ThemeContext } from "@/theme/ThemeContext";
import { themeDark, themeLight } from "@/theme/utils";
import { fetchData } from "../tools/dataClient";
import type { Lang } from "../tools/types";
import type { EvalCase, EvalScore } from "../llm/currentEval";
import type {
  CompactMetrics,
  DeterministicMetrics,
  GateSweep,
} from "../llm/evalsIndex";
type Metrics = {
  n: number;
  toolAcc: number | null;
  callAcc: number | null;
  argN: number;
  argAcc: number | null;
  jsonValidRate: number | null;
  irrelevanceAcc: number | null;
  errors: number;
};
type Run = {
  label: string;
  model: string;
  provider: string;
  startedAt: string;
  finishedAt: string;
  toolCount: number;
  caseCount: number;
  retriedErrors?: number;
  promptHash: string;
  suiteHash: string;
  registryHash: string;
  scoringHash?: string;
  replaySource?: string;
  settings: {
    max_tokens: number;
    temperature: number;
    reasoning_effort: string;
  };
  metrics: Record<Lang, Metrics>;
  groups: Record<string, Record<Lang, Metrics>>;
  cases: EvalCase[];
  rows: EvalScore[];
};
type Legacy = {
  generatedAt: string;
  method: { toolCount: number; caseCount: number };
  models: {
    id: string;
    label: string;
    toolMode?: string;
    perLang: Record<Lang, { toolAcc: number }> | null;
  }[];
};
// The published-run manifest (`data/ai/evals/index.json`), generated by
// ai/llm/evalsIndex.ts from every `current_*.json` on disk. The page reads THIS rather
// than hardcoding filenames, so a new run appears without editing the page and a
// renamed artifact cannot leave a dead link behind.
export type RunSummary = {
  file: string;
  label: string;
  artifactLabel?: string | null;
  model: string | null;
  finishedAt: string | null;
  caseCount: number;
  caseGroups: string[] | null;
  routingBudget: number | null;
  forcedBudget: boolean;
  metrics: Record<Lang, SummarisedMetrics>;
  groups: Record<string, Record<Lang, SummarisedMetrics>>;
  goldInCandidates: { kept: number; total: number } | null;
  meanCandidatesKept: number | null;
};
// DERIVED from the producer, never restated here. The page used to hand-mirror
// `compact()`'s output, so a renamed key left this file rendering `undefined`
// → "—" with nothing failing — the silent degradation this page is otherwise
// careful about. The import is type-only: `evalsIndex.ts` reads the filesystem
// at call time, and a value import would pull `node:fs` into the bundle.
export type SummarisedMetrics = CompactMetrics;
export type DeterministicEval = {
  generatedAt: string;
  caseCount: number;
  caseGroups: string[] | null;
  metrics: Record<Lang, DeterministicMetrics> | null;
  legacyMetrics: Record<Lang, DeterministicMetrics> | null;
};
export type EvalsIndex = {
  generatedAt: string;
  runs: RunSummary[];
  deterministic: DeterministicEval | null;
  /** Absent on a manifest built before the sweep existed. */
  gateSweep?: GateSweep | null;
};
type Recall = {
  generatedAt: string;
  rows: {
    id: string;
    label: Record<Lang, string>;
    declined: Record<string, number>;
  }[];
};
const pct = (v: number | null | undefined) =>
  v == null ? "—" : `${(v * 100).toFixed(1)}%`;

/** The two model lanes' artifacts, by FILENAME — the manifest's own identity
 *  rule (a label inside an artifact can be copied by a re-scored replay).
 *
 *  ⚠️ `CLOUD_RUN_FILE` is NAMED rather than found, and that is the whole point.
 *  It used to be "the first non-Jev run with metrics", and `runs` is sorted by
 *  `finishedAt` DESCENDING — so it resolved to whichever experiment was
 *  published last, which on the committed manifest is the 367-case
 *  starter-prompts-only bank. The page then stated that the cloud model scored
 *  57.8% usable call, below the keyword router's 85.9%, when its production run
 *  is 85.9%; and that Jev beat it on selection 90.6% to 82.6%, when on the
 *  production run the cloud model WINS that column 96.0% to 90.6%. The
 *  published ranking was inverted, and publishing any new artifact would have
 *  re-pointed the lane again with no test failing. */
const JEV_RUN_FILE = "current_jev.json";
const CLOUD_RUN_FILE = "current_production.json";

/**
 * Three lanes, one bank, side by side: the deterministic keyword router, the
 * cloud model, and Jev.
 *
 * ⚠️ THREE THINGS THIS SECTION MUST NOT LET A READER ASSUME.
 *
 * 1. That the rows are comparable when they are not. Every lane here is scored
 *    by the same functions on the same case bank, but a run can be narrowed or
 *    re-scored, so the CASE COUNT is shown per lane and a mismatch is called
 *    out rather than quietly averaged. The check is on the count AND the group
 *    set: two runs of equal size over different banks are the one case where
 *    the visible "Cases" column would agree and the rows still would not be.
 * 2. That accuracy alone ranks them. Jev is the only lane that can decline, and
 *    a lane answering 60% of turns at 99% is a different product from one
 *    answering all of them at 96% — so its decline rate and its accuracy on the
 *    turns it did route are shown beside the headline, not behind a link.
 * 3. That the abstention columns share a denominator. They do not, and this is
 *    the trap in (2) arriving one level down: `toolAccWhenRouted` is measured
 *    over the `jevRouted` subset (71.3% EN on the 2026-09-18 artifact), while
 *    `jevDeclined` is a share of ALL turns. Rendering the 99% beside a 1.3%
 *    decline rate publishes the "99%" of the example in (2) with the "60% of
 *    turns" removed — so `jevRouted` gets its own column and the accuracy
 *    column names the base it is measured on. The headline "Selection" column
 *    is unaffected and must stay as it is: `toolAcc` is computed over every
 *    row, so it already charges Jev for the turns it did not route.
 */
const LaneComparison = ({
  index,
  t,
}: {
  index: EvalsIndex | null;
  t: (bg: string, en: string) => string;
}) => {
  const jev = index?.runs.find((r) => r.file === JEV_RUN_FILE);
  const cloud = index?.runs.find((r) => r.file === CLOUD_RUN_FILE);
  const deterministic = index?.deterministic;
  // All THREE or nothing. The cloud lane used to be optional, which rendered a
  // two-row table under a heading that says "three routers" — and after the
  // selection above became exact, a manifest without the production run reaches
  // it in an ordinary way (a pruned checkout, a renamed artifact).
  if (!jev || !cloud || !deterministic?.metrics) return null;

  type Lane = {
    id: string;
    name: string;
    note: string;
    cases: number;
    groups: string[] | null;
    // The lanes carry DIFFERENT metric shapes on purpose — only Jev has the
    // abstention fields — so the union is written out rather than inferred.
    m: Record<Lang, DeterministicMetrics & Partial<SummarisedMetrics>>;
    /** Can this lane abstain at all? Distinct from "did we measure how often",
     *  which is what a null field means. */
    declines: boolean;
  };
  const lanes: Lane[] = [
    {
      id: "deterministic",
      name: t("Без AI (правила)", "No AI (rules)"),
      note: t("без модел, безплатно", "no model, free"),
      cases: deterministic.caseCount,
      groups: deterministic.caseGroups,
      m: deterministic.metrics,
      declines: false,
    },
    {
      id: "cloud",
      name: cloud.model ?? cloud.label,
      // The run is named, not just the model: two artifacts share this model
      // name and differ by 28 points, so the row must say which one it is.
      note: `${t("облачен модел", "cloud model")} · ${cloud.label}`,
      cases: cloud.caseCount,
      groups: cloud.caseGroups,
      m: cloud.metrics,
      declines: false,
    },
    {
      id: "jev",
      name: t("Jev (TypeSafe)", "Jev (TypeSafe)"),
      note: t("типизиран избор", "typed choice"),
      cases: jev.caseCount,
      groups: jev.caseGroups,
      m: jev.metrics,
      declines: true,
    },
  ];
  const counts = [...new Set(lanes.map((l) => l.cases))];
  // Equal counts over different GROUPS are still not comparable, and that is
  // the case a reader cannot see: the "Cases" column would agree.
  const banks = new Set(
    lanes.map(
      (l) => `${l.cases}:${[...(l.groups ?? [])].sort().join("+") || "?"}`,
    ),
  );
  /** "Not applicable" and "not measured" are different claims and only one of
   *  them is a fact about the product — so a lane that CAN decline but whose
   *  artifact predates these fields must not render the same em dash as one
   *  that has no decline mechanism at all. */
  const abstention = (l: Lane, key: "jevRouted" | "jevDeclined") =>
    !l.declines
      ? "—"
      : l.m.en[key] == null && l.m.bg[key] == null
        ? t("не е измерено", "not measured")
        : `${pct(l.m.en[key])} / ${pct(l.m.bg[key])}`;

  return (
    <section>
      <h2 className="font-title text-xl text-popover-foreground">
        {t("Трите маршрутизатора, един корпус", "Three routers, one corpus")}
      </h2>
      <p className="mt-2 max-w-3xl text-sm text-muted-foreground">
        {t(
          "Едни и същи задачи, едни и същи правила за оценяване — различава се само кой избира инструмента. Само Jev може да откаже да отговори, затова до точността стои и колко често отказва: маршрутизатор, който отговаря на 60% от въпросите с 99% точност, е различен продукт от такъв, който отговаря на всички с 96%.",
          "The same cases and the same scoring rules — only the choice of router differs. Jev is the only lane that can decline, so its decline rate sits beside its accuracy: a router answering 60% of turns at 99% is a different product from one answering all of them at 96%.",
        )}
      </p>
      <p className="mt-2 max-w-3xl text-sm text-muted-foreground">
        {t(
          "Колоните „Избор“ и „Използваемо извикване“ са върху всички задачи, така че маршрутизаторът се наказва и за ходовете, които не е поел. „Точност върху поетите“ е върху друг знаменател — само върху поетите ходове — затова колко е поел стои в собствена колона до нея.",
          "The “Selection” and “Usable call” columns are over every case, so a router is charged for the turns it did not take. “Accuracy over routed” has a different denominator — only the turns it did take — so how many those were sits in its own column beside it.",
        )}
      </p>
      {banks.size > 1 && (
        <p className="mt-2 max-w-3xl text-sm text-destructive">
          {counts.length > 1
            ? t(
                `Внимание: сравняваните измервания са върху различен брой задачи (${counts.join(", ")}), така че редовете не са пряко съпоставими.`,
                `Caution: these measurements cover different case counts (${counts.join(", ")}), so the rows are not directly comparable.`,
              )
            : t(
                "Внимание: измерванията са върху еднакъв брой задачи, но върху различни набори, така че редовете не са пряко съпоставими.",
                "Caution: these measurements cover the same number of cases but different banks, so the rows are not directly comparable.",
              )}
        </p>
      )}
      <div className="mt-3 overflow-x-auto">
        <table className="w-full text-left text-sm">
          <thead>
            <tr className="border-b-2">
              <th className="p-2">{t("Маршрутизатор", "Router")}</th>
              <th className="p-2">{t("Задачи", "Cases")}</th>
              <th className="p-2">{t("Избор EN / BG", "Selection EN / BG")}</th>
              <th className="p-2">
                {t("Използваемо извикване EN / BG", "Usable call EN / BG")}
              </th>
              <th className="p-2">{t("Поема EN / BG", "Routes EN / BG")}</th>
              <th className="p-2">
                {t("Отказва EN / BG", "Declines EN / BG")}
              </th>
              <th className="p-2">
                {t(
                  "Точност върху поетите EN / BG",
                  "Accuracy over routed EN / BG",
                )}
              </th>
              <th className="p-2">
                {t("Мълчи, когато трябва EN / BG", "Correctly silent EN / BG")}
              </th>
            </tr>
          </thead>
          <tbody>
            {lanes.map((l) => (
              <tr key={l.id} data-lane={l.id} className="border-b">
                {/* A row header, not a cell: a screen reader announcing
                    "99.0% / 97.6%" must be told which lane it belongs to, on
                    the table whose whole purpose is attributing numbers to
                    lanes. */}
                <th scope="row" className="p-2 font-medium">
                  {l.name}
                  <span className="ml-2 text-xs font-normal text-muted-foreground">
                    {l.note}
                  </span>
                </th>
                <td className="p-2 tabular-nums">{l.cases}</td>
                <td className="p-2 tabular-nums">
                  {pct(l.m.en.toolAcc)} / {pct(l.m.bg.toolAcc)}
                </td>
                <td className="p-2 tabular-nums">
                  {pct(l.m.en.callAcc)} / {pct(l.m.bg.callAcc)}
                </td>
                {/* An em dash, not 0%: a lane with no decline mechanism has no
                    decline RATE, and printing 0% would claim it measured one. */}
                <td className="p-2 tabular-nums">
                  {abstention(l, "jevRouted")}
                </td>
                <td className="p-2 tabular-nums">
                  {abstention(l, "jevDeclined")}
                </td>
                <td className="p-2 tabular-nums">
                  {l.declines
                    ? `${pct(l.m.en.toolAccWhenRouted)} / ${pct(l.m.bg.toolAccWhenRouted)}`
                    : "—"}
                </td>
                {/* Abstention QUALITY, and the one abstention column the cloud
                    lane also reports — so it is not guarded on `declines`. */}
                <td className="p-2 tabular-nums">
                  {l.m.en.irrelevanceAcc == null &&
                  l.m.bg.irrelevanceAcc == null
                    ? "—"
                    : `${pct(l.m.en.irrelevanceAcc)} / ${pct(l.m.bg.irrelevanceAcc)}`}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
};
/**
 * The Jev confidence-gate sweep: what the lane would score at each gate
 * between 0.50 and the published one.
 *
 * ⚠️ THE COLUMN THAT DECIDES IT IS THE HEAD-TO-HEAD, not the overall figures.
 * A lower gate changes only the turns it hands from the rules to Jev, so
 * overall selection moves by tenths of a point and reads as "about the same".
 * On exactly the turns that move, the question is whether Jev beats the rules
 * it replaces — so those two rates sit side by side, and the takeaway sentence
 * is COMPUTED from them rather than written here, where it would go stale the
 * next time the sweep is run.
 *
 * On the published gate's own row the head-to-head is shown as "—". Rows
 * "gained" there are not gained by any gate change; they are below-gate turns
 * whose re-asked confidence came back above it, i.e. Jev's run-to-run
 * variation. The method note states that count instead.
 */
const GateSweepSection = ({
  sweep,
  t,
}: {
  sweep: GateSweep | null | undefined;
  t: (bg: string, en: string) => string;
}) => {
  if (!sweep?.sweep.length) return null;
  const lower = sweep.sweep.filter((s) => s.gate < sweep.publishedGate);
  const worse = (lang: Lang) =>
    lower.filter(
      (s) =>
        s.metrics[lang].movedJevToolAcc != null &&
        s.metrics[lang].movedRulesToolAcc != null &&
        s.metrics[lang].movedJevToolAcc! < s.metrics[lang].movedRulesToolAcc!,
    ).length;
  const pair = (
    s: GateSweep["sweep"][number],
    k: Exclude<
      keyof GateSweep["sweep"][number]["metrics"]["en"],
      "n" | "moved"
    >,
  ) => `${pct(s.metrics.en[k])} / ${pct(s.metrics.bg[k])}`;
  const gateLabel = (g: number) => g.toFixed(3).replace(/0$/, "");

  return (
    <section>
      <h2 className="font-title text-xl text-popover-foreground">
        {t("Праг на увереност за Jev", "Jev confidence gate")}
      </h2>
      <p className="mt-2 max-w-3xl text-sm text-muted-foreground">
        {t(
          `Когато увереността на Jev е под прага (сега ${gateLabel(sweep.publishedGate)}), той не избира инструмента, а оставя хода на правилата. По-нисък праг дава на Jev повече ходове — въпросът е дали върху точно тези добавени ходове той е по-точен от правилата, които замества.`,
          `When Jev's confidence is below the gate (currently ${gateLabel(sweep.publishedGate)}), it does not pick the tool and leaves the turn to the rules. A lower gate hands Jev more turns — the question is whether, on exactly those added turns, it is more accurate than the rules it replaces.`,
        )}
      </p>
      {lower.length > 0 && (
        <p className="mt-2 max-w-3xl text-sm text-popover-foreground">
          {t(
            `Върху добавените ходове Jev избира правилния инструмент по-рядко от правилата при ${worse("en")} от ${lower.length} по-ниски прага на английски и при ${worse("bg")} от ${lower.length} на български.`,
            `On the added turns, Jev picks the right tool less often than the rules at ${worse("en")} of ${lower.length} lower gates in English and ${worse("bg")} of ${lower.length} in Bulgarian.`,
          )}
        </p>
      )}
      <div className="mt-3 overflow-x-auto">
        <table className="w-full text-left text-sm">
          <thead>
            <tr className="border-b-2">
              <th className="p-2">{t("Праг", "Gate")}</th>
              <th className="p-2">{t("Поема EN / BG", "Routes EN / BG")}</th>
              <th className="p-2">{t("Избор EN / BG", "Selection EN / BG")}</th>
              <th className="p-2">
                {t("Използваемо извикване EN / BG", "Usable call EN / BG")}
              </th>
              <th className="p-2">
                {t("Аргументи EN / BG", "Arguments EN / BG")}
              </th>
              <th className="p-2">
                {t("Мълчи, когато трябва EN / BG", "Correctly silent EN / BG")}
              </th>
              <th className="p-2">
                {t("Добавени ходове EN / BG", "Added turns EN / BG")}
              </th>
              <th className="p-2">
                {t(
                  "Избор върху добавените: Jev EN / BG",
                  "Selection on added: Jev EN / BG",
                )}
              </th>
              <th className="p-2">
                {t("…и правилата EN / BG", "…and the rules EN / BG")}
              </th>
            </tr>
          </thead>
          <tbody>
            {sweep.sweep.map((s) => {
              const current = s.gate === sweep.publishedGate;
              return (
                <tr
                  key={s.gate}
                  data-gate={s.gate}
                  className={current ? "border-b font-medium" : "border-b"}
                >
                  <th scope="row" className="p-2 font-medium tabular-nums">
                    {gateLabel(s.gate)}
                    {current && (
                      <span className="ml-2 text-xs font-normal text-muted-foreground">
                        {t("текущ", "current")}
                      </span>
                    )}
                  </th>
                  <td className="whitespace-nowrap p-2 tabular-nums">
                    {pair(s, "jevRouted")}
                  </td>
                  <td className="whitespace-nowrap p-2 tabular-nums">
                    {pair(s, "toolAcc")}
                  </td>
                  <td className="whitespace-nowrap p-2 tabular-nums">
                    {pair(s, "callAcc")}
                  </td>
                  <td className="whitespace-nowrap p-2 tabular-nums">
                    {pair(s, "argAcc")}
                  </td>
                  <td className="whitespace-nowrap p-2 tabular-nums">
                    {pair(s, "irrelevanceAcc")}
                  </td>
                  <td className="whitespace-nowrap p-2 tabular-nums">
                    {current
                      ? "—"
                      : `${s.metrics.en.moved} / ${s.metrics.bg.moved}`}
                  </td>
                  <td className="whitespace-nowrap p-2 tabular-nums">
                    {current ? "—" : pair(s, "movedJevToolAcc")}
                  </td>
                  <td className="whitespace-nowrap p-2 tabular-nums">
                    {current ? "—" : pair(s, "movedRulesToolAcc")}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
      <p className="mt-2 max-w-3xl text-xs text-muted-foreground">
        {t(
          `Как е измерено: ходовете, на които Jev е бил над текущия праг, се държат еднакво при всеки по-нисък праг и са взети наготово. Всеки от ${sweep.reasked}-те хода под прага е зададен отново точно веднъж, без праг, и всеки отговор е запазен — всички прагове са пресметнати от тази една извадка. Увереността на Jev леко варира между извикванията (средно с ${sweep.meanConfidenceDrift?.toFixed(3) ?? "—"}): ${sweep.crossedPublishedGate} от тези ходове се върнаха над текущия праг, затова редът „текущ“ се различава малко от публикуваното измерване по-горе.`,
          `How it was measured: turns Jev answered above the current gate behave the same at any lower gate and are reused as they are. Each of the ${sweep.reasked} below-gate turns was asked again exactly once, with no gate, and every answer was kept — all gates are computed from that one sample. Jev's confidence varies slightly between calls (by ${sweep.meanConfidenceDrift?.toFixed(3) ?? "—"} on average): ${sweep.crossedPublishedGate} of those turns came back above the current gate, so the “current” row differs slightly from the published measurement above.`,
        )}
      </p>
    </section>
  );
};

export const EvalsScreen = ({
  integrated = false,
}: { integrated?: boolean } = {}) => {
  const navigation = useChatNavigation();
  const { theme, setTheme } = useContext(ThemeContext);
  const [localLang, setLang] = useState<Lang>(navigation.lang);
  const lang = integrated ? navigation.lang : localLang;
  const [run, setRun] = useState<Run | null>(null),
    [baseline, setBaseline] = useState<Run | null>(null);
  const [legacy, setLegacy] = useState<Legacy | null>(null),
    [recall, setRecall] = useState<Recall | null>(null);
  const [index, setIndex] = useState<EvalsIndex | null>(null);
  const [error, setError] = useState(false),
    [failuresOnly, setFailuresOnly] = useState(true);
  const t = (bg: string, en: string) => (lang === "bg" ? bg : en);
  const Content = integrated ? "div" : "main";
  useEffect(() => {
    fetchData<Run>("/ai/evals/current_production.json")
      .then(setRun)
      .catch(() => setError(true));
    fetchData<Run>("/ai/evals/current_baseline_rescored.json")
      .then(setBaseline)
      .catch(() => {});
    fetchData<Legacy>("/ai/evals/fc_eval.json")
      .then(setLegacy)
      .catch(() => {});
    fetchData<Recall>("/ai/evals/retriever_recall.json")
      .then(setRecall)
      .catch(() => {});
    fetchData<EvalsIndex>("/ai/evals/index.json")
      .then(setIndex)
      .catch(() => {});
  }, []);
  const date = (s: string) =>
    new Date(s).toLocaleDateString(lang === "bg" ? "bg-BG" : "en-GB");
  const groupLabel = (g: string) =>
    ({
      registry: t(
        "Прегледани примери от регистъра",
        "Reviewed registry examples",
      ),
      realistic: t("Ежедневни въпроси", "Everyday questions"),
      conversation: t("Разговорни продължения", "Conversation follow-ups"),
      clarification: t(
        "Уточнение / неподдържано действие",
        "Clarification / unsupported action",
      ),
      challenge: t(
        "Авторски задачи за диагностика",
        "Authored diagnostic cases",
      ),
      holdout: t("Отделени контролни задачи", "Held-out checks"),
      unsupported: t("Неподдържани заявки", "Unsupported requests"),
      starter: t("Начални въпроси (чипове)", "Starter prompts (chips)"),
    })[g] ?? g;
  // Run labels are artifact names, so they are translated here rather than sent
  // translated: the file is the identity and must stay greppable.
  const runLabel = (label: string) =>
    ({
      production: t(
        "Пълен каталог (производство)",
        "Full catalogue (production)",
      ),
      narrowed: t(
        "Стеснен каталог (принудително)",
        "Narrowed catalogue (forced budget)",
      ),
      starter: t("Начални въпроси (чипове)", "Starter prompts (chips)"),
      revised: t("След корекциите", "After fixes"),
      baseline: t("Предишна инструкция", "Earlier prompt"),
      baseline_rescored: t(
        "Предишна инструкция (преизчислена)",
        "Earlier prompt (re-scored)",
      ),
    })[label] ?? label;
  const comparable =
    baseline &&
    run &&
    baseline.suiteHash === run.suiteHash &&
    baseline.scoringHash === run.scoringHash;
  return (
    <div className="flex min-h-dvh flex-col bg-card text-foreground">
      {!integrated && (
        <header className="flex flex-wrap items-center justify-between gap-2 border-b-2 bg-muted px-4 py-2.5 shadow-sm">
          <a
            href={chatPath("chat", navigation.pathname)}
            className="flex items-center gap-2 text-xl text-primary"
          >
            <Logo className="size-7" />
            <span className="font-title">Наясно AI</span>
          </a>
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => {
                const next = lang === "bg" ? "en" : "bg";
                if (!integrated) {
                  setLang(next);
                  return;
                }
                const path = navigation.pathname.replace(/^\/en/, "");
                window.location.assign(
                  `${next === "en" ? "/en" : ""}${path}${navigation.search}`,
                );
              }}
              aria-label={t("Език", "Language")}
            >
              {lang === "bg" ? "EN" : "BG"}
            </Button>
            <Button
              variant="outline"
              size="icon"
              onClick={() =>
                setTheme(theme === themeDark ? themeLight : themeDark)
              }
              aria-label={t("Тема", "Theme")}
            >
              {theme === themeDark ? "☀" : "☾"}
            </Button>
          </div>
        </header>
      )}
      <Content className="container mx-auto flex-1 space-y-8 px-4 py-8">
        <div>
          <h1 className="font-title text-3xl font-semibold text-popover-foreground">
            {t(
              "Оценка на AI инструментите (EN/BG)",
              "AI tool evaluation (EN/BG)",
            )}
          </h1>
          <p className="mt-3 max-w-3xl text-muted-foreground">
            {t(
              "Избира ли текущият модел правилния инструмент и подава ли използваеми аргументи? Измерваме Gemini 3.5 Flash-Lite с реалната подкана и валидатора на Наясно, на български и английски.",
              "Does the current model choose the right tool and supply usable arguments? We measure Gemini 3.5 Flash-Lite with Наясно’s actual prompt and validator, in Bulgarian and English.",
            )}
          </p>
        </div>
        <ToolGradSection lang={lang} />
        {error && (
          <p role="alert">
            {t(
              "Текущите резултати не можаха да се заредят.",
              "Current results could not be loaded.",
            )}
          </p>
        )}
        {!run && !error && <p>{t("Зареждане…", "Loading…")}</p>}
        {run && (
          <>
            <section aria-label={t("Текущ модел", "Current model")}>
              <h2 className="font-title text-2xl text-popover-foreground">
                Gemini 3.5 Flash-Lite
              </h2>
              <p className="mt-2 text-sm text-muted-foreground">
                {date(run.finishedAt)} · {run.toolCount}{" "}
                {t("инструмента", "tools")} · {run.caseCount}{" "}
                {t("двуезични задачи", "paired cases")} ·{" "}
                {run.caseCount * 2 + (run.retriedErrors ?? 0)}{" "}
                {t("реални API извиквания", "real API calls")}
              </p>
              <div className="mt-4 overflow-x-auto">
                <table className="w-full text-left text-sm">
                  <thead>
                    <tr className="border-b-2">
                      <th className="p-2">{t("Измерване", "Measurement")}</th>
                      <th className="p-2">
                        {t("Избор EN / BG", "Selection EN / BG")}
                      </th>
                      <th className="p-2">
                        {t(
                          "Използваемо извикване EN / BG",
                          "Usable call EN / BG",
                        )}
                      </th>
                      <th className="p-2">
                        {t("Аргументи EN / BG", "Arguments EN / BG")}
                      </th>
                      <th className="p-2">JSON EN / BG</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(comparable ? [baseline!, run] : [run]).map((r) => (
                      <tr key={r.label} className="border-b">
                        <th className="p-2 font-medium">{runLabel(r.label)}</th>
                        <td className="p-2 tabular-nums">
                          {pct(r.metrics.en.toolAcc)} /{" "}
                          {pct(r.metrics.bg.toolAcc)}
                        </td>
                        <td className="p-2 tabular-nums">
                          {pct(r.metrics.en.callAcc)} /{" "}
                          {pct(r.metrics.bg.callAcc)}
                        </td>
                        <td className="p-2 tabular-nums">
                          {pct(r.metrics.en.argAcc)} /{" "}
                          {pct(r.metrics.bg.argAcc)}
                        </td>
                        <td className="p-2 tabular-nums">
                          {pct(r.metrics.en.jsonValidRate)} /{" "}
                          {pct(r.metrics.bg.jsonValidRate)}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <p className="mt-3 max-w-3xl text-sm text-muted-foreground">
                {t(
                  "Избор = точно име на инструмента. Използваемо извикване = правилен инструмент след проверените поправки на обхвата и аргументите, приет от реалния валидатор, и правилни стойности при анотираните задачи. Аргументите се оценяват върху всички анотирани задачи, включително грешно избраните инструменти.",
                  "Selection = exact tool name. Usable call = correct tool after reviewed scope/argument normalization, accepted by the real validator, plus correct values on annotated cases. Arguments are scored over every annotated case, including wrong-tool selections.",
                )}{" "}
                {t(
                  "Анотирани задачи на език:",
                  "Annotated cases per language:",
                )}{" "}
                {run.metrics.en.argN}.
                {baseline?.replaySource && (
                  <span>
                    {" "}
                    {t(
                      "Отговорите от предишната инструкция са преоценени със същия текущ валидатор, без нови API извиквания.",
                      "Responses from the earlier prompt are re-scored with the same current validator, without new API calls.",
                    )}
                  </span>
                )}
              </p>
            </section>
            {index && index.runs.length > 0 && (
              <section>
                <h2 className="font-title text-xl text-popover-foreground">
                  {t("Всички публикувани измервания", "All published runs")}
                </h2>
                <p className="mt-2 max-w-3xl text-sm text-muted-foreground">
                  {t(
                    "Всяко измерване е отделен артефакт, а не презапис: старите резултати остават, за да се вижда дали има влошаване. „Бюджет“ е ограничението на байтовете, при което е текло стесняването на каталога; „принудително“ означава по-ниско от производственото, за да се измери стесненият път при всяка задача.",
                    "Each measurement is its own artifact rather than an overwrite, so the older results stay and a degradation remains visible. “Budget” is the byte limit the catalogue narrowing ran under; “forced” means below the production one, so the narrowed path is exercised on every case.",
                  )}
                </p>
                <div className="mt-3 overflow-x-auto">
                  <table className="w-full text-left text-sm">
                    <thead>
                      <tr className="border-b-2">
                        <th className="p-2">{t("Измерване", "Run")}</th>
                        <th className="p-2">{t("Дата", "Date")}</th>
                        <th className="p-2">
                          {t("Задачи на език", "Cases per language")}
                        </th>
                        <th className="p-2">{t("Бюджет", "Budget")}</th>
                        <th className="p-2">
                          {t("Избор EN / BG", "Selection EN / BG")}
                        </th>
                        <th className="p-2">
                          {t(
                            "Използваемо извикване EN / BG",
                            "Usable call EN / BG",
                          )}
                        </th>
                        <th className="p-2">
                          {t("Аргументи EN / BG", "Arguments EN / BG")}
                        </th>
                        <th className="p-2">
                          {t(
                            "Правилният инструмент сред кандидатите",
                            "Gold tool in candidates",
                          )}
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      {index.runs.map((r) => (
                        <tr key={r.file} className="border-b align-top">
                          <th className="p-2 font-medium">
                            {runLabel(r.label)}
                            {r.forcedBudget && (
                              <span className="ml-1 rounded bg-muted px-1 text-xs">
                                {t("принудително", "forced")}
                              </span>
                            )}
                          </th>
                          <td className="p-2 tabular-nums">
                            {r.finishedAt ? date(r.finishedAt) : "—"}
                          </td>
                          <td className="p-2 tabular-nums">
                            {r.caseCount}
                            {r.caseGroups && r.caseGroups.length < 7 && (
                              <span className="block text-xs text-muted-foreground">
                                {r.caseGroups.map(groupLabel).join(", ")}
                              </span>
                            )}
                          </td>
                          <td className="p-2 tabular-nums">
                            {r.routingBudget == null
                              ? "—"
                              : `${Math.round(r.routingBudget / 1000)}k`}
                            {r.meanCandidatesKept != null && (
                              <span className="block text-xs text-muted-foreground">
                                {t("средно", "mean")} {r.meanCandidatesKept}
                              </span>
                            )}
                          </td>
                          <td className="p-2 tabular-nums">
                            {pct(r.metrics.en.toolAcc)} /{" "}
                            {pct(r.metrics.bg.toolAcc)}
                          </td>
                          <td className="p-2 tabular-nums">
                            {pct(r.metrics.en.callAcc)} /{" "}
                            {pct(r.metrics.bg.callAcc)}
                          </td>
                          <td className="p-2 tabular-nums">
                            {pct(r.metrics.en.argAcc)} /{" "}
                            {pct(r.metrics.bg.argAcc)}
                            <span className="block text-xs text-muted-foreground">
                              {r.metrics.en.argN}/{r.metrics.bg.argN}
                            </span>
                          </td>
                          <td className="p-2 tabular-nums">
                            {r.goldInCandidates
                              ? `${pct(
                                  r.goldInCandidates.kept /
                                    r.goldInCandidates.total,
                                )}`
                              : "—"}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                <p className="mt-2 max-w-3xl text-sm text-muted-foreground">
                  {t(
                    "„Правилният инструмент сред кандидатите“ е таванът на стесняването: ако очакваният инструмент не е сред кандидатите, моделът не може да го избере. Отделно се отчитат аргументите само по анотираните задачи.",
                    "“Gold tool in candidates” is the ceiling narrowing imposes: if the expected tool is not among the candidates, no model can choose it. Arguments are counted only over the annotated cases.",
                  )}
                </p>
              </section>
            )}
            <LaneComparison index={index} t={t} />
            <GateSweepSection sweep={index?.gateSweep} t={t} />
            {index?.deterministic?.metrics && (
              <section>
                <h2 className="font-title text-xl text-popover-foreground">
                  {t(
                    "Детерминистичен маршрутизатор (без AI)",
                    "Deterministic router (no AI)",
                  )}
                </h2>
                <p className="mt-2 max-w-3xl text-sm text-muted-foreground">
                  {t(
                    `Режимът „Без AI“ не извиква модел, така че се измерва безплатно върху същите задачи (${index.deterministic.caseCount} на език). Показани са и резултатите върху корпуса без началните въпроси, защото публикуваните прагове са регистрирани върху него.`,
                    `The “No AI” mode calls no model, so it is measured for free on the same cases (${index.deterministic.caseCount} per language). The corpus without the starter prompts is shown too, because the published floors were registered on it.`,
                  )}
                </p>
                <div className="mt-3 overflow-x-auto">
                  <table className="w-full text-left text-sm">
                    <thead>
                      <tr className="border-b-2">
                        <th className="p-2">{t("Корпус", "Corpus")}</th>
                        <th className="p-2">
                          {t("Задачи на език", "Cases per language")}
                        </th>
                        <th className="p-2">
                          {t("Избор EN / BG", "Selection EN / BG")}
                        </th>
                        <th className="p-2">
                          {t(
                            "Използваемо извикване EN / BG",
                            "Usable call EN / BG",
                          )}
                        </th>
                        <th className="p-2">
                          {t("Аргументи EN / BG", "Arguments EN / BG")}
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      {(
                        [
                          [
                            t(
                              "Всички задачи (с началните въпроси)",
                              "All cases (with the starter prompts)",
                            ),
                            index.deterministic.metrics,
                          ],
                          [
                            t(
                              "Без началните въпроси",
                              "Without the starter prompts",
                            ),
                            index.deterministic.legacyMetrics,
                          ],
                        ] as const
                      )
                        .filter(([, m]) => m)
                        .map(([label, m]) => (
                          <tr key={label} className="border-b">
                            <th className="p-2 font-medium">{label}</th>
                            <td className="p-2 tabular-nums">
                              {m!.en.n} / {m!.bg.n}
                            </td>
                            <td className="p-2 tabular-nums">
                              {pct(m!.en.toolAcc)} / {pct(m!.bg.toolAcc)}
                            </td>
                            <td className="p-2 tabular-nums">
                              {pct(m!.en.callAcc)} / {pct(m!.bg.callAcc)}
                            </td>
                            <td className="p-2 tabular-nums">
                              {pct(m!.en.argAcc)} / {pct(m!.bg.argAcc)}
                            </td>
                          </tr>
                        ))}
                    </tbody>
                  </table>
                </div>
              </section>
            )}
            <section>
              <h2 className="font-title text-xl text-popover-foreground">
                {t("Покритие и ограничения", "Coverage and limits")}
              </h2>
              <div className="mt-3 overflow-x-auto">
                <table className="w-full text-left text-sm">
                  <thead>
                    <tr className="border-b-2">
                      <th className="p-2">{t("Група", "Group")}</th>
                      <th className="p-2">
                        {t("Задачи на език", "Cases per language")}
                      </th>
                      <th className="p-2">
                        {t("Използваемо извикване EN", "Usable call EN")}
                      </th>
                      <th className="p-2">
                        {t("Използваемо извикване BG", "Usable call BG")}
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {Object.entries(run.groups).map(([g, m]) => (
                      <tr key={g} className="border-b">
                        <th className="p-2 font-medium">{groupLabel(g)}</th>
                        <td className="p-2">{m.en.n}</td>
                        <td className="p-2">{pct(m.en.callAcc)}</td>
                        <td className="p-2">{pct(m.bg.callAcc)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <p className="mt-3 max-w-3xl text-sm text-muted-foreground">
                {t(
                  "Всички примери от регистъра са включени. Те са близки до описанията и не са независима оценка на реалния трафик. Авторските задачи проверяват аргументи, сходни инструменти, последващи въпроси и неподдържани действия. Малкият контролен набор не е използван за редактиране на описанията.",
                  "All registry examples are included. They are close to the descriptions and are not an independent estimate of real traffic. Authored cases test arguments, overlapping tools, follow-ups and unsupported actions. The small held-out set was not used to edit descriptions.",
                )}
              </p>
              <p className="mt-2 max-w-3xl text-sm text-muted-foreground">
                {t(
                  "Това е изолиран тест на маршрутизацията от модела: не изпълнява инструментите и не оценява крайния отговор или резервния маршрутизатор. При примери без анотации валидаторът проверява формата, но не доказва смисловата точност на аргументите. Едно измерване на вариант; разликите могат да включват вариация на модела.",
                  "This isolates model routing: it does not execute tools or evaluate final answers or the fallback router. On unannotated examples, validation checks argument shape, not semantic correctness. One run per variant; differences can include model variation.",
                )}
              </p>
            </section>
            <section>
              <h2 className="font-title text-xl text-popover-foreground">
                {t("Резултати по задачи", "Case results")}
              </h2>
              <label className="my-3 flex items-center gap-2 text-sm">
                <input
                  type="checkbox"
                  checked={failuresOnly}
                  onChange={(e) => setFailuresOnly(e.target.checked)}
                />
                {t("Само неуспешните", "Failures only")}
              </label>
              <div className="max-h-[36rem] overflow-auto rounded border">
                <table className="w-full text-left text-sm">
                  <thead>
                    <tr className="border-b bg-muted">
                      <th className="p-2">{t("Въпрос", "Question")}</th>
                      <th className="p-2">
                        {t("Очакван → избран", "Expected → selected")}
                      </th>
                      <th className="p-2">{t("Резултат", "Result")}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {run.rows
                      .filter(
                        (r) => r.lang === lang && (!failuresOnly || !r.callOk),
                      )
                      .map((r) => (
                        <tr key={r.id} className="border-b align-top">
                          <td className="max-w-lg whitespace-pre-line p-2">
                            {run.cases.find((c) => c.id === r.id)?.[lang]}
                            {run.cases.find((c) => c.id === r.id)?.history && (
                              <details className="mt-1 text-xs text-muted-foreground">
                                <summary className="cursor-pointer">
                                  {t("Предишен контекст", "Previous context")}
                                </summary>
                                <pre className="whitespace-pre-wrap break-words">
                                  {JSON.stringify(
                                    run.cases.find((c) => c.id === r.id)
                                      ?.history?.[lang],
                                    null,
                                    2,
                                  )}
                                </pre>
                              </details>
                            )}
                            {run.cases.find((c) => c.id === r.id)?.review && (
                              <div className="mt-1 text-xs text-muted-foreground">
                                {t(
                                  "Прегледан етикет / уточнен въпрос (v2)",
                                  "Reviewed label / clarified question (v2)",
                                )}
                              </div>
                            )}
                            <div className="mt-1 text-xs text-muted-foreground">
                              {groupLabel(r.group)} · {r.id}
                            </div>
                          </td>
                          <td className="p-2 font-mono text-xs">
                            {r.expectedTool ?? "∅"} → {r.selected ?? "∅"}
                            {r.parsed && r.parsed.tool !== r.selected && (
                              <div>
                                {t("След проверка", "After validation")}:{" "}
                                {r.parsed.tool}
                              </div>
                            )}
                          </td>
                          <td className="p-2">
                            <span>
                              {r.callOk
                                ? "✓"
                                : r.error
                                  ? t("API грешка", "API error")
                                  : !r.toolOk
                                    ? t(
                                        "Различен инструмент / без извикване",
                                        "Different tool / no call",
                                      )
                                    : t(
                                        "Аргументи / валидация",
                                        "Arguments / validation",
                                      )}
                            </span>
                            <details className="mt-1 text-xs">
                              <summary className="cursor-pointer">
                                {t("Отговор на модела", "Model response")}
                              </summary>
                              <pre className="max-w-md whitespace-pre-wrap break-words py-2">
                                {r.raw || r.error}
                              </pre>
                            </details>
                          </td>
                        </tr>
                      ))}
                  </tbody>
                </table>
              </div>
            </section>
            <section className="max-w-3xl text-sm">
              <h2 className="font-title text-xl text-popover-foreground">
                {t(
                  "Обхват и оставащи ограничения",
                  "Coverage and remaining limitations",
                )}
              </h2>
              <ul className="mt-3 list-disc space-y-2 pl-5 text-muted-foreground">
                <li>
                  {t(
                    "Версия 2 уточнява шест двусмислени въпроса и изисква уточнение при единадесет примера без посочено лице или фирма. Старите измервания са запазени отделно.",
                    "Version 2 narrows six ambiguous questions and expects clarification for eleven examples without a named person or company. Earlier measurements are preserved separately.",
                  )}
                </li>
                <li>
                  {t(
                    "Добавени са 40 двойки ръчно написани ежедневни въпроси, включително осем разговорни продължения. Това са симулирани въпроси, не реални потребителски разговори. Те не са независим тестов набор, след като се използват за диагностика.",
                    "Added 40 hand-written pairs of everyday questions, including eight conversation follow-ups. These simulate users; they are not collected user conversations or an independent holdout once used for diagnosis.",
                  )}
                </li>
                <li>
                  {t(
                    "Класациите приемат ограничен набор показатели; неподдържаният показател не се заменя с безработица. Има проверки за типовете на изборния цикъл и за календарна година срещу подвижен период.",
                    "Rankings use a closed set of metrics; unsupported metrics no longer become unemployment. Validation checks election-cycle types and calendar-year versus rolling-window scope.",
                  )}
                </li>
                <li>
                  {t(
                    "API оценките измерват избора и аргументите. Отделни автоматизирани тестове с фиксирани данни проверяват изпълнение, липсващи данни, източници и защита на числата. Те не доказват коректността на всички живи крайни точки или на всеки генериран отговор.",
                    "API scores measure routing and arguments. Separate automated tests with fixed data check execution, missing data, sources and number grounding. They do not establish correctness of every live endpoint or generated answer.",
                  )}
                </li>
              </ul>
            </section>
            <details className="rounded border p-3 text-sm">
              <summary className="cursor-pointer font-medium">
                {t("Възпроизводимост", "Reproducibility")}
              </summary>
              <div className="mt-3 space-y-2 break-all text-xs text-muted-foreground">
                <p>{run.provider}</p>
                <p>
                  {run.model} · temperature {run.settings.temperature} ·
                  max_tokens {run.settings.max_tokens} · reasoning{" "}
                  {run.settings.reasoning_effort}
                </p>
                <p>
                  {t("Хеш на задачите", "Suite hash")}: {run.suiteHash}
                </p>
                <p>
                  {t("Хеш на подканите", "Prompt hash")}: {run.promptHash}
                </p>
                <p>
                  {t("Хеш на регистъра", "Registry hash")}: {run.registryHash}
                </p>
                <p>
                  {t("Грешки на API EN / BG", "API errors EN / BG")}:{" "}
                  {run.metrics.en.errors} / {run.metrics.bg.errors}
                </p>
                <p>
                  {t(
                    "Повторени временни API грешки",
                    "Retried transient API errors",
                  )}
                  : {run.retriedErrors ?? 0}.{" "}
                  {t(
                    "Първите отговори и грешки са запазени в архива.",
                    "Original responses and errors are retained in the run archive.",
                  )}
                </p>
                <p>ai/llm/currentEval.run.ts · data/ai/evals/runs/</p>
              </div>
            </details>
          </>
        )}
        <details className="rounded border p-4">
          <summary className="cursor-pointer font-medium">
            {t(
              "Архив: предишни модели и ретривъри",
              "Archive: previous models and retrievers",
            )}
          </summary>
          <p className="my-3 max-w-3xl text-sm text-muted-foreground">
            {t(
              "Тези експерименти са с по-стар регистър и различни подкани. Не са пряко сравними с текущия тест. Моделите в браузъра и ретривърите не са текущият облачен маршрутизатор.",
              "These experiments used an older registry and different prompts. They are not directly comparable with the current test. Browser models and retrievers are not the current cloud router.",
            )}
          </p>
          {legacy && (
            <>
              <p className="text-sm">
                {date(legacy.generatedAt)} · {legacy.method.toolCount}{" "}
                {t("инструмента", "tools")} · {legacy.method.caseCount}{" "}
                {t("задачи", "cases")}
              </p>
              <div className="overflow-x-auto">
                <table className="mt-3 w-full text-left text-sm">
                  <thead>
                    <tr className="border-b">
                      <th className="p-2">{t("Модел", "Model")}</th>
                      <th className="p-2">
                        {t("Исторически режим", "Historical mode")}
                      </th>
                      <th className="p-2">EN</th>
                      <th className="p-2">BG</th>
                    </tr>
                  </thead>
                  <tbody>
                    {legacy.models.map((m) => (
                      <tr key={m.id} className="border-b">
                        <th className="p-2 font-medium">{m.label}</th>
                        <td className="p-2">{m.toolMode}</td>
                        <td className="p-2">{pct(m.perLang?.en.toolAcc)}</td>
                        <td className="p-2">{pct(m.perLang?.bg.toolAcc)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </>
          )}
          {recall && (
            <details className="mt-4">
              <summary className="cursor-pointer">
                {t("Исторически recall@8", "Historical recall@8")} ·{" "}
                {date(recall.generatedAt)}
              </summary>
              <ul className="mt-2 space-y-1 text-sm">
                {recall.rows.map((r) => (
                  <li key={r.id}>
                    {r.label[lang].replace(/ — current| — текущ/g, "")} —{" "}
                    {pct(r.declined["8"])}
                  </li>
                ))}
              </ul>
              <p className="mt-2 text-xs text-muted-foreground">
                {t(
                  "Въпроси, останали след правилата; синтетичен набор. Резултатите от дообучението споделят генератор с теста и могат да са оптимистични.",
                  "Queries left after rules; synthetic dataset. Fine-tuning and test data share a generator and may give optimistic results.",
                )}
              </p>
            </details>
          )}
        </details>
      </Content>
      {!integrated && (
        <footer className="border-t bg-muted p-4 text-center text-xs">
          <a href={chatPath("chat", navigation.pathname)}>
            {t("Към чата", "Back to chat")}
          </a>{" "}
          · <a href={SITE_ORIGIN}>{SITE_HOST}</a>
        </footer>
      )}
    </div>
  );
};
