import { useChatNavigation } from "./navigation";
import { SITE_ORIGIN, SITE_HOST } from "@/lib/siteOrigin";
import { chatPath } from "./navigationPaths";
import { ToolGradSection } from "./ToolGradSection";
// Current production-router measurements; historical experiments stay explicitly separate.
import { useContext, useEffect, useState, type ReactNode } from "react";
import { Logo } from "@/layout/header/Logo";
import { Button } from "@/components/ui/button";
import { ThemeContext } from "@/theme/ThemeContext";
import { themeDark, themeLight } from "@/theme/utils";
import { fetchData } from "../tools/dataClient";
import type { Lang } from "../tools/types";
import type { EvalCase, EvalScore } from "../llm/currentEval";
import type {
  CompactMetrics,
  DeterministicMetrics,
  GateSweep,
  JevRouting,
  Robustness,
  RobustnessCell,
} from "../llm/evalsIndex";
type Metrics = {
  n: number;
  toolAcc: number | null;
  callAcc: number | null;
  argN: number;
  argAcc: number | null;
  jsonValidRate: number | null;
  irrelevanceAcc: number | null;
  errors: number;
};
type Run = {
  label: string;
  model: string;
  provider: string;
  startedAt: string;
  finishedAt: string;
  toolCount: number;
  caseCount: number;
  retriedErrors?: number;
  promptHash: string;
  suiteHash: string;
  registryHash: string;
  scoringHash?: string;
  replaySource?: string;
  settings: {
    max_tokens: number;
    temperature: number;
    reasoning_effort: string;
  };
  metrics: Record<Lang, Metrics>;
  groups: Record<string, Record<Lang, Metrics>>;
  cases: EvalCase[];
  rows: EvalScore[];
};
type Legacy = {
  generatedAt: string;
  method: { toolCount: number; caseCount: number };
  models: {
    id: string;
    label: string;
    toolMode?: string;
    perLang: Record<Lang, { toolAcc: number }> | null;
  }[];
};
// The published-run manifest (`data/ai/evals/index.json`), generated by
// ai/llm/evalsIndex.ts from every `current_*.json` on disk. The page reads THIS rather
// than hardcoding filenames, so a new run appears without editing the page and a
// renamed artifact cannot leave a dead link behind.
export type RunSummary = {
  file: string;
  label: string;
  artifactLabel?: string | null;
  model: string | null;
  finishedAt: string | null;
  caseCount: number;
  caseGroups: string[] | null;
  routingBudget: number | null;
  forcedBudget: boolean;
  metrics: Record<Lang, SummarisedMetrics>;
  /** The run's figures on the 474-question bank without the starter prompts —
   *  present only on runs that also covered the starters (the Jev lane). */
  legacyMetrics?: Record<Lang, SummarisedMetrics>;
  groups: Record<string, Record<Lang, SummarisedMetrics>>;
  goldInCandidates: { kept: number; total: number } | null;
  meanCandidatesKept: number | null;
  /** Mean routing-prompt tokens per question; absent on older manifests. */
  meanPromptTokens?: number | null;
  jevRouting?: JevRouting;
};
// DERIVED from the producer, never restated here. The page used to hand-mirror
// `compact()`'s output, so a renamed key left this file rendering `undefined`
// → "—" with nothing failing — the silent degradation this page is otherwise
// careful about. The import is type-only: `evalsIndex.ts` reads the filesystem
// at call time, and a value import would pull `node:fs` into the bundle.
export type SummarisedMetrics = CompactMetrics;
export type DeterministicEval = {
  generatedAt: string;
  caseCount: number;
  caseGroups: string[] | null;
  metrics: Record<Lang, DeterministicMetrics> | null;
  legacyMetrics: Record<Lang, DeterministicMetrics> | null;
};
export type EvalsIndex = {
  generatedAt: string;
  runs: RunSummary[];
  deterministic: DeterministicEval | null;
  /** Absent on a manifest built before the sweep existed. */
  gateSweep?: GateSweep | null;
  robustness?: Robustness | null;
};
type Recall = {
  generatedAt: string;
  rows: {
    id: string;
    label: Record<Lang, string>;
    declined: Record<string, number>;
  }[];
};
type T = (bg: string, en: string) => string;
type LangMetrics = Record<Lang, Partial<SummarisedMetrics>>;
type MetricKey = Exclude<keyof SummarisedMetrics, "n" | "argN">;

/** Numbers in the reader's language — Bulgarian writes a decimal COMMA, and a
 *  page mixing "90.6%" in its tables with "99,3%" in its prose reads as two
 *  sources. `pair` is "EN / BG" for one metric: every table puts both
 *  languages in one cell, so the split is stated once per table instead of in
 *  every header. */
const makeFmt = (lang: Lang) => {
  const dec = (v: number, digits: number) => {
    const s = v.toFixed(digits);
    return lang === "bg" ? s.replace(".", ",") : s;
  };
  const pct = (v: number | null | undefined) =>
    v == null ? "—" : `${dec(v * 100, 1)}%`;
  const pair = (m: LangMetrics | null | undefined, k: MetricKey) =>
    m ? `${pct(m.en[k])} / ${pct(m.bg[k])}` : "—";
  return { dec, pct, pair };
};

// ⚠️ TABLE CELLS NEVER WRAP. A figure broken across two lines ("90.6% /" then
// "91.4%") reads as two numbers, and a header broken the same way doubles the
// height of every table for nothing. A table wider than its column scrolls.
const Th = ({ children }: { children: ReactNode }) => (
  <th scope="col" className="whitespace-nowrap p-2 text-left font-medium">
    {children}
  </th>
);
const RowTh = ({
  children,
  note,
}: {
  children: ReactNode;
  note?: ReactNode;
}) => (
  <th scope="row" className="whitespace-nowrap p-2 text-left font-medium">
    {children}
    {note && (
      <span className="ml-2 text-xs font-normal text-muted-foreground">
        {note}
      </span>
    )}
  </th>
);
const Num = ({ children }: { children: ReactNode }) => (
  <td className="whitespace-nowrap p-2 tabular-nums">{children}</td>
);
const DataTable = ({
  children,
  note,
}: {
  children: ReactNode;
  note?: ReactNode;
}) => (
  <div className="mt-3">
    {note && <p className="mb-1 text-xs text-muted-foreground">{note}</p>}
    <div className="overflow-x-auto">
      <table className="w-full text-sm">{children}</table>
    </div>
  </div>
);
const H2 = ({ children }: { children: ReactNode }) => (
  <h2 className="font-title text-2xl text-popover-foreground">{children}</h2>
);
const H3 = ({ children }: { children: ReactNode }) => (
  <h3 className="font-title text-xl text-popover-foreground">{children}</h3>
);
const Lede = ({ children }: { children: ReactNode }) => (
  <p className="mt-2 max-w-3xl text-sm text-muted-foreground">{children}</p>
);
const langNote = (t: T) =>
  t(
    "Във всяка клетка: английски / български.",
    "Each cell: English / Bulgarian.",
  );

/** The two model lanes' artifacts, by FILENAME — the manifest's own identity
 *  rule (a label inside an artifact can be copied by a re-scored replay).
 *
 *  ⚠️ `CLOUD_RUN_FILE` is NAMED rather than found, and that is the whole point.
 *  It used to be "the first non-Jev run with metrics", and `runs` is sorted by
 *  `finishedAt` DESCENDING — so it resolved to whichever experiment was
 *  published last, which on the committed manifest is the 367-question
 *  starter-prompts-only bank. The page then stated that the cloud model scored
 *  57.8% usable call, below the rules' 85.9%, when its production run is 85.9%;
 *  and that Jev beat it on selection 90.6% to 82.6%, when on the production run
 *  the cloud model WINS that column 96.0% to 90.6%. The published ranking was
 *  inverted, and publishing any new artifact would have re-pointed the lane
 *  again with no test failing. */
const JEV_RUN_FILE = "current_jev.json";
const CLOUD_RUN_FILE = "current_production.json";
/** Gemini alone, run the same day and on the same suite as `JEV_GEMINI_FILE` —
 *  the fair comparator for it, so the headline prefers it when present. */
const CONTROL_RUN_FILE = "current_control.json";
/** Jev picks the tool, Gemini fills its parameters. */
const JEV_GEMINI_FILE = "current_jev_gemini.json";

/** A readable model name from an artifact's model id
 *  (`google/gemini-3.5-flash-lite` → `Gemini 3.5 Flash-Lite`). An id this does
 *  not recognise is shown as it is rather than guessed at. */
const modelName = (id: string | null, fallback: string) => {
  const m = id?.match(/^(?:[\w-]+\/)?gemini-([\d.]+)-flash(-lite)?$/i);
  return m ? `Gemini ${m[1]} Flash${m[2] ? "-Lite" : ""}` : (id ?? fallback);
};

type Lane = {
  id: string;
  name: string;
  note: string;
  cases: number;
  groups: string[] | null;
  m: LangMetrics;
  /** Can this lane abstain at all? Distinct from "did we measure how often",
   *  which is what a null field means. */
  declines: boolean;
};

/** Equal counts over different GROUPS are still not comparable, and that is
 *  the one mismatch a reader cannot see for themselves: the count column
 *  agrees. So the check is on the bank, not on its size. */
const sameBank = (lanes: Lane[]) =>
  new Set(
    lanes.map(
      (l) => `${l.cases}:${[...(l.groups ?? [])].sort().join("+") || "?"}`,
    ),
  ).size <= 1;
const MismatchWarning = ({ lanes, t }: { lanes: Lane[]; t: T }) => {
  const counts = [...new Set(lanes.map((l) => l.cases))];
  if (sameBank(lanes)) return null;
  return (
    <p className="mt-2 max-w-3xl text-sm text-destructive">
      {counts.length > 1
        ? t(
            `Внимание: редовете са измерени върху различен брой въпроси (${counts.join(", ")}) и не са пряко съпоставими.`,
            `Caution: the rows were measured on different numbers of questions (${counts.join(", ")}) and are not directly comparable.`,
          )
        : t(
            "Внимание: броят въпроси е еднакъв, но наборите са различни, затова редовете не са пряко съпоставими.",
            "Caution: the number of questions matches but the sets differ, so the rows are not directly comparable.",
          )}
    </p>
  );
};

/**
 * THE HEADLINE: all three ways of choosing a tool, on the SAME questions.
 *
 * ⚠️ The shared bank is the 474 questions WITHOUT the starter prompts. The
 * cloud model's run on the 367 starters is a SEPARATE artifact
 * (`current_starter.json`), while the rules and Jev were scored on all 841 in
 * one run each — and the starters are easy for both of them. So the
 * 841-question figures the page used to lead with flattered the two cheap
 * lanes against the cloud one: Jev read 90.6% there and reads 84.2% here.
 */
const Summary = ({
  index,
  t,
  lang,
}: {
  index: EvalsIndex | null;
  t: T;
  lang: Lang;
}) => {
  const { pair } = makeFmt(lang);
  const byFile = (f: string) => index?.runs.find((r) => r.file === f);
  const jev = byFile(JEV_RUN_FILE);
  // The same-day control first: it shares its day and its exact question set
  // with the Jev + Gemini run, so the two rows below each other differ in one
  // thing only. The older production run is the fallback.
  const cloud = byFile(CONTROL_RUN_FILE) ?? byFile(CLOUD_RUN_FILE);
  const jevGemini = byFile(JEV_GEMINI_FILE);
  const rules = index?.deterministic?.legacyMetrics;
  // All THREE or nothing — a two-row table under a three-lane claim is the
  // failure this section exists to avoid.
  if (!jev?.legacyMetrics || !cloud || !rules) return null;
  const nonStarter = (g: string[] | null) =>
    g ? g.filter((x) => x !== "starter") : null;
  const lanes: Lane[] = [
    {
      id: "deterministic",
      name: t("Правила (без AI)", "Rules (no AI)"),
      note: t("без модел, безплатно", "no model, free"),
      cases: rules.en.n,
      groups: nonStarter(index!.deterministic!.caseGroups),
      m: rules,
      declines: false,
    },
    {
      id: "cloud",
      name: modelName(cloud.model, cloud.label),
      note: t("облачен модел", "cloud model"),
      cases: cloud.caseCount,
      groups: cloud.caseGroups,
      m: cloud.metrics,
      declines: false,
    },
    {
      id: "jev",
      name: "Jev (TypeSafe)",
      note: t(
        "без AI, избира между подадени варианти",
        "no AI, picks among given options",
      ),
      cases: jev.legacyMetrics.en.n,
      groups: nonStarter(jev.caseGroups),
      m: jev.legacyMetrics,
      declines: true,
    },
    // Optional: shown when the run exists. The three above are required.
    ...(jevGemini
      ? [
          {
            id: "jev_gemini",
            name: `Jev + ${modelName(jevGemini.model, jevGemini.label)}`,
            note: t(
              "Jev избира инструмента, Gemini — параметрите",
              "Jev picks the tool, Gemini the parameters",
            ),
            cases: jevGemini.caseCount,
            groups: jevGemini.caseGroups,
            m: jevGemini.metrics,
            declines: false,
          },
        ]
      : []),
  ];
  const mean = (l: Lane) => ((l.m.en.toolAcc ?? 0) + (l.m.bg.toolAcc ?? 0)) / 2;
  const best = [...lanes].sort((a, b) => mean(b) - mean(a))[0];
  const j = lanes[2].m;
  const argMean = (m: LangMetrics) =>
    ((m.en.argAcc ?? 0) + (m.bg.argAcc ?? 0)) / 2;
  const num = (n: number) =>
    n.toLocaleString(lang === "bg" ? "bg-BG" : "en-GB");
  const howMany =
    lanes.length === 4 ? t("четирите", "four") : t("трите", "three");
  return (
    <section aria-labelledby="summary-title">
      <h2
        id="summary-title"
        className="font-title text-2xl text-popover-foreground"
      >
        {t("Накратко", "In short")}
      </h2>
      <Lede>
        {sameBank(lanes)
          ? t(
              `Сравняваме ${howMany} начина, по които чатът може да избере инструмент (тези с Jev са още в изпитание), върху едни и същи ${lanes[1].cases} въпроса на всеки език.`,
              `We compare the ${howMany} ways the chat can choose a tool (those with Jev are still under test) on the same ${lanes[1].cases} questions in each language.`,
            )
          : t(
              `Сравняваме ${howMany} начина, по които чатът може да избере инструмент (тези с Jev са още в изпитание).`,
              `We compare the ${howMany} ways the chat can choose a tool (those with Jev are still under test).`,
            )}
      </Lede>
      <MismatchWarning lanes={lanes} t={t} />
      <DataTable note={langNote(t)}>
        <thead>
          <tr className="border-b-2">
            <Th>{t("Начин на избор", "Method")}</Th>
            <Th>{t("Въпроси", "Questions")}</Th>
            <Th>{t("Правилен инструмент", "Right tool")}</Th>
            <Th>{t("Изпълнимо извикване", "Usable call")}</Th>
            <Th>{t("Верни параметри", "Right parameters")}</Th>
          </tr>
        </thead>
        <tbody>
          {lanes.map((l) => (
            <tr key={l.id} data-lane={l.id} className="border-b">
              <RowTh note={l.note}>{l.name}</RowTh>
              <Num>{l.cases}</Num>
              <Num>{pair(l.m, "toolAcc")}</Num>
              <Num>{pair(l.m, "callAcc")}</Num>
              <Num>{pair(l.m, "argAcc")}</Num>
            </tr>
          ))}
        </tbody>
      </DataTable>
      {/* Computed, never written: these sentences must stay true when the
          artifacts are re-run. */}
      <ul className="mt-4 max-w-3xl list-disc space-y-2 pl-5 text-sm">
        <li>
          {t(
            `${best.name} най-често избира правилния инструмент: ${pair(best.m, "toolAcc")}.`,
            `${best.name} picks the right tool most often: ${pair(best.m, "toolAcc")}.`,
          )}
        </li>
        <li>
          {t(
            `Правилата без AI са безплатни и винаги работят, но избират правилния инструмент в ${pair(rules, "toolAcc")} от случаите, а параметрите са верни в ${pair(rules, "argAcc")}.`,
            `The rules are free and always work, but pick the right tool in ${pair(rules, "toolAcc")} of cases, with the right parameters in ${pair(rules, "argAcc")}.`,
          )}
        </li>
        <li>
          {t(
            `Без AI Jev поема ${pair(j, "jevRouted")} от въпросите и при тях избира правилно в ${pair(j, "toolAccWhenRouted")}; останалите оставя на правилата. Параметрите попълват главно правилата, затова там Jev е близо до тях: ${pair(j, "argAcc")} срещу ${pair(rules, "argAcc")}.`,
            `Without AI, Jev takes ${pair(j, "jevRouted")} of the questions and is right on ${pair(j, "toolAccWhenRouted")} of those; it leaves the rest to the rules. The rules still fill in most parameters, so there Jev stays close to them: ${pair(j, "argAcc")} against ${pair(rules, "argAcc")}.`,
          )}
        </li>
        {jevGemini && (
          <li>
            {t(
              `Когато Jev избере инструмента, а Gemini само попълни параметрите, те са верни в ${pair(jevGemini.metrics, "argAcc")} срещу ${pair(cloud.metrics, "argAcc")} при само Gemini.`,
              `When Jev picks the tool and Gemini only fills its parameters, they are right in ${pair(jevGemini.metrics, "argAcc")} against ${pair(cloud.metrics, "argAcc")} with Gemini alone.`,
            )}
            {/* The explanation only when the data bears it out — a sentence
                written here would survive a run that reversed the numbers. */}
            {argMean(jevGemini.metrics) > argMean(cloud.metrics) &&
              t(
                " Моделът попълва по-точно, щом вижда един инструмент вместо целия каталог.",
                " The model fills more accurately when it sees one tool instead of the whole catalogue.",
              )}
            {jevGemini.meanPromptTokens != null &&
              cloud.meanPromptTokens != null &&
              t(
                ` Подканата за избора е средно ${num(jevGemini.meanPromptTokens)} токена вместо ${num(cloud.meanPromptTokens)}.`,
                ` The routing prompt averages ${num(jevGemini.meanPromptTokens)} tokens instead of ${num(cloud.meanPromptTokens)}.`,
              )}
          </li>
        )}
      </ul>
      <dl className="mt-4 grid max-w-3xl gap-x-4 gap-y-1 text-sm text-muted-foreground sm:grid-cols-[max-content_1fr]">
        <dt className="font-medium text-foreground">
          {t("Правилен инструмент", "Right tool")}
        </dt>
        <dd>
          {t(
            "избран е точно инструментът, който отговаря на въпроса.",
            "exactly the tool that answers the question was chosen.",
          )}
        </dd>
        <dt className="font-medium text-foreground">
          {t("Изпълнимо извикване", "Usable call")}
        </dt>
        <dd>
          {t(
            "правилен инструмент с параметри, които той приема; при въпросите с проверени отговори параметрите трябва и да са верни.",
            "the right tool, with parameters it accepts; on questions with checked answers the parameters must also be right.",
          )}
        </dd>
        <dt className="font-medium text-foreground">
          {t("Верни параметри", "Right parameters")}
        </dt>
        <dd>
          {t(
            `точните стойности (партия, година, община…) при ${cloud.metrics.en.argN}-те въпроса на всеки език, за които знаем верния отговор.`,
            `the exact values (party, year, municipality…) on the ${cloud.metrics.en.argN} questions per language whose answer we know.`,
          )}
        </dd>
      </dl>
    </section>
  );
};

/**
 * The robustness test: the same questions with typos, reworded, and in Latin
 * script — the questions the main test does not contain.
 *
 * ⚠️ WHY IT IS ON THE PAGE AT ALL. The main test is 91% sentences the rules
 * were BUILT FROM (every tool's examples and every suggested question), so it
 * flatters the rules, and the no-AI Jev lane that falls back to them. Real
 * readers do not type the examples. This is where the methods separate.
 *
 * Only the TOOL is scored — a rewording keeps the tool but not the expected
 * parameter values — so these figures are not comparable to "Изпълнимо
 * извикване" elsewhere on the page. The takeaway is computed.
 */
const RobustnessSection = ({
  robustness,
  t,
  lang,
}: {
  robustness: Robustness | null | undefined;
  t: T;
  lang: Lang;
}) => {
  const { pct } = makeFmt(lang);
  if (!robustness) return null;
  const s = robustness.summary;
  const variants: { key: string; label: string }[] = [
    { key: "original", label: t("Както са написани", "As written") },
    { key: "typo", label: t("С правописни грешки", "With typos") },
    { key: "paraphrase", label: t("Казани с други думи", "Reworded") },
    {
      key: "latin",
      label: t("На латиница (само BG)", "In Latin letters (BG only)"),
    },
  ];
  const cols: { key: keyof RobustnessCell; label: string }[] = [
    { key: "rules", label: t("Правила", "Rules") },
    { key: "jevRaw", label: t("Само Jev", "Jev alone") },
    { key: "jevLane", label: t("Jev без AI", "Jev, no AI") },
    { key: "gemini", label: t("Само Gemini", "Gemini alone") },
    { key: "jevGemini", label: "Jev + Gemini" },
  ];
  const cell = (slice: string, v: string, k: keyof RobustnessCell) => {
    const en = s[`${slice}|en:${v}`]?.[k];
    const bg = s[`${slice}|bg:${v}`]?.[k];
    if (en == null && bg == null) return "—";
    return `${pct(en)} / ${pct(bg)}`;
  };
  // How many (language, kind of question) cells each AI method wins.
  const cells = Object.entries(s).filter(([k]) => k.startsWith("all|"));
  const jgWins = cells.filter(
    ([, c]) => (c.jevGemini ?? 0) >= (c.gemini ?? 0),
  ).length;
  const table = (slice: string, caption: string) => (
    <div className="mt-4">
      <p className="text-sm font-medium">{caption}</p>
      <DataTable note={langNote(t)}>
        <thead>
          <tr className="border-b-2">
            <Th>{t("Въпросите", "Questions")}</Th>
            {cols.map((c) => (
              <Th key={c.key}>{c.label}</Th>
            ))}
          </tr>
        </thead>
        <tbody>
          {variants.map((v) => (
            <tr key={v.key} data-variant={v.key} className="border-b">
              <RowTh>{v.label}</RowTh>
              {cols.map((c) => (
                <Num key={c.key}>{cell(slice, v.key, c.key)}</Num>
              ))}
            </tr>
          ))}
        </tbody>
      </DataTable>
    </div>
  );
  return (
    <section aria-labelledby="robust-title">
      <h2
        id="robust-title"
        className="font-title text-2xl text-popover-foreground"
      >
        {t(
          "Когато въпросът е написан по-различно",
          "When the question is written differently",
        )}
      </h2>
      <Lede>
        {t(
          "Основният тест е съставен най-вече от примерите, по които са написани самите правила, затова ги облагодетелства. Хората обаче пишат с грешки, с други думи или на латиница. Тук същите въпроси са зададени точно така — и оценяваме само избора на инструмент.",
          "The main test is made mostly of the examples the rules themselves were written from, so it favours them. People, though, type with mistakes, in other words, or in Latin letters. Here the same questions are asked that way — and only the choice of tool is scored.",
        )}
      </Lede>
      <p className="mt-2 max-w-3xl text-sm font-medium">
        {t(
          `Jev + Gemini е поне толкова точен, колкото само Gemini, в ${jgWins} от ${cells.length} случая (език и вид въпрос).`,
          `Jev + Gemini is at least as accurate as Gemini alone in ${jgWins} of ${cells.length} cases (language and kind of question).`,
        )}
      </p>
      {table(
        "all",
        t(
          "Всички въпроси (по един пример за инструмент и всички ръчно написани)",
          "All questions (one example per tool and every hand-written one)",
        ),
      )}
      {table(
        "handwritten",
        t(
          "Само ръчно написаните — те не са в речника на правилата",
          "Hand-written only — they are not in the rules' vocabulary",
        ),
      )}
      <p className="mt-2 max-w-3xl text-xs text-muted-foreground">
        {t(
          "„Само Jev“ е собственият избор на Jev, преди прага на увереност. „Jev без AI“ е режимът без модел: когато Jev не е уверен или инструментът иска параметри, които правилата не могат да попълнят, отговорът идва от правилата. Грешките са изкуствени (разместена, изпусната или удвоена буква в две думи), а преформулираните въпроси са написани от модел; няколко леко променят смисъла.",
          "“Jev alone” is Jev's own pick, before the confidence gate. “Jev, no AI” is the mode without a model: when Jev is not confident, or the tool needs parameters the rules cannot fill, the answer comes from the rules. The typos are synthetic (a swapped, dropped or doubled letter in two words), and the reworded questions were written by a model; a few shift the meaning slightly.",
        )}
      </p>
    </section>
  );
};

/**
 * How we got here. Dated, and each step says why it was tried and why it was
 * kept or dropped — the page's answer to "why this architecture".
 *
 * ⚠️ FROZEN HISTORY, deliberately not computed: these are records of what was
 * measured at the time, with the numbers of the time. Live figures belong in
 * the tables, never here. Sources are the commits and docs named in the
 * `ai/`, `docs/ai/` and `ai/toolgrad/` trees.
 */
const History = ({ t }: { t: T }) => {
  const steps: {
    date: string;
    title: string;
    body: string;
    outcome: string;
  }[] = [
    {
      date: t("юни 2026", "June 2026"),
      title: t("Правила без AI", "Rules, no AI"),
      body: t(
        "Чатът не бива да измисля числа, затова първата версия не използваше модел: избираше инструмента по ключови думи, а отговорът се попълваше по шаблон от изчислените данни. Правилата са безплатни и винаги налични, но разбират само формулировките, за които са писани.",
        "The chat must never invent numbers, so the first version used no model: it picked the tool by keywords and filled the answer from a template over computed data. Rules are free and always available, but only understand the phrasings they were written for.",
      ),
      outcome: t(
        "Остават основата: при всяка грешка на модел чатът се връща към тях. От юни са и отделен режим „Без AI“, а от септември това е единият от двата режима в чата.",
        "They remain the base: whenever a model fails, the chat falls back to them. They have been a separate “No AI” mode since June; since September it is one of the chat's two modes.",
      ),
    },
    {
      date: t("юни 2026", "June 2026"),
      title: t("Малки модели в браузъра", "Small models in the browser"),
      body: t(
        "Модел, който работи на устройството на читателя, би бил безплатен и не би пращал въпросите никъде. Пробвахме Qwen 2.5 (не е български модел и бъркаше), EuroLLM-1.7B (браузърът оставаше без памет), BgGPT-2.6B (програмите за преобразуване на модела не работеха) и FunctionGemma-270M: 37% при избор между три инструмента, сред които винаги беше верният — едва над случайния избор (33%).",
        "A model running on the reader's device would be free and send the questions nowhere. We tried Qwen 2.5 (not a Bulgarian model, and it mis-routed), EuroLLM-1.7B (the browser ran out of memory), BgGPT-2.6B (the model-conversion tooling was broken) and FunctionGemma-270M: 37% when choosing among three tools that always included the right one — barely above chance (33%).",
      ),
      outcome: t(
        "Нито един не стигна до използваемо ниво. Qwen и EuroLLM махнахме още през юни, а FunctionGemma и BgGPT извадихме от публичния избор през септември.",
        "None reached a usable level. Qwen and EuroLLM were dropped in June; FunctionGemma and BgGPT left the public picker in September.",
      ),
    },
    {
      date: t("юни 2026", "June 2026"),
      title: t("Облачен модел", "A cloud model"),
      body: t(
        "Силен модел разбира въпроси, зададени по различен начин, и извлича параметрите много по-добре от правилата. Първият тест с Gemini 3.1 Flash-Lite — по един примерен въпрос за всеки от тогавашните 104 инструмента — даде 96% на английски и 97% на български, без загуба за българския.",
        "A strong model understands questions phrased in different ways and extracts parameters far better than rules. The first test of Gemini 3.1 Flash-Lite — one example question for each of the 104 tools of the time — gave 96% in English and 97% in Bulgarian, no penalty for Bulgarian.",
      ),
      outcome: t(
        "Става основният AI режим. Днес това е Gemini 3.5 Flash-Lite, който от септември викаме директно през Gemini API.",
        "It becomes the main AI mode. Today that is Gemini 3.5 Flash-Lite, which since September we call directly through the Gemini API.",
      ),
    },
    {
      date: t("юни 2026", "June 2026"),
      title: t(
        "Предварителен подбор на инструменти",
        "Pre-selecting the tools",
      ),
      body: t(
        "Малкият модел може да избира само сред няколкото инструмента, които му подаде търсачка, така че нейната точност е таван за целия отговор. На въпросите, на които правилата не отговарят, търсенето по думи намираше правилния инструмент сред първите 8 едва в 49% от случаите; търсенето по смисъл — между 72% и 95%.",
        "A small model can only choose among the few tools a search step hands it, so that search caps the whole answer. On the questions the rules cannot answer, keyword search found the right tool in its top 8 only 49% of the time; search by meaning managed 72% to 95%.",
      ),
      outcome: t(
        "Тесни места бяха и подборът, и малкият модел. С облачен модел, който вижда целия каталог, въпросът отпадна — до септември, когато каталогът порасна.",
        "Both the pre-selection and the small model were bottlenecks. With a cloud model seeing the whole catalogue the question went away — until the catalogue grew in September.",
      ),
    },
    {
      date: t("юли 2026", "July 2026"),
      title: t(
        "Проверка на числата в текста",
        "Checking the numbers in the text",
      ),
      body: t(
        "Таблиците идват от изчислени данни, но изречението, което моделът пише над тях, може да съдържа закръглено или измислено число.",
        "The tables come from computed data, but the sentence the model writes above them could contain a rounded or invented number.",
      ),
      outcome: t(
        "Всяко съществено число в текста трябва да се намира в изчислените данни. Ако не се намира, показваме шаблонния отговор.",
        "Every material number in the text must be found in the computed data. If it is not, we show the template answer instead.",
      ),
    },
    {
      date: t("10 септември", "10 September"),
      title: t("Нова версия на теста", "A new version of the test"),
      body: t(
        "471 въпроса, всеки на двата езика, за 228 инструмента; за 53 от тях на всеки език знаем верните параметри. Добавихме 40 нови въпроса: 24 ежедневни, 8 за уточнение и 8 за продължение на разговор. Промените в инструкциите към модела (подканата) и в проверките не подобриха резултата като цяло — на български той спадна с 1,3 пункта.",
        "471 questions, each in both languages, over 228 tools, 53 per language with checked parameters. 40 new questions were added: 24 everyday, 8 needing clarification and 8 conversation follow-ups. The changes to the model's instructions (the prompt) and to the checks did not improve the result overall — Bulgarian fell by 1.3 points.",
      ),
      outcome: t(
        "Не обявяваме подобрение, щом измерването не го показва. Старите резултати остават на страницата за сравнение.",
        "We announce no improvement the measurement does not show. The earlier results stay on the page for comparison.",
      ),
    },
    {
      date: t("11 септември", "11 September"),
      title: "ToolGrad",
      body: t(
        "Взехме идея от метод на Google Research: първо изпълняваме инструментите, после съставяме въпроси, чийто верен отговор вече знаем. От грешките на тренировъчните въпроси написахме едно допълнение към инструкциите на модела.",
        "We borrowed an idea from a Google Research method: run the tools first, then write questions whose right answer is already known. From the failures on the development questions we wrote one addition to the model's instructions.",
      ),
      outcome: t(
        "Допълнението влоши резултата на контролните въпроси (от 33 на 31 от 36) и го отхвърлихме. Запазихме само конкретни поправки — например че „Пловдив“ означава града, а не областта.",
        "The addition made the held-out questions worse (33 down to 31 of 36), so we rejected it. We kept only specific fixes — for example, that “Plovdiv” means the city, not the province.",
      ),
    },
    {
      date: t("16 септември", "16 September"),
      title: t("Стесняване на каталога", "Narrowing the catalogue"),
      body: t(
        "При 235 инструмента описанието им на български е около 85 KB и почти запълва нашия лимит от 96 KB на заявка. Когато каталогът не се побира, изпращаме само предварително подбрани кандидати.",
        "With 235 tools their Bulgarian description is about 85 KB, close to our own 96 KB limit per request. When the catalogue does not fit, we send only pre-selected candidates.",
      ),
      outcome: t(
        "При принудително стесняване до около 62 кандидата правилният инструмент беше сред тях в 99,3% от случаите и точността не спадна. Пращаме целия каталог, когато се побира, и стеснен — само когато не се побира.",
        "Forced down to about 62 candidates, the right tool was among them 99.3% of the time and accuracy did not fall. We send the whole catalogue when it fits and a narrowed one only when it does not.",
      ),
    },
    {
      date: t("17–18 септември", "17–18 September"),
      title: "Jev (TypeSafe)",
      body: t(
        "Jev не пише текст — само избира между варианти, които му подаваме, и казва колко е уверен. Така не може да измисли несъществуващ инструмент, а режимът без генеративен модел би могъл да разбира повече въпроси.",
        "Jev writes no text — it only chooses among options we give it and says how confident it is. It cannot invent a tool that does not exist, and a mode without a generative model could understand more questions.",
      ),
      outcome: t(
        "Когато е уверен, почти не греши, но поема само около 70% от въпросите. Не може да попълва отворени стойности (ЕИК, свободен текст, дати), а имената избира само сред резултатите от търсене — затова като цяло изостава от облачния модел. Изпитан е, но още не е пуснат за читателите. Прагът на увереност остава 0,70: при почти всички по-ниски прагове Jev е по-неточен от правилата на въпросите, които би поел от тях.",
        "When confident it is almost never wrong, but it takes only about 70% of the questions. It cannot fill open values (company IDs, free text, dates) and picks names only from search results — so overall it trails the cloud model. It has been tested but is not yet live for readers. The confidence gate stays at 0.70: at almost every lower gate Jev is less accurate than the rules on the questions it would take over from them.",
      ),
    },
    {
      date: t("18 септември", "18 September"),
      title: t("Jev избира, Gemini попълва", "Jev picks, Gemini fills in"),
      body: t(
        "Jev избира инструмента добре дори при грешки и други думи, но не може да попълни свободните параметри, а Gemini може. Затова, когато Jev е уверен, Gemini получава описанието само на избрания инструмент и попълва параметрите му; иначе получава целия каталог, както досега.",
        "Jev picks the tool well even with typos and rewording, but cannot fill open parameters, and Gemini can. So when Jev is confident, Gemini receives only the chosen tool's description and fills its parameters; otherwise it receives the whole catalogue, as before.",
      ),
      outcome: t(
        "Измерено в същия ден и на същите въпроси, това е по-точно от само Gemini — най-вече при параметрите — и подканата е около четири пъти по-кратка. По-точно е и при грешки, други думи и латиница. Изпитано е, но още не е пуснато за читателите.",
        "Measured on the same day and the same questions, it is more accurate than Gemini alone — above all on parameters — with a prompt about four times shorter. It is also more accurate with typos, rewording and Latin script. It has been tested but is not yet live for readers.",
      ),
    },
  ];
  return (
    <section aria-labelledby="history-title">
      <h2
        id="history-title"
        className="font-title text-2xl text-popover-foreground"
      >
        {t("Как стигнахме дотук", "How we got here")}
      </h2>
      <Lede>
        {t(
          "Всяка стъпка — защо я опитахме и какво решихме. Числата са към онзи момент; текущите резултати са в таблиците.",
          "Each step — why we tried it and what we decided. The numbers are from the time; the current results are in the tables.",
        )}
      </Lede>
      <ol className="mt-4 max-w-3xl space-y-5 border-l-2 pl-5 text-sm">
        {steps.map((s) => (
          <li key={s.date + s.title} className="relative">
            <span className="absolute -left-[1.6rem] top-1.5 size-2.5 rounded-full bg-primary" />
            <p className="text-xs uppercase tracking-wide text-muted-foreground">
              {s.date}
            </p>
            <p className="font-title text-lg text-popover-foreground">
              {s.title}
            </p>
            <p className="mt-1">{s.body}</p>
            <p className="mt-1 text-muted-foreground">
              <span className="font-medium text-foreground">
                {t("Решение: ", "Decision: ")}
              </span>
              {s.outcome}
            </p>
          </li>
        ))}
      </ol>
    </section>
  );
};

/**
 * Jev up close, on all 841 questions — the bank on which it and the rules were
 * each measured in a single run. The cloud model is absent because its starter
 * run is a separate artifact, not part of one 841-question measurement; the
 * headline table is where the three are compared.
 *
 * ⚠️ THE ABSTENTION COLUMNS DO NOT SHARE A DENOMINATOR. `toolAccWhenRouted` is
 * measured over the `jevRouted` subset, while `jevDeclined` and `jevUnsure` are
 * shares of ALL questions. Rendering the accuracy without the routed share
 * publishes a "99%" with its "70% of questions" removed — so both are shown,
 * and the headline "right tool" column (over every question) is unaffected.
 */
const JevCloseUp = ({
  index,
  t,
  lang,
}: {
  index: EvalsIndex | null;
  t: T;
  lang: Lang;
}) => {
  const { pair } = makeFmt(lang);
  const jev = index?.runs.find((r) => r.file === JEV_RUN_FILE);
  const det = index?.deterministic;
  if (!jev || !det?.metrics) return null;
  const lanes: Lane[] = [
    {
      id: "deterministic",
      name: t("Правила (без AI)", "Rules (no AI)"),
      note: "",
      cases: det.caseCount,
      groups: det.caseGroups,
      m: det.metrics,
      declines: false,
    },
    {
      id: "jev",
      name: "Jev (TypeSafe)",
      note: "",
      cases: jev.caseCount,
      groups: jev.caseGroups,
      m: jev.metrics,
      declines: true,
    },
  ];
  /** "Not applicable" and "not measured" are different claims and only one of
   *  them is a fact about the product. */
  const abstention = (l: Lane, key: MetricKey) =>
    !l.declines
      ? "—"
      : l.m.en[key] == null && l.m.bg[key] == null
        ? t("не е измерено", "not measured")
        : pair(l.m, key);
  return (
    <section aria-labelledby="jev-title">
      <h3 id="jev-title" className="font-title text-xl text-popover-foreground">
        {t("Jev отблизо", "Jev up close")}
      </h3>
      <Lede>
        {t(
          `Тук Jev и правилата са изпитани върху всички ${jev.caseCount} въпроса, включително предложените въпроси в чата. Облачният модел е изпитан върху предложените въпроси отделно (ред „Предложени въпроси“ по-горе), а не в едно общо измерване с останалите, затова тук липсва. Jev е единственият, който може да откаже, затова показваме колко въпроса поема и колко от тях решава правилно.`,
          `Here Jev and the rules are tested on all ${jev.caseCount} questions, including the chat's suggested questions. The cloud model was tested on the suggested questions separately (the “Suggested questions” row above), not in one run with the rest, so it is absent here. Jev is the only one that can decline, so we show how many questions it takes and how many of those it gets right.`,
        )}
      </Lede>
      <MismatchWarning lanes={lanes} t={t} />
      <DataTable note={langNote(t)}>
        <thead>
          <tr className="border-b-2">
            <Th>{t("Начин на избор", "Method")}</Th>
            <Th>{t("Въпроси", "Questions")}</Th>
            <Th>{t("Правилен инструмент", "Right tool")}</Th>
            <Th>{t("Изпълнимо извикване", "Usable call")}</Th>
            <Th>{t("Поети", "Taken")}</Th>
            <Th>{t("Отказани", "Declined")}</Th>
            <Th>{t("Точност при поетите", "Accuracy when taken")}</Th>
            <Th>
              {t(
                "Разпознава въпроси извън обхвата",
                "Spots off-topic questions",
              )}
            </Th>
          </tr>
        </thead>
        <tbody>
          {lanes.map((l) => (
            <tr key={l.id} data-lane={l.id} className="border-b">
              <RowTh>{l.name}</RowTh>
              <Num>{l.cases}</Num>
              <Num>{pair(l.m, "toolAcc")}</Num>
              <Num>{pair(l.m, "callAcc")}</Num>
              <Num>{abstention(l, "jevRouted")}</Num>
              <Num>{abstention(l, "jevDeclined")}</Num>
              <Num>{abstention(l, "toolAccWhenRouted")}</Num>
              <Num>
                {l.m.en.irrelevanceAcc == null && l.m.bg.irrelevanceAcc == null
                  ? "—"
                  : pair(l.m, "irrelevanceAcc")}
              </Num>
            </tr>
          ))}
        </tbody>
      </DataTable>
      <p className="mt-2 max-w-3xl text-xs text-muted-foreground">
        {t(
          "„Поети“ и „Отказани“ са дял от всички въпроси; „Точност при поетите“ се смята само върху поетите. Когато Jev не е достатъчно уверен, въпросът отива при правилата — това не е отказ.",
          "“Taken” and “Declined” are shares of all questions; “Accuracy when taken” is over the taken ones only. When Jev is not confident enough the question goes to the rules — that is not a decline.",
        )}
      </p>
    </section>
  );
};

/**
 * The Jev confidence-gate sweep: what the lane would score at each gate
 * between 0.50 and the published one.
 *
 * ⚠️ THE COLUMN THAT DECIDES IT IS THE HEAD-TO-HEAD, not the overall figures.
 * A lower gate changes only the questions it hands from the rules to Jev, so
 * overall accuracy moves by tenths of a point. On exactly those questions the
 * question is whether Jev beats the rules it replaces — so those two rates sit
 * side by side, and the takeaway sentence is COMPUTED from them rather than
 * written here, where it would go stale the next time the sweep is run.
 *
 * On the published gate's own row the head-to-head is "—": questions "gained"
 * there are Jev's confidence varying between calls, not a gate change, and the
 * method note states that count instead.
 */
const GateSweepSection = ({
  sweep,
  t,
  lang,
}: {
  sweep: GateSweep | null | undefined;
  t: T;
  lang: Lang;
}) => {
  const { pct, dec } = makeFmt(lang);
  if (!sweep?.sweep.length) return null;
  const lower = sweep.sweep.filter((s) => s.gate < sweep.publishedGate);
  const worse = (lang: Lang) =>
    lower.filter(
      (s) =>
        s.metrics[lang].movedJevToolAcc != null &&
        s.metrics[lang].movedRulesToolAcc != null &&
        s.metrics[lang].movedJevToolAcc! < s.metrics[lang].movedRulesToolAcc!,
    ).length;
  const sp = (
    s: GateSweep["sweep"][number],
    k: Exclude<
      keyof GateSweep["sweep"][number]["metrics"]["en"],
      "n" | "moved"
    >,
  ) => `${pct(s.metrics.en[k])} / ${pct(s.metrics.bg[k])}`;
  const gateLabel = (g: number) => dec(g, 3).replace(/0$/, "");
  return (
    <section aria-labelledby="gate-title">
      <h3
        id="gate-title"
        className="font-title text-xl text-popover-foreground"
      >
        {t("Праг на увереност за Jev", "Jev confidence gate")}
      </h3>
      <Lede>
        {t(
          `Когато Jev е по-малко уверен от прага (сега ${gateLabel(sweep.publishedGate)}), той не избира, а оставя въпроса на правилата. По-нисък праг му дава повече въпроси — но дали на точно тези въпроси той е по-точен от правилата, които замества?`,
          `When Jev is less confident than the gate (currently ${gateLabel(sweep.publishedGate)}), it does not choose and leaves the question to the rules. A lower gate gives it more questions — but on exactly those questions, is it more accurate than the rules it replaces?`,
        )}
      </Lede>
      {lower.length > 0 && (
        <p className="mt-2 max-w-3xl text-sm font-medium">
          {t(
            `На добавените въпроси Jev избира правилния инструмент по-рядко от правилата при ${worse("en")} от ${lower.length} по-ниски прага на английски и при ${worse("bg")} от ${lower.length} на български.`,
            `On the added questions Jev picks the right tool less often than the rules at ${worse("en")} of ${lower.length} lower gates in English and ${worse("bg")} of ${lower.length} in Bulgarian.`,
          )}
        </p>
      )}
      <DataTable note={langNote(t)}>
        <thead>
          <tr className="border-b-2">
            <Th>{t("Праг", "Gate")}</Th>
            <Th>{t("Поети", "Taken")}</Th>
            <Th>{t("Правилен инструмент", "Right tool")}</Th>
            <Th>{t("Изпълнимо извикване", "Usable call")}</Th>
            <Th>{t("Верни параметри", "Right parameters")}</Th>
            <Th>
              {t(
                "Разпознава въпроси извън обхвата",
                "Spots off-topic questions",
              )}
            </Th>
            <Th>{t("Добавени въпроси", "Added questions")}</Th>
            <Th>{t("Jev на добавените", "Jev on added")}</Th>
            <Th>{t("Правилата на добавените", "Rules on added")}</Th>
          </tr>
        </thead>
        <tbody>
          {sweep.sweep.map((s) => {
            const current = s.gate === sweep.publishedGate;
            return (
              <tr
                key={s.gate}
                data-gate={s.gate}
                className={current ? "border-b font-medium" : "border-b"}
              >
                <RowTh note={current ? t("текущ", "current") : undefined}>
                  {gateLabel(s.gate)}
                </RowTh>
                <Num>{sp(s, "jevRouted")}</Num>
                <Num>{sp(s, "toolAcc")}</Num>
                <Num>{sp(s, "callAcc")}</Num>
                <Num>{sp(s, "argAcc")}</Num>
                <Num>{sp(s, "irrelevanceAcc")}</Num>
                <Num>
                  {current
                    ? "—"
                    : `${s.metrics.en.moved} / ${s.metrics.bg.moved}`}
                </Num>
                <Num>{current ? "—" : sp(s, "movedJevToolAcc")}</Num>
                <Num>{current ? "—" : sp(s, "movedRulesToolAcc")}</Num>
              </tr>
            );
          })}
        </tbody>
      </DataTable>
      <p className="mt-2 max-w-3xl text-xs text-muted-foreground">
        {t(
          `Как е измерено: въпросите, при които Jev е бил над текущия праг, се държат еднакво при всеки по-нисък праг и са използвани наготово. Всеки от ${sweep.reasked}-те въпроса под прага е зададен отново точно веднъж, без праг, и всеки отговор е запазен — всички прагове са пресметнати от тази една извадка. Увереността на Jev леко се колебае между извикванията (средно с ${sweep.meanConfidenceDrift == null ? "—" : dec(sweep.meanConfidenceDrift, 3)}): ${sweep.crossedPublishedGate} от тези въпроси се върнаха над текущия праг, затова редът „текущ“ се различава малко от основното измерване.`,
          `How it was measured: questions Jev answered above the current gate behave the same at any lower gate and are reused as they are. Each of the ${sweep.reasked} below-gate questions was asked again exactly once, with no gate, and every answer was kept — all gates are computed from that one sample. Jev's confidence varies slightly between calls (by ${sweep.meanConfidenceDrift == null ? "—" : dec(sweep.meanConfidenceDrift, 3)} on average): ${sweep.crossedPublishedGate} of those questions came back above the current gate, so the “current” row differs slightly from the main measurement.`,
        )}
      </p>
    </section>
  );
};

export const EvalsScreen = ({
  integrated = false,
}: { integrated?: boolean } = {}) => {
  const navigation = useChatNavigation();
  const { theme, setTheme } = useContext(ThemeContext);
  const [localLang, setLang] = useState<Lang>(navigation.lang);
  const lang = integrated ? navigation.lang : localLang;
  const [run, setRun] = useState<Run | null>(null),
    [baseline, setBaseline] = useState<Run | null>(null);
  const [legacy, setLegacy] = useState<Legacy | null>(null),
    [recall, setRecall] = useState<Recall | null>(null);
  const [index, setIndex] = useState<EvalsIndex | null>(null);
  const [error, setError] = useState(false),
    [failuresOnly, setFailuresOnly] = useState(true);
  const t: T = (bg, en) => (lang === "bg" ? bg : en);
  const { dec, pct, pair } = makeFmt(lang);
  const Content = integrated ? "div" : "main";
  useEffect(() => {
    fetchData<Run>("/ai/evals/current_production.json")
      .then(setRun)
      .catch(() => setError(true));
    fetchData<Run>("/ai/evals/current_baseline_rescored.json")
      .then(setBaseline)
      .catch(() => {});
    fetchData<Legacy>("/ai/evals/fc_eval.json")
      .then(setLegacy)
      .catch(() => {});
    fetchData<Recall>("/ai/evals/retriever_recall.json")
      .then(setRecall)
      .catch(() => {});
    fetchData<EvalsIndex>("/ai/evals/index.json")
      .then(setIndex)
      .catch(() => {});
  }, []);
  const date = (s: string) =>
    new Date(s).toLocaleDateString(lang === "bg" ? "bg-BG" : "en-GB");
  const groupLabel = (g: string) =>
    ({
      registry: t(
        "Примери от описанията на инструментите",
        "Examples from the tool descriptions",
      ),
      realistic: t("Ежедневни въпроси", "Everyday questions"),
      conversation: t("Продължение на разговор", "Conversation follow-ups"),
      clarification: t("Нужно уточнение", "Needs clarification"),
      challenge: t("Трудни случаи", "Hard cases"),
      holdout: t("Контролни въпроси", "Held-out checks"),
      unsupported: t("Неподдържани заявки", "Unsupported requests"),
      starter: t("Предложени въпроси", "Suggested questions"),
    })[g] ?? g;
  // Run labels are artifact names, so they are translated here rather than sent
  // translated: the file is the identity and must stay greppable.
  const runLabel = (label: string) =>
    ({
      production: t("Пълен каталог", "Full catalogue"),
      control: t(
        "Само Gemini (контрола, същия ден)",
        "Gemini only (same-day control)",
      ),
      jev_gemini: t(
        "Jev избира инструмента, Gemini — параметрите",
        "Jev picks the tool, Gemini the parameters",
      ),
      narrowed: t("Стеснен каталог", "Narrowed catalogue"),
      starter: t("Предложени въпроси", "Suggested questions"),
      revised: t("След поправките", "After fixes"),
      baseline: t("Предишна подкана", "Earlier prompt"),
      baseline_rescored: t(
        "Предишна подкана, преоценена",
        "Earlier prompt, re-scored",
      ),
    })[label] ?? label;
  const comparable =
    baseline &&
    run &&
    baseline.suiteHash === run.suiteHash &&
    baseline.scoringHash === run.scoringHash;
  // Jev has its own section; the runs table is the CLOUD model's history, and a
  // Jev row there would sit an 841-question figure among 474-question ones.
  const cloudRuns = index?.runs.filter((r) => r.file !== JEV_RUN_FILE) ?? [];
  return (
    <div className="flex min-h-dvh flex-col bg-card text-foreground">
      {!integrated && (
        <header className="flex flex-wrap items-center justify-between gap-2 border-b-2 bg-muted px-4 py-2.5 shadow-sm">
          <a
            href={chatPath("chat", navigation.pathname)}
            className="flex items-center gap-2 text-xl text-primary"
          >
            <Logo className="size-7" />
            <span className="font-title">Наясно AI</span>
          </a>
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => {
                const next = lang === "bg" ? "en" : "bg";
                if (!integrated) {
                  setLang(next);
                  return;
                }
                const path = navigation.pathname.replace(/^\/en/, "");
                window.location.assign(
                  `${next === "en" ? "/en" : ""}${path}${navigation.search}`,
                );
              }}
              aria-label={t("Език", "Language")}
            >
              {lang === "bg" ? "EN" : "BG"}
            </Button>
            <Button
              variant="outline"
              size="icon"
              onClick={() =>
                setTheme(theme === themeDark ? themeLight : themeDark)
              }
              aria-label={t("Тема", "Theme")}
            >
              {theme === themeDark ? "☀" : "☾"}
            </Button>
          </div>
        </header>
      )}
      <Content className="container mx-auto flex-1 space-y-12 px-4 py-8">
        <div>
          <h1 className="font-title text-3xl font-semibold text-popover-foreground">
            {t("Как оценяваме AI чата", "How we evaluate the AI chat")}
          </h1>
          <p className="mt-3 max-w-3xl text-muted-foreground">
            {t(
              "Чатът не измисля числа. Всеки отговор с данни идва от инструмент — програма, която изчислява резултата от публичните данни. Затова най-важното, което мерим, е дали чатът избира правилния инструмент и дали му подава верните параметри: партия, година, община. Тук са резултатите, пътят до сегашното решение и това, което тестовете още не показват.",
              "The chat does not make up numbers. Every answer with data comes from a tool — a program that computes the result from public data. So what we measure most is whether the chat picks the right tool and gives it the right parameters: party, year, municipality. Here are the results, how we arrived at the current design, and what the tests do not yet show.",
            )}
          </p>
        </div>

        <Summary index={index} t={t} lang={lang} />
        <RobustnessSection robustness={index?.robustness} t={t} lang={lang} />
        <History t={t} />

        {error && (
          <p role="alert">
            {t(
              "Текущите резултати не можаха да се заредят.",
              "Current results could not be loaded.",
            )}
          </p>
        )}
        {!run && !error && <p>{t("Зареждане…", "Loading…")}</p>}
        {run && (
          <section aria-labelledby="details-title" className="space-y-10">
            <div>
              <h2
                id="details-title"
                className="font-title text-2xl text-popover-foreground"
              >
                {t("Подробни резултати", "Detailed results")}
              </h2>
              <Lede>
                {t(
                  "Всяко измерване е отделен файл и не презаписва предишните — така влошаване не остава незабелязано.",
                  "Each measurement is its own file and never overwrites the earlier ones — so a regression cannot go unnoticed.",
                )}
              </Lede>
            </div>

            <section>
              <H3>
                {t("Облачният модел", "The cloud model")}: Gemini 3.5 Flash-Lite
              </H3>
              <Lede>
                {date(run.finishedAt)} · {run.toolCount}{" "}
                {t("инструмента", "tools")} · {run.caseCount}{" "}
                {t("въпроса на всеки език", "questions per language")} ·{" "}
                {run.caseCount * 2 + (run.retriedErrors ?? 0)}{" "}
                {t("реални извиквания", "real calls")}
              </Lede>
              <DataTable note={langNote(t)}>
                <thead>
                  <tr className="border-b-2">
                    <Th>{t("Измерване", "Run")}</Th>
                    <Th>{t("Правилен инструмент", "Right tool")}</Th>
                    <Th>{t("Изпълнимо извикване", "Usable call")}</Th>
                    <Th>{t("Верни параметри", "Right parameters")}</Th>
                    <Th>{t("Валиден JSON", "Valid JSON")}</Th>
                  </tr>
                </thead>
                <tbody>
                  {(comparable ? [baseline!, run] : [run]).map((r) => (
                    <tr key={r.label} className="border-b">
                      <RowTh>{runLabel(r.label)}</RowTh>
                      <Num>
                        {pct(r.metrics.en.toolAcc)} /{" "}
                        {pct(r.metrics.bg.toolAcc)}
                      </Num>
                      <Num>
                        {pct(r.metrics.en.callAcc)} /{" "}
                        {pct(r.metrics.bg.callAcc)}
                      </Num>
                      <Num>
                        {pct(r.metrics.en.argAcc)} / {pct(r.metrics.bg.argAcc)}
                      </Num>
                      <Num>
                        {pct(r.metrics.en.jsonValidRate)} /{" "}
                        {pct(r.metrics.bg.jsonValidRate)}
                      </Num>
                    </tr>
                  ))}
                </tbody>
              </DataTable>
              <Lede>
                {t(
                  `Параметрите се оценяват върху всички ${run.metrics.en.argN} въпроса на всеки език с проверени отговори, включително когато моделът е избрал грешен инструмент.`,
                  `Parameters are scored over all ${run.metrics.en.argN} questions per language with checked answers, including those where the model chose the wrong tool.`,
                )}
                {baseline?.replaySource &&
                  t(
                    " Отговорите от предишната подкана са преоценени със сегашната проверка, без нови извиквания.",
                    " Responses from the earlier prompt are re-scored with the current checks, without new calls.",
                  )}
              </Lede>
            </section>

            {cloudRuns.length > 0 && (
              <section>
                <H3>
                  {t(
                    "Всички измервания на облачния модел",
                    "All cloud-model runs",
                  )}
                </H3>
                <Lede>
                  {t(
                    "„Бюджет“ е лимитът в байтове, до който се стеснява каталогът. „Принудително“ значи по-нисък от реалния, за да се изпита стесняването при всеки въпрос. „Верен сред кандидатите“ е таванът на стесняването: ако правилният инструмент не е сред подадените, моделът не може да го избере.",
                    "“Budget” is the byte limit the catalogue is narrowed to. “Forced” means lower than the real one, so narrowing is exercised on every question. “Right among candidates” is the ceiling narrowing imposes: if the right tool is not among those given, no model can choose it.",
                  )}
                </Lede>
                <DataTable note={langNote(t)}>
                  <thead>
                    <tr className="border-b-2">
                      <Th>{t("Измерване", "Run")}</Th>
                      <Th>{t("Дата", "Date")}</Th>
                      <Th>{t("Въпроси", "Questions")}</Th>
                      <Th>{t("Бюджет", "Budget")}</Th>
                      <Th>{t("Правилен инструмент", "Right tool")}</Th>
                      <Th>{t("Изпълнимо извикване", "Usable call")}</Th>
                      <Th>{t("Верни параметри", "Right parameters")}</Th>
                      <Th>
                        {t("Верен сред кандидатите", "Right among candidates")}
                      </Th>
                    </tr>
                  </thead>
                  <tbody>
                    {cloudRuns.map((r) => (
                      <tr key={r.file} className="border-b align-top">
                        <th
                          scope="row"
                          className="whitespace-nowrap p-2 text-left font-medium"
                        >
                          {runLabel(r.label)}
                          {r.forcedBudget && (
                            <span className="ml-1 rounded bg-muted px-1 text-xs font-normal">
                              {t("принудително", "forced")}
                            </span>
                          )}
                        </th>
                        <Num>{r.finishedAt ? date(r.finishedAt) : "—"}</Num>
                        <Num>
                          {r.caseCount}
                          {/* Which groups a PARTIAL run covered — omitted when
                              it would only repeat the run's own name. */}
                          {r.caseGroups &&
                            r.caseGroups.length < 7 &&
                            r.caseGroups.map(groupLabel).join(", ") !==
                              runLabel(r.label) && (
                              <span className="block text-xs text-muted-foreground">
                                {r.caseGroups.map(groupLabel).join(", ")}
                              </span>
                            )}
                        </Num>
                        <Num>
                          {r.routingBudget == null
                            ? "—"
                            : `${Math.round(r.routingBudget / 1000)}k`}
                          {r.meanCandidatesKept != null && (
                            <span className="block text-xs text-muted-foreground">
                              {t("средно", "mean")}{" "}
                              {dec(r.meanCandidatesKept, 1)}
                            </span>
                          )}
                        </Num>
                        <Num>{pair(r.metrics, "toolAcc")}</Num>
                        <Num>{pair(r.metrics, "callAcc")}</Num>
                        <Num>
                          {pair(r.metrics, "argAcc")}
                          <span className="block text-xs text-muted-foreground">
                            {r.metrics.en.argN}/{r.metrics.bg.argN}
                          </span>
                        </Num>
                        <Num>
                          {r.goldInCandidates
                            ? pct(
                                r.goldInCandidates.kept /
                                  r.goldInCandidates.total,
                              )
                            : "—"}
                        </Num>
                      </tr>
                    ))}
                  </tbody>
                </DataTable>
              </section>
            )}

            <JevCloseUp index={index} t={t} lang={lang} />
            <GateSweepSection sweep={index?.gateSweep} t={t} lang={lang} />

            {index?.deterministic?.metrics && (
              <section>
                <H3>{t("Правилата без AI", "Rules without AI")}</H3>
                <Lede>
                  {t(
                    `Режимът „Без AI“ не използва модел, затова се измерва безплатно върху всички ${index.deterministic.caseCount} въпроса. Показваме и резултата без предложените въпроси, защото долната граница, под която тестът не бива да пада, е определена върху него.`,
                    `The “No AI” mode uses no model, so it is measured for free on all ${index.deterministic.caseCount} questions. The result without the suggested questions is shown too, because the floor the test must not fall below was set on it.`,
                  )}
                </Lede>
                <DataTable note={langNote(t)}>
                  <thead>
                    <tr className="border-b-2">
                      <Th>{t("Набор въпроси", "Question set")}</Th>
                      <Th>{t("Въпроси", "Questions")}</Th>
                      <Th>{t("Правилен инструмент", "Right tool")}</Th>
                      <Th>{t("Изпълнимо извикване", "Usable call")}</Th>
                      <Th>{t("Верни параметри", "Right parameters")}</Th>
                    </tr>
                  </thead>
                  <tbody>
                    {(
                      [
                        [
                          t(
                            "Всички, с предложените въпроси",
                            "All, with the suggested questions",
                          ),
                          index.deterministic.metrics,
                        ],
                        [
                          t(
                            "Без предложените въпроси",
                            "Without the suggested questions",
                          ),
                          index.deterministic.legacyMetrics,
                        ],
                      ] as const
                    )
                      .filter(([, m]) => m)
                      .map(([label, m]) => (
                        <tr key={label} className="border-b">
                          <RowTh>{label}</RowTh>
                          <Num>
                            {m!.en.n} / {m!.bg.n}
                          </Num>
                          <Num>{pair(m, "toolAcc")}</Num>
                          <Num>{pair(m, "callAcc")}</Num>
                          <Num>{pair(m, "argAcc")}</Num>
                        </tr>
                      ))}
                  </tbody>
                </DataTable>
              </section>
            )}

            <section>
              <H3>{t("По групи въпроси", "By question group")}</H3>
              <Lede>
                {t(
                  "Облачният модел по видове въпроси — дял на успешните извиквания.",
                  "The cloud model by kind of question — share of usable calls.",
                )}
              </Lede>
              <DataTable>
                <thead>
                  <tr className="border-b-2">
                    <Th>{t("Група", "Group")}</Th>
                    <Th>{t("Въпроси", "Questions")}</Th>
                    <Th>{t("Английски", "English")}</Th>
                    <Th>{t("Български", "Bulgarian")}</Th>
                  </tr>
                </thead>
                <tbody>
                  {Object.entries(run.groups).map(([g, m]) => (
                    <tr key={g} className="border-b">
                      <RowTh>{groupLabel(g)}</RowTh>
                      <Num>{m.en.n}</Num>
                      <Num>{pct(m.en.callAcc)}</Num>
                      <Num>{pct(m.bg.callAcc)}</Num>
                    </tr>
                  ))}
                </tbody>
              </DataTable>
            </section>

            <details className="rounded border p-4">
              <summary className="cursor-pointer font-title text-xl text-popover-foreground">
                {t(
                  "ToolGrad: какво пробвахме и какво запазихме",
                  "ToolGrad: what we tried and what we kept",
                )}
              </summary>
              <ToolGradSection lang={lang} />
            </details>

            <section>
              <H3>{t("Отделните въпроси", "Individual questions")}</H3>
              <label className="my-3 flex items-center gap-2 text-sm">
                <input
                  type="checkbox"
                  checked={failuresOnly}
                  onChange={(e) => setFailuresOnly(e.target.checked)}
                />
                {t("Само сгрешените", "Failures only")}
              </label>
              <div className="max-h-[36rem] overflow-auto rounded border">
                <table className="w-full text-left text-sm">
                  <thead>
                    <tr className="border-b bg-muted">
                      <Th>{t("Въпрос", "Question")}</Th>
                      <Th>{t("Очакван → избран", "Expected → chosen")}</Th>
                      <Th>{t("Резултат", "Result")}</Th>
                    </tr>
                  </thead>
                  <tbody>
                    {run.rows
                      .filter(
                        (r) => r.lang === lang && (!failuresOnly || !r.callOk),
                      )
                      .map((r) => {
                        const c = run.cases.find((x) => x.id === r.id);
                        return (
                          <tr key={r.id} className="border-b align-top">
                            <td className="max-w-lg whitespace-pre-line p-2">
                              {c?.[lang]}
                              {c?.history && (
                                <details className="mt-1 text-xs text-muted-foreground">
                                  <summary className="cursor-pointer">
                                    {t("Предишен контекст", "Previous context")}
                                  </summary>
                                  <pre className="whitespace-pre-wrap break-words">
                                    {JSON.stringify(c.history[lang], null, 2)}
                                  </pre>
                                </details>
                              )}
                              {c?.review && (
                                <div className="mt-1 text-xs text-muted-foreground">
                                  {t(
                                    "Проверен очакван отговор / уточнен въпрос",
                                    "Checked expected answer / clarified question",
                                  )}
                                </div>
                              )}
                              <div className="mt-1 text-xs text-muted-foreground">
                                {groupLabel(r.group)} · {r.id}
                              </div>
                            </td>
                            <td className="p-2 font-mono text-xs">
                              {r.expectedTool ?? "∅"} → {r.selected ?? "∅"}
                              {r.parsed && r.parsed.tool !== r.selected && (
                                <div>
                                  {t("След проверка", "After validation")}:{" "}
                                  {r.parsed.tool}
                                </div>
                              )}
                            </td>
                            <td className="p-2">
                              <span>
                                {r.callOk
                                  ? "✓"
                                  : r.error
                                    ? t("Грешка на API", "API error")
                                    : !r.toolOk
                                      ? t(
                                          "Друг инструмент / без извикване",
                                          "Different tool / no call",
                                        )
                                      : t(
                                          "Параметри / проверка",
                                          "Parameters / validation",
                                        )}
                              </span>
                              <details className="mt-1 text-xs">
                                <summary className="cursor-pointer">
                                  {t("Отговор на модела", "Model response")}
                                </summary>
                                <pre className="max-w-md whitespace-pre-wrap break-words py-2">
                                  {r.raw || r.error}
                                </pre>
                              </details>
                            </td>
                          </tr>
                        );
                      })}
                  </tbody>
                </table>
              </div>
            </section>
          </section>
        )}

        <section className="max-w-3xl text-sm">
          <H2>
            {t("Какво тестовете не показват", "What the tests do not show")}
          </H2>
          <ul className="mt-3 list-disc space-y-2 pl-5 text-muted-foreground">
            <li>
              {t(
                "Тестът мери само избора на инструмент и параметрите. Той не изпълнява инструментите и не оценява крайния текст — за тях има отделни автоматични тестове с фиксирани данни, които проверяват изпълнението, липсващите данни, източниците и числата в текста.",
                "The test measures only the choice of tool and its parameters. It does not run the tools or judge the final text — separate automated tests with fixed data check execution, missing data, sources and the numbers in the text.",
              )}
            </li>
            <li>
              {t(
                "Примерите от регистъра са близки до описанията на самите инструменти, затова не са независима оценка на реалните въпроси на читателите.",
                "The registry examples are close to the tools' own descriptions, so they are not an independent estimate of readers' real questions.",
              )}
            </li>
            <li>
              {t(
                "Ежедневните въпроси са написани от нас, а не събрани от реални разговори. След като сме ги използвали да откриваме грешки, те вече не са независим контролен набор. Малкият контролен набор не е използван за редактиране на описанията.",
                "The everyday questions were written by us, not collected from real conversations. Once used to find mistakes, they are no longer an independent check. The small held-out set was not used to edit the descriptions.",
              )}
            </li>
            <li>
              {t(
                "При въпросите без проверени отговори проверката гледа само формата на параметрите, не дали са смислово верни.",
                "On questions without checked answers, validation only checks the form of the parameters, not whether they are right.",
              )}
            </li>
            <li>
              {t(
                "При единадесет въпроса без посочено лице или фирма очакваме чатът да поиска уточнение, а шест двусмислени въпроса са уточнени. Класациите приемат само определен набор показатели, а проверката различава календарна година от подвижен период.",
                "For eleven questions naming no person or company we expect the chat to ask for clarification, and six ambiguous questions were made precise. Rankings accept only a fixed set of metrics, and validation tells a calendar year from a rolling period.",
              )}
            </li>
            <li>
              {t(
                "Всеки вариант е измерен веднъж; разлика от един-два пункта може да е просто колебание на модела.",
                "Each variant was measured once; a difference of one or two points may be just model variation.",
              )}
            </li>
            <li>
              {t(
                "Jev и Jev + Gemini са измерени директно срещу API-тата на TypeSafe и Google, без нашия сървър-посредник и неговия лимит за време. В реална работа Jev може да поема по-малко въпроси.",
                "Jev and Jev + Gemini were measured directly against TypeSafe's and Google's APIs, without our proxy server and its time limit. In real use Jev may take fewer questions.",
              )}
            </li>
          </ul>
        </section>

        <div className="space-y-3">
          {run && (
            <details className="rounded border p-3 text-sm">
              <summary className="cursor-pointer font-medium">
                {t("Възпроизводимост", "Reproducibility")}
              </summary>
              <div className="mt-3 space-y-2 break-all text-xs text-muted-foreground">
                <p>{run.provider}</p>
                <p>
                  {run.model} · temperature {run.settings.temperature} ·
                  max_tokens {run.settings.max_tokens} · reasoning{" "}
                  {run.settings.reasoning_effort}
                </p>
                <p>
                  {t("Отпечатък на въпросите", "Suite hash")}: {run.suiteHash}
                </p>
                <p>
                  {t("Отпечатък на подканата", "Prompt hash")}: {run.promptHash}
                </p>
                <p>
                  {t("Отпечатък на регистъра", "Registry hash")}:{" "}
                  {run.registryHash}
                </p>
                <p>
                  {t("Грешки на API EN / BG", "API errors EN / BG")}:{" "}
                  {run.metrics.en.errors} / {run.metrics.bg.errors}
                </p>
                <p>
                  {t(
                    "Повторени временни грешки на API",
                    "Retried transient API errors",
                  )}
                  : {run.retriedErrors ?? 0}.{" "}
                  {t(
                    "Първоначалните отговори и грешки са запазени в архива.",
                    "Original responses and errors are kept in the run archive.",
                  )}
                </p>
                <p>ai/llm/currentEval.run.ts · data/ai/evals/runs/</p>
              </div>
            </details>
          )}
          <details className="rounded border p-3 text-sm">
            <summary className="cursor-pointer font-medium">
              {t(
                "Архив: ранните опити от юни",
                "Archive: the early attempts from June",
              )}
            </summary>
            <p className="my-3 max-w-3xl text-muted-foreground">
              {t(
                "Моделите в браузъра и търсачките на инструменти от стъпки 2–4 по-горе. Регистърът, въпросите и подканите тогава бяха други, затова числата не са пряко сравними със сегашните.",
                "The browser models and tool search from steps 2–4 above. The registry, questions and prompts were different then, so the numbers are not directly comparable with today's.",
              )}
            </p>
            {legacy && (
              <>
                <p>
                  {date(legacy.generatedAt)} · {legacy.method.toolCount}{" "}
                  {t("инструмента", "tools")} · {legacy.method.caseCount}{" "}
                  {t("въпроса", "questions")}
                </p>
                <DataTable>
                  <thead>
                    <tr className="border-b">
                      <Th>{t("Модел", "Model")}</Th>
                      <Th>{t("Начин на изпитване", "Setup")}</Th>
                      <Th>{t("Английски", "English")}</Th>
                      <Th>{t("Български", "Bulgarian")}</Th>
                    </tr>
                  </thead>
                  <tbody>
                    {legacy.models.map((m) => (
                      <tr key={m.id} className="border-b">
                        <RowTh>{m.label}</RowTh>
                        <Num>{m.toolMode}</Num>
                        <Num>{pct(m.perLang?.en.toolAcc)}</Num>
                        <Num>{pct(m.perLang?.bg.toolAcc)}</Num>
                      </tr>
                    ))}
                  </tbody>
                </DataTable>
              </>
            )}
            {recall && (
              <div className="mt-4">
                <p className="font-medium">
                  {t(
                    "Правилният инструмент сред първите 8 от търсачката",
                    "Right tool among the search's top 8",
                  )}{" "}
                  · {date(recall.generatedAt)}
                </p>
                <ul className="mt-2 space-y-1">
                  {recall.rows.map((r) => (
                    <li key={r.id}>
                      {r.label[lang].replace(/ — current| — текущ/g, "")} —{" "}
                      {pct(r.declined["8"])}
                    </li>
                  ))}
                </ul>
                <p className="mt-2 text-xs text-muted-foreground">
                  {t(
                    "Върху въпросите, на които правилата не отговарят; изкуствено генериран набор. Дообученият модел е обучен и изпитан върху въпроси от един и същ генератор, затова резултатът му е оптимистичен.",
                    "On the questions the rules do not answer; a synthetic set. The fine-tuned model was trained and tested on questions from the same generator, so its result is optimistic.",
                  )}
                </p>
              </div>
            )}
          </details>
        </div>
      </Content>
      {!integrated && (
        <footer className="border-t bg-muted p-4 text-center text-xs">
          <a href={chatPath("chat", navigation.pathname)}>
            {t("Към чата", "Back to chat")}
          </a>{" "}
          · <a href={SITE_ORIGIN}>{SITE_HOST}</a>
        </footer>
      )}
    </div>
  );
};
