// Invariants over the data-map model and the committed manifest.
//
// Until 2026-08-31 there was no test here at all, and the gap was not
// theoretical: `["src:keep_eu", "ds:funds"]` asserted for months that the
// Interreg corpus is part of ИСУН — a merge the serving layer exists to
// prevent — and `validate()` accepted it, because it is tier-valid
// (src: → ds:) and validate() only checks tiers. The correction lived in a
// comment, which is exactly what a comment cannot enforce.
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";
import { DATASETS, EDGES, SOURCE_GROUPS, FEATURES } from "./model";

const ROOT = path.resolve(import.meta.dirname, "../..");
const manifest = JSON.parse(
  readFileSync(path.join(ROOT, "data/data_map.json"), "utf8"),
) as {
  nodes: { id: string; kind: string }[];
  edges: { id: string; from: string; to: string }[];
};

const pair = (e: { from: string; to: string }) => `${e.from} -> ${e.to}`;
const manifestPairs = new Set(manifest.edges.map(pair));

describe("data-map model", () => {
  it("keeps Interreg a separate dataset from ИСУН EU funds", () => {
    // The two corpora are disjoint by construction: Interreg is managed on
    // Jems, fund_projects holds zero Interreg rows, and the totals measure
    // different things (a contract's own value vs one partner's budget). An
    // edge into ds:funds claims a merge that funds_fit_basis() ships a basis
    // declaration to prevent.
    const keepEu = EDGES.filter(([from]) => from === "src:keep_eu");
    expect(keepEu).toEqual([["src:keep_eu", "ds:interreg"]]);
    expect(DATASETS.map((d) => d.id)).toContain("interreg");
  });

  it("gives every dataset node a source and at least one consumer", () => {
    // A dataset with no incoming edge has no provenance; one with no outgoing
    // edge renders as an orphan and tells a reader nothing uses it. ds:interreg
    // was briefly the latter, between being added and its consumers being
    // traced.
    //
    // Consumers are counted from the BUILT manifest, not from EDGES: a dataset
    // whose only reader is the AI assistant (ds:security, ds:transport today)
    // reaches f:ai through an edge the build derives from AI_PATH_RULES, and it
    // is legitimately consumed. Asserting on EDGES alone would call those two
    // orphans and force a hand-written duplicate of a derived edge.
    const ins = new Set(manifest.edges.map((e) => e.to));
    const outs = new Set(manifest.edges.map((e) => e.from));
    const missing = DATASETS.flatMap((d) => {
      const id = `ds:${d.id}`;
      return [
        ...(ins.has(id) ? [] : [`${id} has no source edge`]),
        ...(outs.has(id) ? [] : [`${id} has no consumer edge`]),
      ];
    });
    expect(missing).toEqual([]);
  });

  it("declares no edge twice and no edge to an unknown node", () => {
    const known = new Set([
      ...SOURCE_GROUPS.map((g) => `src:${g.id}`),
      ...DATASETS.map((d) => `ds:${d.id}`),
      ...FEATURES.map((f) => `f:${f.id}`),
    ]);
    const unknown = EDGES.flatMap(([from, to]) =>
      [from, to].filter((n) => !known.has(n)),
    );
    expect(unknown).toEqual([]);

    const seen = new Set<string>();
    const dupes = EDGES.filter(([from, to]) => {
      const k = `${from} -> ${to}`;
      if (seen.has(k)) return true;
      seen.add(k);
      return false;
    });
    expect(dupes).toEqual([]);
  });
});

describe("committed manifest", () => {
  // data/data_map.json is committed AND regenerated by `prebuild`, so a commit
  // that edits model.ts without running `npm run data:map` ships a stale
  // artifact to the bucket while every local build silently rewrites it — the
  // drift then surfaces as churn in an unrelated diff instead of as a failure.
  it("contains every model-declared edge", () => {
    const missing = EDGES.map(([from, to]) => `${from} -> ${to}`).filter(
      (k) => !manifestPairs.has(k),
    );
    expect(missing).toEqual([]);
  });

  it("contains every model-declared node, and no unknown one", () => {
    const declared = new Set([
      ...SOURCE_GROUPS.map((g) => `src:${g.id}`),
      ...DATASETS.map((d) => `ds:${d.id}`),
      ...FEATURES.map((f) => `f:${f.id}`),
    ]);
    const built = new Set(manifest.nodes.map((n) => n.id));
    expect([...declared].filter((d) => !built.has(d))).toEqual([]);
    // f:ai is synthesised by the build rather than declared in FEATURES.
    expect([...built].filter((b) => !declared.has(b) && b !== "f:ai")).toEqual(
      [],
    );
  });

  it("carries no lateral dataset->dataset edge in the lineage array", () => {
    // Lateral links (plan T1) ride a separate `links` array and are never ELK
    // inputs; a ds:->ds: edge here would shatter the dataset tier's layout.
    const lateral = manifest.edges.filter(
      (e) => e.from.startsWith("ds:") && e.to.startsWith("ds:"),
    );
    expect(lateral).toEqual([]);
  });
});
