/**
 * One-off: bake data/regions_map.json (Bulgaria oblast GeoJSON, lon/lat) into a
 * compact set of pre-projected SVG paths for the AI chat empty-state hero's
 * mini "regional map" answer-card. Projecting + simplifying here (offline) means
 * the landing page never loads the 407 KB GeoJSON or pulls d3-geo at runtime — it
 * just renders ~31 short <path> strings that theme-swap via CSS fill vars.
 *
 * Run:  node_modules/.bin/tsx scripts/brand/bake_bg_oblast_paths.ts
 * Out:  ai/app/hero/bgOblastPaths.ts  (committed)
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { geoMercator, geoPath } from "d3";
import type {
  FeatureCollection,
  Feature,
  Polygon,
  MultiPolygon,
  Position,
} from "geojson";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "../..");
const SRC = resolve(ROOT, "data/regions_map.json");
const OUT = resolve(ROOT, "ai/app/hero/bgOblastPaths.ts");

const W = 360;
const H = 232;
const TOLERANCE = 0.02; // ~1.2px at this scale — plenty for a decorative map

// --- Douglas–Peucker ring simplification (perpendicular distance, lon/lat) ---
const perpDist = (p: Position, a: Position, b: Position): number => {
  const [x, y] = p;
  const [x1, y1] = a;
  const [x2, y2] = b;
  const dx = x2 - x1;
  const dy = y2 - y1;
  const len2 = dx * dx + dy * dy;
  if (len2 === 0) return Math.hypot(x - x1, y - y1);
  const t = ((x - x1) * dx + (y - y1) * dy) / len2;
  const cx = x1 + t * dx;
  const cy = y1 + t * dy;
  return Math.hypot(x - cx, y - cy);
};

const dp = (pts: Position[], tol: number): Position[] => {
  if (pts.length < 3) return pts;
  let maxD = 0;
  let idx = 0;
  for (let i = 1; i < pts.length - 1; i++) {
    const d = perpDist(pts[i], pts[0], pts[pts.length - 1]);
    if (d > maxD) {
      maxD = d;
      idx = i;
    }
  }
  if (maxD <= tol) return [pts[0], pts[pts.length - 1]];
  const left = dp(pts.slice(0, idx + 1), tol);
  const right = dp(pts.slice(idx), tol);
  return [...left.slice(0, -1), ...right];
};

const simplifyRing = (ring: Position[]): Position[] => {
  const s = dp(ring, TOLERANCE);
  return s.length >= 4 ? s : ring; // keep a valid closed ring
};

const simplifyGeom = (g: Polygon | MultiPolygon): Polygon | MultiPolygon => {
  if (g.type === "Polygon") {
    return { type: "Polygon", coordinates: g.coordinates.map(simplifyRing) };
  }
  return {
    type: "MultiPolygon",
    coordinates: g.coordinates.map((poly) => poly.map(simplifyRing)),
  };
};

const fc = JSON.parse(readFileSync(SRC, "utf-8")) as FeatureCollection<
  Polygon | MultiPolygon,
  { nuts3?: string }
>;

const simplified: FeatureCollection<Polygon | MultiPolygon> = {
  type: "FeatureCollection",
  features: fc.features.map(
    (f): Feature<Polygon | MultiPolygon> => ({
      type: "Feature",
      properties: f.properties,
      geometry: simplifyGeom(f.geometry),
    }),
  ),
};

// fit the simplified country into the WxH box, padding a touch
const projection = geoMercator().fitExtent(
  [
    [6, 6],
    [W - 6, H - 6],
  ],
  simplified,
);
const path = geoPath(projection);

const round = (d: string) =>
  d.replace(/-?\d+\.\d+/g, (m) => String(Math.round(Number(m))));

const oblasts = simplified.features
  .map((f) => {
    const code = (f.properties as { nuts3?: string } | null)?.nuts3 ?? "";
    const d = path(f);
    return d ? { code, d: round(d) } : null;
  })
  .filter((x): x is { code: string; d: string } => x !== null);

const body = `// AUTO-GENERATED by scripts/brand/bake_bg_oblast_paths.ts — do not edit by hand.
// Pre-projected + simplified Bulgaria oblast outlines for the AI empty-state hero map card.
export const BG_MAP_VIEWBOX = "0 0 ${W} ${H}";
export const BG_OBLASTS: { code: string; d: string }[] = ${JSON.stringify(
  oblasts,
)};
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, body);
console.log(`Wrote ${oblasts.length} oblast paths -> ${OUT}`);
