// Parser for parliament.bg's per-MP "Поименно гласуване" PDFs.
//
// This is a fallback for the rare case where the CSV and XLSX attachments
// labelled "Поименно гласуване" are actually the GROUPS-aggregate file
// (parliament.bg occasionally uploads the per-group file under the per-MP
// label and never publishes a real per-MP CSV/XLSX — only the PDF). The
// PDF is generated by Microsoft SQL Reporting Services and has extractable
// text via pdftotext.
//
// Mojibake caveat: the PDF text is encoded with a private-use-area font
// mapping (typical SSRS output), so MP names, party labels, and the
// presence/absence marker letter come through as Latin/PUA glyphs we can't
// reliably reverse. BUT every piece of data we actually need is ASCII:
//
//   • MP IDs are 4-digit decimal numbers
//   • NS number is "52" (or similar)
//   • Vote codes are +, -, =, 0
//   • Item-number column headers are bare integers
//
// We extract these directly. MP name + party are filled in from
// `knownMpById` (built from the most recent session shard in the same NS).
// MPs that didn't appear in the prior session get a placeholder name —
// they'll be flagged as unresolved downstream the same way the
// CSV/XLSX paths handle missing roster matches.

import { execFileSync } from "child_process";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import type { RawCsvRow } from "./parse";

export interface PdfParseContext {
  fallbackNs: string;
  // mpId → { name, partyShort } sourced from the most recent same-NS session
  // shard. Used to fill in the mojibake fields the PDF can't supply.
  knownMpById?: Map<number, { name: string; partyShort: string }>;
}

const VOTE_CODES = new Set(["+", "-", "=", "0"]);

const isColumnHeaderTokens = (tokens: string[]): boolean => {
  if (tokens.length < 4) return false;
  if (!tokens.every((t) => /^\d{1,3}$/.test(t))) return false;
  // Genuine column-headers always start at 1 or continue a contiguous run
  // (e.g. "24 25 26 …"). Reject otherwise — guards against accidentally
  // catching an item-number / tally line.
  const nums = tokens.map(Number);
  for (let i = 1; i < nums.length; i++) {
    if (nums[i] !== nums[i - 1] + 1) return false;
  }
  return nums[0] === 1 || nums[0] >= 2;
};

const runPdftotext = (buffer: Buffer): string => {
  const tmpPath = path.join(
    os.tmpdir(),
    `rollcall_${Date.now()}_${Math.floor(Math.random() * 1e6)}.pdf`,
  );
  fs.writeFileSync(tmpPath, buffer);
  try {
    return execFileSync("pdftotext", ["-layout", tmpPath, "-"], {
      encoding: "utf8",
      maxBuffer: 64 * 1024 * 1024,
    });
  } finally {
    try {
      fs.unlinkSync(tmpPath);
    } catch {
      /* best-effort cleanup */
    }
  }
};

export const parsePdf = (buffer: Buffer, ctx: PdfParseContext): RawCsvRow[] => {
  const text = runPdftotext(buffer);
  return parsePdfText(text, ctx);
};

export const parsePdfText = (
  text: string,
  ctx: PdfParseContext,
): RawCsvRow[] => {
  const lines = text.split("\n");
  let currentItems: number[] = [];
  const rows: RawCsvRow[] = [];
  // Dedupe across page breaks — if the same (mpId, item) appears twice
  // (shouldn't, but layout occasionally repeats a row at the page boundary
  // for orientation), keep the first.
  const seen = new Set<string>();

  for (const rawLine of lines) {
    // pdftotext occasionally emits non-breaking spaces (U+00A0) between
    // columns; fold to regular space so the tokenizer doesn't glue fields.
    const NBSP_RE = new RegExp(String.fromCharCode(0x00a0), "g");
    const line = rawLine.replace(NBSP_RE, " ");
    const stripped = line.trim();
    if (!stripped) continue;

    const tokens = stripped.split(/\s+/);
    if (isColumnHeaderTokens(tokens)) {
      currentItems = tokens.map(Number);
      continue;
    }
    if (currentItems.length === 0) continue;

    // A vote row looks like:
    //   <mojibake-name>... <mpId 4 digits> <mojibake-party> 52 <code> <code> ...
    // The first column after NS is item 1, which on a typical session is the
    // registration marker — a Cyrillic П/О/Р letter that survives the SSRS
    // font encoding as private-use-area mojibake. All subsequent columns are
    // standard ASCII vote codes (+/-/=/0). Treat any non-ASCII token as
    // "absent" (matches the CSV/XLSX parser's VOTE_MAP behaviour for Р/О/П).
    const idAnchor = stripped.match(/(\d{3,5})\s+\S+\s+52\s+/);
    if (!idAnchor || idAnchor.index === undefined) continue;
    const mpId = parseInt(idAnchor[1], 10);
    if (!Number.isFinite(mpId) || mpId < 100) continue;

    const after = stripped.slice(idAnchor.index + idAnchor[0].length);
    const allTokens = after.split(/\s+/).filter((t) => t.length > 0);
    if (allTokens.length < currentItems.length) {
      // Wrapped continuation line (long party names overflow onto a second
      // PDF line); the data row below carries the codes. Skip silently.
      continue;
    }
    const codes = allTokens
      .slice(0, currentItems.length)
      .map((t) => (VOTE_CODES.has(t) ? t : "0"));

    const known = ctx.knownMpById?.get(mpId);
    const mpName = known?.name ?? `MP ${mpId}`;
    const partyShort = known?.partyShort ?? "";

    for (let i = 0; i < currentItems.length; i++) {
      const item = currentItems[i];
      const key = `${mpId}-${item}`;
      if (seen.has(key)) continue;
      seen.add(key);
      rows.push({
        mpName,
        mpId,
        partyShort,
        nsFolder: ctx.fallbackNs,
        item,
        voteCode: codes[i],
      });
    }
  }

  if (rows.length === 0) {
    throw new Error(
      "PDF parser produced 0 vote rows — no column-header lines matched, " +
        "or no MP rows matched the expected layout (mpId + 52 + codes). " +
        "Inspect the pdftotext -layout output to identify the drift.",
    );
  }
  return rows;
};
