// Slim per-município geo pins for EU-funded projects. Generated by
// scripts/funds/build_geo_pins.ts from the heavy per-município corpus —
// the SPA fetches just the trimmed map-ready slice (max 200 pins,
// largest-totalEur-first per município) so the Leaflet tile loads in
// milliseconds even for big municipalities.

import { useQuery } from "@tanstack/react-query";
import { dataUrl } from "@/data/dataUrl";

export type FundsGeoPin = {
  ekatte: string;
  lat: number;
  lon: number;
  title: string;
  totalEur: number;
  status: string;
  contractNumber: string;
  programName?: string;
};

export type FundsGeoFile = {
  obshtina: string;
  generatedAt: string;
  sourceContractCount: number;
  geocodedCount: number;
  pins: FundsGeoPin[];
};

const fetchGeo = async (obshtina: string): Promise<FundsGeoFile | null> => {
  const r = await fetch(
    dataUrl(`/funds/projects/by-muni-geo/${obshtina}.json`),
  );
  if (r.status === 404) return null;
  if (!r.ok) throw new Error(`funds geo fetch failed: ${r.status}`);
  return r.json();
};

export const useFundsGeoPins = (obshtina?: string | null) => {
  const { data } = useQuery({
    queryKey: ["funds", "geo", obshtina ?? ""],
    queryFn: () => (obshtina ? fetchGeo(obshtina) : Promise.resolve(null)),
    enabled: !!obshtina,
    staleTime: Infinity,
  });
  return data;
};
