// Slim per-município geo pins for EU-funded projects. Generated by
// scripts/funds/build_geo_pins.ts from the heavy per-município corpus —
// the SPA fetches just the trimmed map-ready slice (max 200 pins,
// largest-totalEur-first per município) so the Leaflet tile loads in
// milliseconds even for big municipalities.

import { useQuery } from "@tanstack/react-query";
import { fetchFundPayload } from "./fetchFundPayload";

export type FundsGeoContract = {
  contractNumber: string;
  title: string;
  totalEur: number;
  status: string;
  programName?: string;
  // Present only for contracts that resolved to a settlement centroid.
  ekatte?: string;
  lat?: number;
  lon?: number;
};

// A contract that carries coordinates — safe to render as a map pin.
export type FundsGeoPin = FundsGeoContract & { lat: number; lon: number };

export type FundsGeoFile = {
  obshtina: string;
  generatedAt: string;
  // Total contracts in the município (honest headline count; `contracts` is capped).
  sourceContractCount: number;
  // How many contracts resolved to a location (and can be a map pin).
  geocodedCount: number;
  // Top-N by money — geocoded and non-geocoded together.
  contracts: FundsGeoContract[];
};

const fetchGeo = (obshtina: string): Promise<FundsGeoFile | null> =>
  fetchFundPayload<FundsGeoFile>("geo", obshtina);

export const useFundsGeoPins = (obshtina?: string | null) => {
  const { data } = useQuery({
    queryKey: ["funds", "geo", obshtina ?? ""],
    queryFn: () => (obshtina ? fetchGeo(obshtina) : Promise.resolve(null)),
    enabled: !!obshtina,
    staleTime: Infinity,
  });
  return data;
};
