import { Card, CardContent } from "@/ux/Card";
import { SEO } from "@/ux/SEO";
import { H1 } from "@/ux/H1";
import { Anchor } from "@/ux/Anchor";
import { Link } from "react-router-dom";
import { useTranslation } from "react-i18next";

const linkClass =
  "text-accent underline underline-offset-4 decoration-accent/40 hover:decoration-accent transition-colors";

const SectionHeading: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => (
  <h2 className="font-display text-2xl md:text-3xl font-bold tracking-tight text-foreground">
    {children}
  </h2>
);

export const AboutScreen = () => {
  const { t } = useTranslation();
  return (
    <div className="text-foreground w-full">
      <SEO title={t("about")} description="About page" />
      <article className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 py-8 md:py-16">
        {/* Hero */}
        <header className="mb-12 md:mb-16">
          <H1 className="text-4xl md:text-5xl lg:text-6xl text-left py-0 mb-8 md:mb-10 text-foreground">
            {t("about")}
          </H1>
          <p className="text-lg md:text-xl leading-relaxed text-muted-foreground">
            {t("about_p_1")}
          </p>
          <div className="mt-8 space-y-6">
            <blockquote className="border-l-4 border-accent pl-5 md:pl-6 text-lg md:text-xl italic font-medium leading-relaxed text-foreground">
              {t("about_p_2")}
            </blockquote>
            <blockquote className="border-l-4 border-accent pl-5 md:pl-6 text-lg md:text-xl italic font-medium leading-relaxed text-foreground">
              {t("about_p_3")}
            </blockquote>
          </div>
          <p className="mt-8 text-lg md:text-xl leading-relaxed text-muted-foreground">
            {t("about_p_4")}
          </p>
          {/* My-Area feature mention — sits at the bottom of the hero so
              visitors who scan only the top of the page still learn it
              exists. The "сниперът" sniper icon and pill in the header are
              both wired to /my-area; this paragraph explains the input
              affordances (search vs geolocation) in plain language. */}
          <p className="mt-8 text-base md:text-lg leading-relaxed text-muted-foreground">
            {t("about_my_area")}
          </p>
        </header>

        {/* AI chat — the standalone "Наясно AI" assistant at
            ai.electionsbg.com. Its selling point is honesty: every figure it
            returns is computed from this platform's data, not generated by the
            language model. External link (separate Firebase hosting target). */}
        <section className="mb-12 md:mb-16">
          <SectionHeading>{t("about_ai_title")}</SectionHeading>
          <p className="mt-4 text-base md:text-lg leading-relaxed text-muted-foreground">
            {t("about_ai")}
          </p>
          <p className="mt-6 text-base md:text-lg leading-relaxed text-muted-foreground">
            <Anchor
              href="https://ai.electionsbg.com"
              target="_blank"
              rel="noreferrer"
              className={linkClass}
            >
              {t("about_ai_link")}
            </Anchor>
          </p>
        </section>

        {/* Team */}
        <section className="mb-12 md:mb-16">
          <SectionHeading>{t("whos_behind_the_project")}</SectionHeading>
          <p className="mt-4 text-base md:text-lg leading-relaxed text-muted-foreground">
            {t("project_about")}
          </p>
          <div className="mt-8 grid grid-cols-1 md:grid-cols-2 gap-6">
            <ProfileCard
              name={t("martin_stoyanov")}
              location={t("martin_location")}
              image="/images/IMG_2272.png"
              bio={t("martin_about")}
              experienceLabel={t("experience")}
              experience={t("martin_experience")}
              hobbiesLabel={t("hobbies")}
              hobbies={t("martin_hobbies")}
            />
            <ProfileCard
              name={t("atanas_stoyanov")}
              location={t("atanas_location")}
              image="/images/IMG_4016.png"
              bio={
                <>
                  {t("atanas_about")}{" "}
                  <Anchor
                    target="_blank"
                    rel="noreferrer"
                    href="https://smartbear.com"
                    className={linkClass}
                  >
                    AutomatedQA.
                  </Anchor>
                </>
              }
              experienceLabel={t("experience")}
              experience={t("atanas_experience")}
              hobbiesLabel={t("hobbies")}
              hobbies={t("atanas_hobbies")}
            />
          </div>
        </section>

        {/* Data sources — the full source registry + download links now live
            on the dedicated sources page (/data/sources). */}
        <section>
          <SectionHeading>{t("the_data")}</SectionHeading>
          <p className="mt-4 text-base md:text-lg leading-relaxed text-muted-foreground">
            {t("about_data")}
          </p>
          <p className="mt-6 text-base md:text-lg leading-relaxed text-muted-foreground">
            <Link to="/data/sources" className={linkClass}>
              {t("about_data_sources_link")}
            </Link>
          </p>
        </section>
      </article>
    </div>
  );
};

const ProfileCard: React.FC<{
  name: string;
  location: string;
  image: string;
  bio: React.ReactNode;
  experienceLabel: string;
  experience: string;
  hobbiesLabel: string;
  hobbies: string;
}> = ({
  name,
  location,
  image,
  bio,
  experienceLabel,
  experience,
  hobbiesLabel,
  hobbies,
}) => (
  <Card className="overflow-hidden">
    <CardContent className="p-6 pt-6">
      <div className="flex flex-col items-center text-center">
        <img
          className="h-32 w-32 rounded-full object-cover ring-2 ring-border"
          src={image}
          alt={name}
        />
        <h3 className="mt-4 font-display text-xl md:text-2xl font-bold text-foreground">
          {name}
        </h3>
        <p className="text-sm font-medium text-muted-foreground">{location}</p>
      </div>
      <div className="mt-6 space-y-4 text-sm md:text-base leading-relaxed text-muted-foreground">
        <p>{bio}</p>
        <div>
          <h4 className="text-xs uppercase tracking-wider font-semibold text-foreground/70">
            {experienceLabel}
          </h4>
          <p className="mt-1">{experience}</p>
        </div>
        <div>
          <h4 className="text-xs uppercase tracking-wider font-semibold text-foreground/70">
            {hobbiesLabel}
          </h4>
          <p className="mt-1">{hobbies}</p>
        </div>
      </div>
    </CardContent>
  </Card>
);
