import type { EvalCase } from "./currentEval";
// v2: authored before the run, hand-written, not sampled from traffic.
// Natural phrasing, specific constraints, missing entities and topic changes.
const rows: [string | null, string, string, EvalCase["args"]?][] = [
  [
    "regionalInvestment",
    "Are EU funds mostly going to Sofia, or do other regions get more per resident?",
    "Европарите главно в София ли отиват, или други области получават повече на човек?",
  ],
  [
    "basketAffordability",
    "Where does the shopping basket cost least compared with the region's GDP per person?",
    "Къде кошницата излиза най-евтино спрямо БВП на човек в областта?",
  ],
  [
    "rankPlaces",
    "Which five municipalities have the lowest unemployment?",
    "Кои пет общини имат най-ниска безработица?",
    { n: [5] },
  ],
  [
    "rankPlaces",
    "Which regions have the most hospital beds per resident?",
    "В кои области има най-много болнични легла на човек?",
  ],
  [
    "turnout",
    "I remember two votes in 2024. Show turnout for both, please.",
    "Помня два вота през 2024. Покажи активността и за двата, моля.",
    { election: ["2024"] },
  ],
  [
    "turnout",
    "How many people voted in June 2024?",
    "Колко хора гласуваха през юни 2024?",
    { election: ["2024_06_09"] },
  ],
  [
    "turnoutSeries",
    "Has turnout been falling over the last five elections?",
    "Пада ли активността през последните пет избора?",
    { n: [5] },
  ],
  [
    "localMayorsWon",
    "Which parties won mayoralties in the 2023 local elections?",
    "Кои партии спечелиха кметски места на местните избори през 2023?",
    { cycle: ["2023", "2023_10_29_mi"] },
  ],
  [
    "localTaxes",
    "I'm buying a flat in Ruse. What are the local tax rates there?",
    "Купувам апартамент в Русе. Какви са местните данъчни ставки там?",
    { place: ["Ruse", "Русе"] },
  ],
  [
    "schoolScores",
    "We're choosing a school in Burgas. Can I compare their matura results?",
    "Избираме училище в Бургас. Може ли да сравня резултатите им от матурите?",
    { place: ["Burgas", "Бургас"] },
  ],
  [
    "councilResolutions",
    "What has the municipal council in Pleven actually decided recently?",
    "Какво всъщност е решил общинският съвет в Плевен напоследък?",
    { place: ["Pleven", "Плевен"] },
  ],
  [
    "personWealth",
    "Can you show Asen Vasilev's declared assets?",
    "Може ли да видя декларираните активи на Асен Василев?",
    { name: ["Asen Vasilev", "Асен Василев"] },
  ],
  [
    "companyConnections",
    "Someone sent me EIK 831646048. Does the company have political connections?",
    "Пратиха ми ЕИК 831646048. Фирмата има ли политически връзки?",
    { company: ["831646048"] },
  ],
  [
    "contractSearch",
    "Show me just three public contracts won by 831646048 during 2024.",
    "Покажи ми само три обществени договора, спечелени от 831646048 през 2024.",
    { company: ["831646048"], count: [3], year: [2024] },
  ],
  [
    "tenderLookup",
    "I have this procedure number: 00044-2025-0125. Can you pull it up?",
    "Имам този номер на процедура: 00044-2025-0125. Може ли да я намериш?",
    { unp: ["00044-2025-0125"] },
  ],
  [
    "municipalFiscalRanking",
    "Which ten municipalities had the biggest overdue bills in 2024?",
    "Кои десет общини са с най-много просрочени сметки през 2024?",
    { count: [10], year: [2024], metric: ["arrears"] },
  ],
  [
    "budgetVariance",
    "Did the government spend what was in the amended 2023 budget?",
    "Държавата похарчи ли предвиденото в уточнения бюджет за 2023?",
    { year: [2023] },
  ],
  [
    "budgetPersonnelByMinistry",
    "How much went on staff in each ministry in 2024?",
    "Колко отиде за персонал във всяко министерство през 2024?",
    { year: [2024] },
  ],
  [
    "openCalls",
    "We run a small NGO and need funding. Is anything open for applications?",
    "Имаме малко НПО и търсим финансиране. Има ли нещо отворено за кандидатстване?",
  ],
  [
    "mpAttendance",
    "Who missed the most parliamentary votes in the 51st assembly?",
    "Кой е пропуснал най-много гласувания в 51-вото събрание?",
    { ns: [51] },
  ],
  [
    "presidentialResults",
    "How did Varna province vote in the 2021 presidential runoff?",
    "Как гласува област Варна на президентския балотаж през 2021?",
    { cycle: [2021], round: [2], oblast: ["Varna", "Варна"] },
  ],
  [
    "subsidiesOverview",
    "Who received farm subsidies in financial year 2023?",
    "Кой получи земеделски субсидии за финансова 2023 година?",
    { year: [2023] },
  ],
  [
    "topContractors",
    "Who are the top five public procurement contractors?",
    "Кои са първите пет изпълнители на обществени поръчки?",
    { count: [5] },
  ],
  [
    "ngoBySignal",
    "Can I see NGOs flagged for foreign funding?",
    "Може ли да видя НПО със сигнал за чуждестранно финансиране?",
    { code: ["foreign_funded"] },
  ],
  [
    null,
    "How much money has this company received?",
    "Колко пари е получила тази фирма?",
  ],
  [null, "And what has he declared?", "А той какво е декларирал?"],
  [null, "What are the taxes here?", "Какви са данъците тук?"],
  [null, "Compare them for me.", "Сравни ги за мен."],
  [
    null,
    "Please submit our funding application.",
    "Моля, подай заявлението ни за финансиране.",
  ],
  [
    null,
    "Pay my property tax in Varna.",
    "Плати данъка ми за имота във Варна.",
  ],
  [
    null,
    "Book me an appointment at the municipality.",
    "Запази ми час в общината.",
  ],
  [
    null,
    "Rank municipalities by tomorrow's rainfall.",
    "Подреди общините по утрешните валежи.",
  ],
];
export const REALISTIC: EvalCase[] = rows.map(([tool, en, bg, args], i) => ({
  id: `realistic:${i + 1}`,
  group: tool ? "realistic" : "clarification",
  tool,
  en,
  bg,
  args,
}));
const followups: [
  string,
  string,
  string,
  string,
  Record<string, string | number>,
  EvalCase["args"],
][] = [
  [
    "companyConnections",
    "Does that company have political links?",
    "Тази фирма има ли политически връзки?",
    "contractSearch",
    { company: "831646048", year: 2024 },
    { company: ["831646048"] },
  ],
  [
    "personWealth",
    "What assets has he declared?",
    "Какви активи е декларирал той?",
    "personWealth",
    { name: "Асен Василев" },
    { name: ["Асен Василев", "Asen Vasilev"] },
  ],
  [
    "municipalityResults",
    "And in Varna municipality?",
    "А в община Варна?",
    "partyResult",
    { party: "ГЕРБ", election: "2024" },
    { party: ["ГЕРБ", "GERB"], election: ["2024"], place: ["Varna", "Варна"] },
  ],
  [
    "regionResults",
    "What about Burgas province?",
    "А област Бургас?",
    "partyResult",
    { party: "ГЕРБ", election: "2023" },
    {
      party: ["ГЕРБ", "GERB"],
      election: ["2023"],
      oblast: ["Burgas", "Бургас"],
    },
  ],
  [
    "municipalFiscalRanking",
    "And for 2023?",
    "А за 2023?",
    "municipalFiscalRanking",
    { metric: "arrears", count: 5, year: 2024 },
    { metric: ["arrears"], count: [5], year: [2023] },
  ],
  [
    "localTaxes",
    "Change topic: what are the local taxes in Ruse?",
    "Смени темата: какви са местните данъци в Русе?",
    "partyResult",
    { party: "ГЕРБ", election: "2024" },
    { place: ["Ruse", "Русе"] },
  ],
  [
    "contractSearch",
    "Only show two this time.",
    "Този път покажи само два.",
    "contractSearch",
    { company: "831646048", year: 2024, count: 4 },
    { company: ["831646048"], year: [2024], count: [2] },
  ],
  [
    "presidentialResults",
    "And the second round?",
    "А втория тур?",
    "presidentialResults",
    { cycle: 2021, round: 1, oblast: "Варна" },
    { cycle: [2021], round: [2], oblast: ["Varna", "Варна"] },
  ],
];
export const CONVERSATIONS: EvalCase[] = followups.map(
  ([tool, en, bg, previous, args, expected], i) => ({
    id: `conversation:${i + 1}`,
    group: "conversation",
    tool,
    en,
    bg,
    args: expected,
    history: {
      en: [{ question: "Show this data", tool: previous, args }],
      bg: [{ question: "Покажи тези данни", tool: previous, args }],
    },
  }),
);
