// Build /public/llms.txt — the short overview that AI / LLM crawlers fetch
// first. Most sections are hand-authored constants; "Featured analyses" is
// generated from /public/articles/index.json so a newly published article
// shows up here automatically, without an extra hand-edit step.
//
// The companion /public/llms-full.txt and /public/llms-full.en.txt corpora
// are generated by ./buildFull.ts; the entries below link to them.

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, "../..");
const PUBLIC = path.join(PROJECT_ROOT, "public");
const SITE_URL = "https://electionsbg.com";

type ArticleMeta = {
  slug: string;
  election?: string;
  publishedAt: string;
  category?: string;
  topics?: string[];
  title: { bg: string; en: string };
  summary: { bg: string; en: string };
  /** Editorial draft — kept out of the llms index, prerender, and sitemap.
   *  Drafts only surface on the Vite dev server. */
  draft?: boolean;
};

const KEY_URLS: Array<{ url: string; label: string; description: string }> = [
  {
    url: "/",
    label: "Home",
    description: "overview, latest election headline, dashboard tiles",
  },
  {
    url: "/about",
    label: "About",
    description: "methodology, data sources, team",
  },
  {
    url: "/articles",
    label: "Articles",
    description:
      "long-form analytical pieces; each article also available as raw Markdown at `/articles/{slug}-bg.md` and `/articles/{slug}-en.md`",
  },

  // Election + party browsing
  {
    url: "/elections",
    label: "Elections",
    description:
      "every parliamentary vote from 2005 with national + regional drill-down",
  },
  {
    url: "/parties",
    label: "Parties",
    description: "full party list for the latest vote, votes / share / seats",
  },
  {
    url: "/regions",
    label: "Regions (28 MIR)",
    description: "results across the 28 multi-member districts",
  },
  {
    url: "/sofia",
    label: "Sofia",
    description: "Sofia-only view across MIR 23/24/25",
  },
  {
    url: "/compare",
    label: "Compare",
    description: "side-by-side comparison of any two parliamentary votes",
  },
  {
    url: "/timeline",
    label: "Timeline",
    description: "bubble-timeline of every party's share across all 13 votes",
  },
  {
    url: "/simulator",
    label: "Simulator",
    description: "coalition + seat-allocation what-if tool",
  },
  {
    url: "/polls",
    label: "Polls",
    description: "polling-agency accuracy tracker, per-vote miss profile",
  },

  // Government + parliament dashboards
  {
    url: "/governance",
    label: "Governance",
    description:
      "country node of the Governance view — parliament roll-calls, MP declarations, state budget execution, public procurement, party financing and macro/governance context; also the top of a place ladder that drills country → region (/governance/region/{oblast}) → município or settlement (/governance/{id}) for the local governance picture (the place's MPs, mayor & council, Чл.53 transfers, EU funds, local taxes, census, transparency)",
  },
  {
    url: "/parliament",
    label: "Parliament",
    description: "MP roster, party seats, per-MP profiles",
  },
  {
    url: "/parliament/cohesion",
    label: "Parliament cohesion",
    description: "intra- and cross-party roll-call cohesion",
  },
  {
    url: "/parliament/embedding",
    label: "Parliament embedding",
    description: "2-D embedding of MPs from roll-call voting behavior",
  },
  {
    url: "/connections",
    label: "MP business connections",
    description: "graph of declared business ties between MPs and companies",
  },
  {
    url: "/mp-assets",
    label: "MP assets",
    description: "declared net-worth rankings (property, vehicles, holdings)",
  },
  {
    url: "/mp-cars",
    label: "MP cars",
    description: "declared vehicles, ranked by value with typo guards",
  },
  {
    url: "/officials",
    label: "Officials declarations",
    description:
      "cabinet members, deputy ministers, agency heads, regional governors",
  },

  // Fiscal + procurement
  {
    url: "/budget",
    label: "State budget",
    description:
      "consolidated execution, ministry-by-ministry plan vs actual, COFOG breakdown, EU peer comparison",
  },
  {
    url: "/procurement",
    label: "Public procurement",
    description:
      "all АОП contracts since the dataset starts, debarred-supplier flags, MP-connection cross-reference",
  },
  {
    url: "/procurement/by-settlement",
    label: "Procurement by settlement",
    description:
      "per-settlement procurement totals — every contract pinned to the buyer's HQ address (municipalities, schools, hospitals, universities, regional offices, utilities) with central ministries / national state companies aggregated into a separate 'national procurement' rollup; ~388 settlements with €36 B in local-tier contracts",
  },
  {
    url: "/financing",
    label: "Party financing",
    description: "declared campaign income and expenditures from Сметна палата",
  },
  {
    url: "/indicators",
    label: "Macro & governance indicators",
    description:
      "KPI dashboard of Bulgaria's macro/fiscal/governance/social indicators since 2005, with EU27 rank, YoY arrows and cabinet-shaded sparklines; domain sub-pages at /indicators/economy, /indicators/fiscal, /indicators/governance, /indicators/society; multi-panel EU peer comparison dashboard at /indicators/compare (WGI radar, COFOG budget composition, SILC inequality, spend-vs-outcome scatters)",
  },

  // Anomalies + integrity
  {
    url: "/risk-analysis",
    label: "Risk analysis",
    description:
      "composite electoral-risk index across 5 process signals + 4 context signals",
  },

  // Machine-readable
  {
    url: "/sitemap_index.xml",
    label: "Sitemap index",
    description: "index of per-bucket sitemaps (~78,000 URLs total)",
  },
  {
    url: "/llms-full.txt",
    label: "Full corpus (BG)",
    description:
      "national summary, per-party retrospect, polling analysis, and full article texts — Bulgarian",
  },
  {
    url: "/llms-full.en.txt",
    label: "Full corpus (EN)",
    description: "same content, English",
  },
];

const URL_PATTERNS: string[] = [
  "`/party/{nickName}` — results for a specific party across years and territories. Sub-paths: `/regions`, `/municipalities`, `/settlements`, `/preferences`, `/donors`, `/income`, `/expenses`.",
  "`/municipality/{oblastCode}` — oblast-level results and per-section anomalies.",
  "`/settlement/{ekatte}` — settlement-level results by section.",
  "`/governance/region/{oblastCode}` — region (oblast) node of the Governance view: the area's MPs and declarations, the Чл.53 transfer envelope, regional indicators, census and land-use.",
  "`/governance/{id}` — place node of the Governance view, where `{id}` is an obshtina code (município) or EKATTE (settlement): everything about how that place is governed — representation, mayor & council, municipal budget and capital programme, EU-funded projects, procurement, local taxes, census, transparency (LISI) and quality-of-life.",
  "`/section/{sectionId}` — individual polling-section detail.",
  "`/candidate/{name}` — candidate profile with sub-paths `/regions`, `/municipalities`, `/settlements`, `/sections`, `/donations`, `/connections`, `/assets`.",
  "`/elections/{YYYY_MM_DD}` — landing for one parliamentary vote (national + regional).",
  "`/reports/{level}/{metric}` — analytical reports (turnout, concentration, gainers/losers, invalid ballots, additional voters, supports-no-one, problem sections) at municipality, settlement, or section level.",
  "`/articles/{slug}` — long-form analytical articles. Each article is also available as raw Markdown at `/articles/{slug}-bg.md` and `/articles/{slug}-en.md` for direct LLM ingestion.",
  "`/en/...` — every BG URL has an English mirror under `/en/`; both variants declare bidirectional `hreflang` alternates.",
];

const buildFeaturedAnalyses = (): string[] => {
  const indexFile = path.join(PUBLIC, "articles", "index.json");
  if (!fs.existsSync(indexFile)) return [];
  let articles: ArticleMeta[];
  try {
    articles = JSON.parse(fs.readFileSync(indexFile, "utf-8"));
  } catch {
    return [];
  }
  if (!Array.isArray(articles) || !articles.length) return [];
  const sorted = [...articles]
    .filter((a) => a?.slug && a.title?.en && a.title?.bg && !a.draft)
    .sort((a, b) => (b.publishedAt || "").localeCompare(a.publishedAt || ""));
  return sorted.map((a) => {
    const enUrl = `${SITE_URL}/en/articles/${a.slug}`;
    const bgUrl = `${SITE_URL}/articles/${a.slug}`;
    const mdEnUrl = `${SITE_URL}/articles/${a.slug}-en.md`;
    const mdBgUrl = `${SITE_URL}/articles/${a.slug}-bg.md`;
    const summary = a.summary?.en ?? a.summary?.bg ?? "";
    return `- [${a.title.en}](${enUrl}) (English) / [${a.title.bg}](${bgUrl}) (Bulgarian) — ${summary} Markdown: [${a.slug}-en.md](${mdEnUrl}) · [${a.slug}-bg.md](${mdBgUrl}).`;
  });
};

const buildLlmsTxt = (): string => {
  const lines: string[] = [];
  lines.push(`# Elections Bulgaria — electionsbg.com`);
  lines.push("");
  lines.push(
    `> Open-source platform for visualizing and analyzing every Bulgarian parliamentary election since 2005 — broken down by region (oblast), municipality (obshtina), settlement, and polling section — plus dashboards for the resulting parliament, the state budget, public procurement, MP business connections and declared assets, polling-agency accuracy, and an electoral-risk screening index. Source data comes from the Central Election Commission (ЦИК), Sofia's Сметна палата (campaign finance + assets), parliament.bg, Eurostat, World Bank WGI, the Bulgarian Court of Audit and АОП. Everything is reprocessed offline into static JSON served from a JAMstack SPA.`,
  );
  lines.push("");
  lines.push(
    `Site language: primary Bulgarian, with full English UI translation. Every page is prerendered into static HTML at build time, so non-JS crawlers see the real content. All data is public-domain; the site is open source.`,
  );
  lines.push("");

  lines.push(`## What this site contains`);
  lines.push("");
  lines.push(
    `- Per-election results for all 13 parliamentary votes from 2005 onward, including the early-election cycles of 2021–2026.`,
  );
  lines.push(
    `- Geographic drill-down: 28 МИР (multi-member districts) → 265 municipalities → ~5,300 settlements → ~12,000 polling sections.`,
  );
  lines.push(
    `- Machine-vote vs. paper-vote breakdowns, recount metrics, invalid-ballot rates, and section-level anomaly detection.`,
  );
  lines.push(
    `- Per-party results across time (rise-and-fall timeline), declared campaign financing, and donor lists.`,
  );
  lines.push(
    `- Parliament dashboards: roll-call cohesion, MP business-connection graph (Commerce Registry crossed with declarations), declared assets/cars rankings.`,
  );
  lines.push(
    `- State budget execution (КФП + ministry "Отчет за изпълнението на програмния бюджет"), public procurement (АОП contracts, debarred-supplier register), regional indicators (Eurostat NUTS-3, unemployment, education).`,
  );
  lines.push(
    `- Composite electoral-risk index and interactive simulator for coalition formation and seat allocation.`,
  );
  lines.push("");

  lines.push(`## Key URLs`);
  lines.push("");
  for (const k of KEY_URLS) {
    lines.push(`- [${k.label}](${SITE_URL}${k.url}): ${k.description}.`);
  }
  lines.push("");

  const featured = buildFeaturedAnalyses();
  if (featured.length) {
    lines.push(`## Featured analyses`);
    lines.push("");
    lines.push(
      `> All long-form analytical articles, most recent first. Each is published in Bulgarian and English with a raw-Markdown URL for direct ingestion.`,
    );
    lines.push("");
    for (const f of featured) lines.push(f);
    lines.push("");
  }

  lines.push(`## URL patterns`);
  lines.push("");
  for (const p of URL_PATTERNS) lines.push(`- ${p}`);
  lines.push("");

  lines.push(`## Data`);
  lines.push("");
  lines.push(
    `Raw inputs are CSV/ZIP/HTML releases from the Central Election Commission (ЦИК), Сметна палата, parliament.bg, data.egov.bg (АОП procurement, budget execution), Eurostat, World Bank WGI, and the Bulgarian Court of Audit. The offline pipeline in \`/scripts/\` transforms them into static JSON; per-election artifacts live in a GCS bucket (\`storage.googleapis.com/data-electionsbg-com\`) and the site fetches them via React Query.`,
  );
  lines.push("");

  lines.push(`## Citation`);
  lines.push("");
  lines.push(
    `If you cite results or visualizations from this site, please link to the specific page (e.g. the settlement, party, or article URL) and credit "electionsbg.com". The source code lives at https://github.com/atanasster/data-bg.`,
  );
  lines.push("");

  lines.push(`## Contact`);
  lines.push("");
  lines.push(`Questions or corrections: see the About page.`);
  lines.push("");

  return lines.join("\n");
};

const writeOutput = (filename: string, content: string) => {
  fs.writeFileSync(path.join(PUBLIC, filename), content, "utf-8");
  const dist = path.join(PROJECT_ROOT, "dist");
  if (fs.existsSync(dist)) {
    fs.writeFileSync(path.join(dist, filename), content, "utf-8");
  }
  console.log(
    `${filename}: ${Buffer.byteLength(content, "utf-8")} bytes, ${content.split("\n").length} lines`,
  );
};

writeOutput("llms.txt", buildLlmsTxt());
