#!/usr/bin/env python3
"""Contrastively fine-tune multilingual-e5-small on the Наясно tool registry so a
SMALL (~45 MB q8) in-browser embedder rivals generic e5-base (~110 MB) on tool
retrieval. See ai/m0/finetune_functiongemma.md (embedder fine-tune).

Data (generated by the TS scripts, held out from each other):
  train_queries.json  — TRAINING queries per tool (gen_train_data.ts)
  recall_export.json  — EVAL: {docs:[{name,text}], queries:[{tool,lang,query,declined}]}
                        (the SAME held-out eval set measure_recall_semantic.ts used)

Pairs: (("query: "+q), ("passage: "+doc_of_its_tool)) with in-batch negatives (MNR).
Reports held-out recall (all + rules-declined residual) BEFORE and AFTER, so the
lift is provable, then saves the model. ONNX export for transformers.js is a
separate step (see the README note printed at the end).

  ai/m0/.venv/bin/python ai/m0/finetune/finetune_embedder.py --epochs 4 --batch 32
"""
import argparse, json, os
from pathlib import Path

import torch
from sentence_transformers import SentenceTransformer, InputExample, losses
from sentence_transformers.datasets import NoDuplicatesDataLoader

HERE = Path(__file__).resolve().parent
BASE = "intfloat/multilingual-e5-small"
KS = [1, 3, 5, 8]


def load():
    train = json.loads((HERE / "train_queries.json").read_text())
    exp = json.loads((HERE / "recall_export.json").read_text())
    doc_text = {d["name"]: d["text"] for d in exp["docs"]}
    return train, exp["queries"], doc_text


def eval_recall(model, queries, doc_text, device):
    names = list(doc_text)
    doc_emb = model.encode(
        ["passage: " + doc_text[n] for n in names],
        normalize_embeddings=True, convert_to_tensor=True, device=device, batch_size=64,
    )
    q_emb = model.encode(
        ["query: " + q["query"] for q in queries],
        normalize_embeddings=True, convert_to_tensor=True, device=device, batch_size=64,
    )
    sims = q_emb @ doc_emb.T  # cosine (both normalized)
    order = torch.argsort(sims, dim=1, descending=True).cpu().tolist()
    idx = {n: i for i, n in enumerate(names)}

    def tally(subset):
        hit = {k: 0 for k in KS}
        for qi in subset:
            tool_i = idx[queries[qi]["tool"]]
            rank = order[qi].index(tool_i)
            for k in KS:
                if rank < k:
                    hit[k] += 1
        n = len(subset) or 1
        return {k: hit[k] / n for k in KS}

    all_i = range(len(queries))
    decl_i = [i for i, q in enumerate(queries) if q["declined"]]
    return tally(all_i), tally(decl_i), len(decl_i)


def show(label, allr, declr, ndecl):
    f = lambda r: "  ".join(f"@{k} {r[k]*100:5.1f}%" for k in KS)
    print(f"  {label:8} all      {f(allr)}")
    print(f"  {'':8} declined {f(declr)}   (n={ndecl})")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--epochs", type=int, default=4)
    ap.add_argument("--batch", type=int, default=32)
    ap.add_argument("--lr", type=float, default=2e-5)
    ap.add_argument("--out", default=str(HERE / "e5-small-naiasno"))
    args = ap.parse_args()

    device = "mps" if torch.backends.mps.is_available() else ("cuda" if torch.cuda.is_available() else "cpu")
    print(f"device={device}  base={BASE}")
    train, eval_q, doc_text = load()

    pairs = []
    for tool, q in train.items():
        if tool not in doc_text:
            continue
        for s in q.get("en", []) + q.get("bg", []):
            pairs.append(InputExample(texts=["query: " + s, "passage: " + doc_text[tool]]))
    print(f"{len(pairs)} training pairs | {len(eval_q)} eval queries | {len(doc_text)} tools")

    model = SentenceTransformer(BASE, device=device)

    print("\n=== BEFORE fine-tune ===")
    a0, d0, nd = eval_recall(model, eval_q, doc_text, device)
    show("base", a0, d0, nd)

    loader = NoDuplicatesDataLoader(pairs, batch_size=args.batch)
    loss = losses.MultipleNegativesRankingLoss(model)
    warmup = int(len(loader) * args.epochs * 0.1)
    print(f"\ntraining: {args.epochs} epochs, batch {args.batch}, {len(loader)} steps/epoch, warmup {warmup}")
    model.fit(
        train_objectives=[(loader, loss)],
        epochs=args.epochs,
        warmup_steps=warmup,
        optimizer_params={"lr": args.lr},
        show_progress_bar=True,
    )

    print("\n=== AFTER fine-tune ===")
    a1, d1, _ = eval_recall(model, eval_q, doc_text, device)
    show("tuned", a1, d1, nd)
    print("\n  reference — e5-base(generic) declined @5 79% @8 87% | gemini-embedding-001 @5 92% @8 95%")
    print(f"  delta declined @8: {(d1[8]-d0[8])*100:+.1f}pt")

    os.makedirs(args.out, exist_ok=True)
    model.save(args.out)
    print(f"\nsaved → {args.out}")
    print("ONNX export for transformers.js (separate step):")
    print(f"  optimum-cli export onnx -m {args.out} --task feature-extraction {args.out}/onnx")
    print("  then quantize q8 + host as a public HF repo; point EMBED_MODEL at it.")


if __name__ == "__main__":
    main()
