#!/usr/bin/env node
// One-shot: download Inter + Fraunces from Google Fonts, store woff2 locally,
// and write a self-contained CSS file so we can drop the render-blocking
// fonts.googleapis.com / fonts.gstatic.com requests.
//
// Why: Google Fonts CSS is render-blocking and adds ~250 ms FCP. Self-hosting
// puts everything on the same origin (electionsbg.com), eliminates two extra
// origins from the critical path, and lets us preload only the BG/EN subsets
// we actually use.
//
// Re-run: occasionally to pull updated revisions of the Google CSS (font
// files don't change often). The script is idempotent — it overwrites the
// existing files. Commit the result.
//
// Output: /public/fonts/{...}.woff2  +  /public/fonts/fonts.css

import { writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, "../../public/fonts");

// Asking Google for its CSS with a recent Chrome UA forces it to return the
// woff2 declarations rather than the older woff/ttf fallback.
const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Fraunces:opsz,wght@9..144,400..700&display=swap";
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36";

mkdirSync(OUT_DIR, { recursive: true });

console.log(`Fetching CSS from Google Fonts...`);
const cssRes = await fetch(CSS_URL, { headers: { "User-Agent": UA } });
if (!cssRes.ok) {
  console.error(`CSS fetch failed: ${cssRes.status}`);
  process.exit(1);
}
let css = await cssRes.text();

// Match every gstatic woff2 URL in the CSS
const urlRe = /https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2/g;
const urls = Array.from(new Set(css.match(urlRe) ?? []));
console.log(`Found ${urls.length} woff2 files to download.`);

let downloaded = 0;
let bytes = 0;
for (const url of urls) {
  // Build a deterministic local filename from the path tail. e.g.
  // .../inter/v20/UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa1ZL7W0Q5nw.woff2
  // → inter-v20-UcC73FwrK...woff2
  const tail = url.replace("https://fonts.gstatic.com/s/", "").replace(/\//g, "-");
  const localPath = path.join(OUT_DIR, tail);
  const localUrl = `/fonts/${tail}`;

  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) {
    console.error(`  ✗ ${url}  (${res.status})`);
    continue;
  }
  const buf = Buffer.from(await res.arrayBuffer());
  writeFileSync(localPath, buf);
  downloaded++;
  bytes += buf.length;
  // Rewrite every occurrence of this URL in the CSS to the local one
  css = css.split(url).join(localUrl);
}

console.log(`  ✓ ${downloaded}/${urls.length} files, ${(bytes / 1024).toFixed(0)} KB`);

// Add a header comment so the source isn't mysterious
const header = `/*
 * Self-hosted Google Fonts (Inter + Fraunces).
 *
 * Generated by scripts/fonts/fetch-fonts.mjs — do not edit by hand. Re-run
 * the script to refresh. Google Fonts CSS is render-blocking and lives on a
 * second origin; this file replaces the network round-trip with a local
 * stylesheet served by Firebase Hosting (same origin, gzipped, immutable).
 */

`;

writeFileSync(path.join(OUT_DIR, "fonts.css"), header + css);
console.log(`✓ wrote ${OUT_DIR}/fonts.css  (${(css.length / 1024).toFixed(1)} KB)`);
