// `data/home/flyover.json` must be the corpus it claims to be — plan §11.1.
//
// The artifact is COMMITTED and bucket-served, so every number in it is a claim published at a
// 200 long after the corpus underneath it has moved. Nothing at request time can notice: there
// is no live query to disagree with. So this gate re-counts every layer, every cell of the flow
// matrix and every coverage bucket directly against Postgres.
//
// Three things it deliberately does NOT do:
//
//   - it never sums the three money layers. They are three TAPS over overlapping corpora (an
//     ИСУН-funded contract is in `fund_projects` AND `contracts`), so their sum is a quantity
//     with no name, and a gate that computed one would license a caption to publish it;
//   - it does not require the elections layer. `data/<date>/region_votes.json` is gitignored,
//     so a fresh clone legitimately has none — `available.elections` is the assertion;
//   - it does not „reconcile" the three procurement bases. €94.12bn (corpus), €93.91bn (the
//     hub-stats tile) and €93.18bn (buyer-placed) are three different questions, and the gate
//     pins the DISTANCE between them rather than their equality.
//
// Auto-skips when Postgres is down or the contracts corpus is empty.
//
//   npm run test:data

import { test, afterAll } from "vitest";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { allRows, dbReachable, end } from "../lib/pg";
import { reportSkip } from "../../lib/report_skip";
import { assertCommitted } from "../../lib/assert_committed";
import {
  MAX_BYTES,
  buildArtifact,
  type FlyoverArtifactV1,
  PARTITION_EPS_EUR,
} from "../gen_home/flyover";
import { OBLAST_CODES, oblastFromName } from "../gen_home/oblastCodes";
import type { FlyoverWorld } from "../../../src/lib/flyover/types";

const ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "..",
);
const REL = "data/home/flyover.json";
const FILE = path.join(ROOT, REL);

const haveFile = fs.existsSync(FILE);
const haveDb = await dbReachable();
const contractsLoaded =
  haveDb &&
  Number(
    (
      await allRows<{ n: string }>(
        "SELECT count(*) n FROM contracts WHERE tag = 'contract'",
      ).catch(() => [{ n: "0" }])
    )[0]?.n ?? 0,
  ) > 0;
const skip = !haveFile
  ? `${REL} has not been generated`
  : !haveDb
    ? "Postgres unreachable"
    : !contractsLoaded
      ? "contracts corpus is empty"
      : false;
reportSkip(import.meta.url, skip);

// ⚠️ ALL FOUR ARE COMMITTED, so their absence is a broken working copy rather than a state
// this gate may stand down for — and the `!haveFile` arm above would report exactly that as a
// tidy skip, invisible in a CI summary where every *.data.test.ts skips for want of Postgres.
// The artifact is the one that matters: it is regenerated by `db:gen-home-flyover` and
// committed, so „has not been generated" is only ever true on a tree somebody has broken.
// These run OUTSIDE the gated suite, which is the point — they fire when the gate does not.
assertCommitted(
  "data/home/flyover.json",
  "data/regions_map.json",
  "data/home/hub_stats.json",
  "data/census_2021.json",
);

const artifact: FlyoverArtifactV1 | null = haveFile
  ? (JSON.parse(fs.readFileSync(FILE, "utf8")) as FlyoverArtifactV1)
  : null;

/**
 * ⚠️ THE ENGINE DECLARES THE ARTIFACT'S SHAPE A SECOND TIME, AND THIS IS WHAT KEEPS THE TWO
 * IN STEP. `src/lib/flyover/` may not import from `scripts/` — the generator pulls in
 * `node:fs`, and the engine has to bundle for the browser, for Node canvas and for Remotion —
 * so `FlyoverWorld` is a parallel declaration rather than a shared one. This assignability
 * check fails at BUILD time (`tsc -b`), not at runtime, the moment the generator's output
 * stops satisfying what the engine expects to draw.
 */
type ArtifactSatisfiesEngine = FlyoverArtifactV1 extends FlyoverWorld
  ? true
  : never;
const _engineShape: ArtifactSatisfiesEngine = true;
void _engineShape;

/**
 * Negative control: the one way the check above can go quiet is either side resolving to
 * `any`, since `any extends X ? true : never` accepts `true` and compiles in silence. This
 * line compiles only while a wrong shape is genuinely REJECTED.
 */
type EngineCheckRejectsWrongShape = { v: number } extends FlyoverWorld
  ? never
  : true;
const _engineShapeDiscriminates: EngineCheckRejectsWrongShape = true;
void _engineShapeDiscriminates;

afterAll(async () => {
  await end();
});

/** M€, the artifact's money grain — the same rounding the generator applies. */
const meur = (eur: number): number => Math.round(eur / 1e6);

test.skipIf(skip)(
  "the artifact is committed, parses, and is inside its budget",
  () => {
    const tracked = execFileSync("git", ["ls-files", REL], {
      cwd: ROOT,
      encoding: "utf8",
    }).trim();
    assert.ok(
      tracked,
      `${REL} is not tracked by git — it is a committed artifact`,
    );
    assert.equal(artifact!.v, 1);
    const bytes = fs.statSync(FILE).size;
    assert.ok(
      bytes <= MAX_BYTES,
      `${REL} is ${bytes} bytes, over the ${MAX_BYTES}-byte budget`,
    );
  },
);

test.skipIf(skip)(
  "the geometry is the committed МИР set, closed and in frame",
  () => {
    const fc = JSON.parse(
      fs.readFileSync(path.join(ROOT, "data/regions_map.json"), "utf8"),
    ) as { features: { properties: { nuts3: string } }[] };
    const keys = fc.features.map((f) => f.properties.nuts3).sort();
    assert.deepEqual(Object.keys(artifact!.geo.regions).sort(), keys);
    assert.deepEqual(artifact!.frame, { w: 1000, h: 625 });
    const oblasts = new Set<string>();
    for (const [key, region] of Object.entries(artifact!.geo.regions)) {
      oblasts.add(region.oblast);
      for (const ring of region.rings) {
        assert.ok(
          ring.length >= 4,
          `${key}: a ring with ${ring.length} points`,
        );
        assert.deepEqual(
          ring[0],
          ring[ring.length - 1],
          `${key}: an unclosed ring`,
        );
        for (const [x, y] of ring) {
          assert.ok(
            Number.isInteger(x) && Number.isInteger(y) && x >= 0 && y >= 0,
            `${key}: ${x},${y} is not an integer tenth inside the frame`,
          );
          assert.ok(
            x <= 10_000 && y <= 6_250,
            `${key}: ${x},${y} is outside the frame`,
          );
        }
      }
    }
    assert.deepEqual([...oblasts].sort(), [...OBLAST_CODES]);
    assert.deepEqual(Object.keys(artifact!.geo.cities).sort(), [
      ...OBLAST_CODES,
    ]);
  },
);

test.skipIf(skip)(
  "two consecutive runs are byte-identical, and the commit is one of them",
  async () => {
    // ⚠️ The artifact is COMMITTED. Nondeterminism here fails nothing at runtime — it churns
    // the diff of the one file a reviewer reads to see what a corpus reload actually moved.
    const a = await buildArtifact();
    const b = await buildArtifact();
    assert.equal(JSON.stringify(a), JSON.stringify(b));
    assert.equal(
      fs.readFileSync(FILE, "utf8"),
      JSON.stringify(a) + "\n",
      "the committed artifact is not what this corpus builds — run npm run db:gen-home-flyover",
    );
  },
);

test.skipIf(skip)("the funds layer declares its place coverage", async () => {
  if (!artifact!.available.funds) return;
  const [{ total, placed }] = (await allRows(
    `SELECT sum(grant_eur::numeric) AS total,
            sum(grant_eur::numeric) FILTER (
              WHERE oblast IS NOT NULL AND btrim(oblast) <> '') AS placed
       FROM fund_projects`,
  )) as { total: string; placed: string }[];
  assert.ok(Math.abs(Number(total) - artifact!.figures.fundsTotalEur) <= 1);
  assert.ok(Math.abs(Number(placed) - artifact!.figures.fundsPlacedEur) <= 1);
  // The GAP is the finding, not an error — assert that it is STATED, never that it is small.
  // 4.6% of rows are unplaced and they hold 52% of the money, so a consumer given only the
  // numerator publishes a figure about half the corpus.
  assert.ok(
    artifact!.figures.fundsTotalEur > artifact!.figures.fundsPlacedEur,
    "fundsTotalEur must be the denominator fundsPlacedEur is a share of",
  );
});

test.skipIf(skip)("no money layer has quietly emptied", () => {
  // The per-layer recount below defaults an absent oblast to 0 on BOTH sides, so a layer that
  // lost its rows compares equal. This is the non-vacuity arm: the generator's own refusal is
  // the real guard, and this notices if that refusal is ever weakened.
  for (const [name, layer] of Object.entries(artifact!.layers.all)) {
    const values = Object.values(layer!);
    const zeros = values.filter((v) => v === 0).length;
    assert.ok(
      zeros <= 2,
      `layers.all.${name} has ${zeros} zero oblasts of ${values.length} — a hole draws as a claim`,
    );
  }
});

test.skipIf(skip)("every money layer equals its own SQL recount", async () => {
  const recount = async (
    sql: string,
    key: "name" | "code",
  ): Promise<Record<string, number>> => {
    const rows = (await allRows(sql)) as {
      k: string | null;
      eur: string | null;
    }[];
    const acc = new Map<string, number>();
    for (const r of rows) {
      const code =
        key === "name"
          ? oblastFromName(r.k)
          : r.k && OBLAST_CODES.includes(r.k)
            ? r.k
            : foldCode(r.k);
      if (!code) continue;
      acc.set(code, (acc.get(code) ?? 0) + Number(r.eur ?? 0));
    }
    return Object.fromEntries(
      OBLAST_CODES.map((c) => [c, meur(acc.get(c) ?? 0)]),
    );
  };
  // The funds corpus is CODE-keyed with four spellings for the capital; the fold is the
  // generator's own, restated here only so this recount is independent of it in the arms that
  // matter (the money, and which oblast it lands in).
  const foldCode = (c: string | null): string | null =>
    c === "S22" || c === "S23" || c === "S24" || c === "S25"
      ? "SOF"
      : c === "PDV-00"
        ? "PDV"
        : null;

  const proc = await recount(
    `SELECT s.oblast AS k, sum(c.amount_eur::numeric) AS eur
       FROM contracts c JOIN awarder_seats s ON s.eik = c.awarder_eik
      WHERE c.tag = 'contract' GROUP BY 1`,
    "name",
  );
  assert.deepEqual(artifact!.layers.all.proc, proc);

  if (artifact!.available.funds) {
    const funds = await recount(
      `SELECT oblast AS k, sum(grant_eur::numeric) AS eur FROM fund_projects GROUP BY 1`,
      "code",
    );
    assert.deepEqual(artifact!.layers.all.funds, funds);
  }
  if (artifact!.available.agri) {
    const agri = await recount(
      `SELECT oblast AS k, sum(total_eur::numeric) AS eur FROM agri_subsidies GROUP BY 1`,
      "name",
    );
    assert.deepEqual(artifact!.layers.all.agri, agri);
  }
});

test.skipIf(skip)(
  "only `proc` is scoped, and the sitting parliament is a real window",
  async () => {
    // `fund_projects` has NO date column and `agri_subsidies` is annual, so a parliament window
    // over either would be invented. `available.scopedLayers` is the claim; this is the check.
    assert.deepEqual(artifact!.available.scopedLayers, ["proc"]);
    const scoped = Object.keys(artifact!.layers).filter((k) => k !== "all");
    assert.equal(
      scoped.length,
      1,
      "v1 carries `all` plus exactly one parliament window",
    );
    for (const key of scoped) {
      assert.deepEqual(Object.keys(artifact!.layers[key]), ["proc"]);
    }
    const [{ scope_key }] = (await allRows(
      `SELECT scope_key FROM procurement_scopes WHERE scope_key LIKE 'ns:%'
      ORDER BY sort_ord ASC LIMIT 1`,
    )) as { scope_key: string }[];
    assert.equal(
      scoped[0],
      scope_key,
      "the scoped window is the SITTING parliament",
    );
    // It must be a strict subset of the corpus, or the window is not being applied at all.
    const all = Object.values(artifact!.layers.all.proc!).reduce(
      (a, b) => a + b,
      0,
    );
    const ns = Object.values(artifact!.layers[scope_key].proc!).reduce(
      (a, b) => a + b,
      0,
    );
    assert.ok(
      ns > 0 && ns < all,
      `the ${scope_key} window sums ${ns} against ${all} for all time`,
    );
  },
);

test.skipIf(skip)(
  "the flow matrix equals its independent recount, cell by cell",
  async () => {
    // ⚠️ THE LEAD IS RESOLVED IN TYPESCRIPT HERE, NOT WITH THE GENERATOR'S `DISTINCT ON`. Since
    // T3.3 a carrier's oblast comes from its largest member, and a recount that pasted the
    // generator's CTE would agree with it by construction — including on an ordering bug, which
    // is the one defect a `DISTINCT ON` over three sort keys can actually have. Picking the max
    // in a loop is a second implementation of the same RULE, which is what makes this a check.
    const members = (await allRows(
      `SELECT c.consortium_eik AS carrier, c.contractor_eik AS eik, p.oblast AS oblast
         FROM contracts c
         JOIN tr_company_place p ON p.uic = c.contractor_eik
        WHERE c.consortium_role = 'member' AND c.tag = 'contract'
          AND p.oblast IS NOT NULL
        GROUP BY 1, 2, 3`,
    )) as { carrier: string; eik: string; oblast: string }[];
    // ⚠️ THE PREMISE THE TWO IMPLEMENTATIONS RESTED ON, ASSERTED. Until 2026-09-06 the
    // generator picked the lead over every member with a `tr_company_place` ROW while this
    // recount filtered on a non-null OBLAST — different rules in the two files, held in
    // agreement only by the column being 100% populated. Both read `p.oblast` now; this pins
    // the property, so a future divergence fails HERE rather than as a differing cell.
    const [nulls] = await allRows<{ n: string }>(
      "SELECT count(*)::text AS n FROM tr_company_place WHERE oblast IS NULL",
    );
    assert.equal(
      Number(nulls.n),
      0,
      `${nulls.n} tr_company_place rows carry a null oblast — "placed" now means different ` +
        `things in the lead pick, the matrix and the coverage`,
    );
    const own = new Map(
      (
        (await allRows(
          `SELECT contractor_eik AS eik, sum(amount_eur::numeric) AS eur
             FROM contracts WHERE tag = 'contract' GROUP BY 1`,
        )) as { eik: string; eur: string }[]
      ).map((r) => [r.eik, Number(r.eur)]),
    );
    const lead = new Map<string, string>();
    const best = new Map<string, { eur: number; eik: string }>();
    for (const r of members) {
      const eur = own.get(r.eik) ?? 0;
      const cur = best.get(r.carrier);
      // Largest own money wins; EIK breaks the tie — the generator's ORDER BY, restated as a
      // comparison so a disagreement about either key shows up as a differing cell.
      // ⚠️ `<` on a string is UTF-16 CODE-UNIT order, which is why the generator's ORDER BY
      // carries `COLLATE "C"`: en_US.utf8 does not compare punctuation at the primary weight,
      // and 38 carriers tie at the top money with 7 of those ties deciding an oblast. Without
      // the collation the two implementations agree by luck of the data rather than by rule.
      if (!cur || eur > cur.eur || (eur === cur.eur && r.eik < cur.eik)) {
        best.set(r.carrier, { eur, eik: r.eik });
        lead.set(r.carrier, r.oblast);
      }
    }

    const rows = (await allRows(
      `SELECT s.oblast AS buyer, p.oblast AS con,
              -- ⚠️ THE SYNTHETIC GUARD, HERE TOO. Without it this recount reproduces the
              -- generator's own omission and agrees with it by construction — which is exactly
              -- how €19,857,818 across 18 ph-/np- keys was drawn as arcs while the coverage
              -- called it unplaced, with this test green.
              CASE WHEN c.consortium_role = 'carrier'
                    AND c.contractor_eik NOT LIKE 'ph-%'
                    AND c.contractor_eik NOT LIKE 'np-%'
                   THEN c.contractor_eik END AS carrier,
              sum(c.amount_eur::numeric) AS eur
         FROM contracts c
         JOIN awarder_seats s ON s.eik = c.awarder_eik
         LEFT JOIN tr_company_place p ON p.uic = c.contractor_eik
        WHERE c.tag = 'contract'
        GROUP BY 1, 2, 3`,
    )) as {
      buyer: string;
      con: string | null;
      carrier: string | null;
      eur: string;
    }[];
    const idx = new Map(OBLAST_CODES.map((c, i) => [c, i]));
    const m = OBLAST_CODES.map(() => OBLAST_CODES.map(() => 0));
    let viaLead = 0;
    for (const r of rows) {
      const b = oblastFromName(r.buyer);
      const conName =
        r.con ?? (r.carrier ? (lead.get(r.carrier) ?? null) : null);
      if (!r.con && conName) viaLead += Number(r.eur);
      const k = oblastFromName(conName);
      if (!b || !k) continue;
      m[idx.get(b)!][idx.get(k)!] += Number(r.eur);
    }
    assert.deepEqual(artifact!.flows.keys, [...OBLAST_CODES]);
    assert.deepEqual(
      artifact!.flows.m,
      m.map((row) => row.map(meur)),
    );
    // Non-vacuity: the lead branch must have been exercised, or this reproduces the pre-T3.3
    // matrix and would pass against a generator that had lost the attribution entirely.
    assert.ok(
      viaLead > 1e9,
      `only €${viaLead} entered the matrix via a carrier's lead member — the attribution is ` +
        `not being tested`,
    );
  },
);

test.skipIf(skip)(
  "the coverage buckets are an exact partition of the corpus",
  () => {
    const cov = artifact!.flows.coverage;
    const parts =
      cov.bothPlacedEur +
      Object.values(cov.unplaced).reduce((a, b) => a + b, 0);
    // ⚠️ SHARED WITH THE GENERATOR rather than restated: six independently rounded euro
    // figures against one rounded total can differ by 3 with no defect present, and this
    // used to allow 1 — the value the committed artifact happens to sit at. A reload that
    // shifted the cents would have failed here AND aborted `db:gen-home-flyover` mid-chain,
    // both naming a hole that was not there.
    assert.ok(
      Math.abs(parts - cov.totalEur) <= PARTITION_EPS_EUR,
      `the buckets sum to ${parts} against a corpus of ${cov.totalEur} — ` +
        `\`unplaced\` is a decomposition, not a list of related figures`,
    );
    // The matrix's own total is the both-placed sum, to within the M€ rounding of 784 cells.
    // ⚠️ THIS TOLERANCE IS 392 M€ AND CANNOT BE TIGHTENED — it is 784 cells of M€ rounding,
    // measured at −24 M€ today. It is therefore blind to anything smaller, which is how a
    // 19.9 M€ leak lived inside it; "the matrix draws exactly what the bothPlaced bucket
    // counts" below is the assertion that compares the two in EUROS, before rounding.
    const matrixM = artifact!.flows.m.reduce(
      (a, row) => a + row.reduce((x, y) => x + y, 0),
      0,
    );
    assert.ok(
      Math.abs(matrixM - meur(cov.bothPlacedEur)) <=
        OBLAST_CODES.length ** 2 / 2,
      `the matrix sums to ${matrixM} M€ against a declared ${meur(cov.bothPlacedEur)} M€`,
    );
  },
);

test.skipIf(skip)(
  "the arcs' coverage floor still holds, and the join still discriminates",
  async () => {
    // The §7 ratchet. RAISE this by hand after each contractor-placement step lands; a floor
    // left where it was is a gate that has stopped discriminating.
    //
    // 0.20 → 0.33 on 2026-09-06, when T3.1 (the CR deed seat projected into
    // `tr_companies.seat`) took the reading from 23.45% to **36.24%** — 26,152 companies that
    // had no seat at all now have one, and 99.6% of the seated corpus places. `trNoSeat`, the
    // largest unplaced bucket, fell from 45.5% to 32.6% of the money.
    //
    // 0.33 → 0.42 the same day, when T3.3 placed the consortium carriers at their largest
    // member: **36.24% → 46.62%**, €9.81bn moving out of `carriers` (6.6% → 0.8%) and out of
    // `notInTr` (24.2% → 19.6%, the registered ДЗЗД half). ⚠️ That money is placed by
    // ATTRIBUTION rather than by a seat, so this floor no longer measures only what the corpus
    // knows — `carrierLead` is asserted separately below, and 546 of those groups have members
    // in more than one oblast.
    //
    // ⚠️ THE FLOOR SITS BELOW THE READING ON PURPOSE, and the margin is for CORPUS drift, not
    // for a regression: a contracts reload moves the denominator, and `db:load:tr:pg` is a
    // REFRESH_EXCLUSIONS member, so a machine can legitimately sit a TR vintage behind. ~9%
    // of headroom absorbs that and still fails long before the pre-T3.1 state.
    const FLOOR = 0.42;
    const cov = artifact!.flows.coverage;
    const placed = cov.bothPlacedEur / cov.totalEur;
    assert.ok(
      placed >= FLOOR,
      `both ends are placed for ${(placed * 100).toFixed(1)}% of the money, under the ${FLOOR * 100}% floor`,
    );
    // Mutation check: the same recount WITHOUT the contractor join must be strictly larger, or
    // an implementation whose join silently stopped filtering would satisfy the assertion above.
    const [{ eur }] = (await allRows(
      `SELECT sum(c.amount_eur::numeric) AS eur
       FROM contracts c JOIN awarder_seats s ON s.eik = c.awarder_eik
      WHERE c.tag = 'contract'`,
    )) as { eur: string }[];
    assert.ok(
      Number(eur) > cov.bothPlacedEur * 1.5,
      "dropping the contractor join did not widen the sum — the join is not filtering",
    );
  },
);

test.skipIf(skip)(
  "the three procurement bases stay distinct and stay close",
  async () => {
    const cov = artifact!.flows.coverage;
    const [{ total }] = (await allRows(
      `SELECT sum(amount_eur::numeric) AS total FROM contracts WHERE tag = 'contract'`,
    )) as { total: string }[];
    assert.ok(
      Math.abs(Number(total) - cov.totalEur) <= 1,
      "coverage.totalEur is not the corpus at tag='contract'",
    );
    const hub = JSON.parse(
      fs.readFileSync(path.join(ROOT, "data/home/hub_stats.json"), "utf8"),
    ) as { tiles?: { procurement?: { value?: number } } };
    assert.equal(
      artifact!.figures.procTotalEur,
      Math.round(hub.tiles!.procurement!.value!),
      "the caption headline must be the tile's own figure — two numbers on one screen",
    );
    const gap =
      Math.abs(artifact!.figures.procTotalEur - cov.totalEur) / cov.totalEur;
    assert.ok(
      gap < 0.005,
      `the tile and the corpus differ by ${(gap * 100).toFixed(2)}%`,
    );
    assert.ok(
      cov.buyerPlacedEur / cov.totalEur >= 0.98,
      `only ${((cov.buyerPlacedEur / cov.totalEur) * 100).toFixed(1)}% of the money has a placed buyer`,
    );
  },
);

test.skipIf(skip)(
  "computedAt is the max source date, never today",
  async () => {
    const [{ max_date }] = (await allRows(
      `SELECT max(date) AS max_date FROM contracts WHERE tag = 'contract'`,
    )) as { max_date: string }[];
    assert.equal(artifact!.computedAt, max_date);
    assert.notEqual(
      artifact!.computedAt,
      new Date().toISOString().slice(0, 10),
      "a `now` stamp lets a stalled pipeline look fresh and makes two rebuilds differ",
    );
  },
);

test.skipIf(skip)("the overlays are declared rather than assumed", () => {
  const a = artifact!;
  assert.equal(a.available.elections, Boolean(a.elections));
  assert.equal(a.available.prices, Boolean(a.prices));
  assert.equal(a.available.proc, Boolean(a.layers.all.proc));
  assert.equal(a.available.funds, Boolean(a.layers.all.funds));
  assert.equal(a.available.agri, Boolean(a.layers.all.agri));
  if (a.prices) {
    // МИР keys, not oblast codes — the price panel's grain and the polygons'.
    for (const key of Object.keys(a.prices.byMir)) {
      assert.ok(
        key in a.geo.regions,
        `prices carry ${key}, which has no polygon`,
      );
    }
    assert.ok(a.prices.national > 0);
  }
  if (a.elections) {
    // ⚠️ WHICH elections, not just that they are well-formed. A slice taken from the wrong end
    // of a registry that carries no date field shows 2005 and 2009 while every other assertion
    // here passes.
    const registry = JSON.parse(
      fs.readFileSync(path.join(ROOT, "src/data/json/elections.json"), "utf8"),
    ) as { name: string }[];
    const newest = registry
      .map((e) => e.name)
      .sort()
      .slice(-2)
      .reverse();
    assert.deepEqual(
      Object.keys(a.elections),
      newest.filter((d) =>
        fs.existsSync(path.join(ROOT, `data/${d}/region_votes.json`)),
      ),
      "the overlay must carry the MOST RECENT elections",
    );
    for (const [date, regions] of Object.entries(a.elections)) {
      for (const [key, r] of Object.entries(regions)) {
        assert.ok(key in a.geo.regions, `${date}: ${key} has no polygon`);
        assert.ok(
          r.nick.length > 0 && r.color.length > 0,
          `${date}/${key}: no winner`,
        );
        assert.ok(
          r.share > 0 && r.share <= 100,
          `${date}/${key}: share ${r.share}`,
        );
      }
    }
  }
});

test.skipIf(skip)("every population is the census's own", () => {
  const census = JSON.parse(
    fs.readFileSync(path.join(ROOT, "data/census_2021.json"), "utf8"),
  ) as { oblasts: { code: string; population: number }[] };
  assert.deepEqual(
    artifact!.pop,
    Object.fromEntries(
      census.oblasts
        .map((o) => [o.code, o.population] as const)
        .sort(([a], [b]) => (a < b ? -1 : 1)),
    ),
  );
});

test.skipIf(skip)(
  "the consortium attribution is a declared subset, not a sixth bucket",
  async () => {
    // ⚠️ WHAT THIS EXISTS TO CATCH. `carrierLead.eur` is money that is ALREADY inside
    // `bothPlacedEur` / `buyerUnplaced`; the partition test above cannot see it, because it
    // does not read this field. A consumer that added it — or a generator change that started
    // counting rows the bucket CASE does not — would over-state the corpus with every count
    // still reconciling.
    const lead = artifact!.flows.carrierLead;
    assert.ok(lead, "the artifact carries no carrierLead — regenerate it");
    const cov = artifact!.flows.coverage;
    assert.ok(
      lead.eur <= cov.bothPlacedEur + cov.unplaced.buyerUnplaced,
      `carrier-lead money ${lead.eur} exceeds the ${cov.bothPlacedEur + cov.unplaced.buyerUnplaced} it is a subset of`,
    );

    // ⚠️ THE COUNTS AND THE MONEY MUST DESCRIBE ONE POPULATION. The first cut counted only the
    // synthetic `obed-` carriers (1,420) while the euro figure covered those AND the registered
    // ДЗЗД that carry an ordinary 9-digit EIK (611 more) — and NOT the 18 ph-/np- keys that also carry the role — a rate over the
    // wrong denominator, and invisible because both numbers were individually right.
    const [row] = await allRows<{ seatless: string; placed: string }>(
      `WITH carriers AS (
         -- ⚠️ THE SAME SYNTHETIC GUARD THE GENERATOR APPLIES. A ph-/np- key is a filler
         -- registration number or a natural person, which is not a consortium — and this
         -- recount admitted 22 of them (18 placed, 4 not) while the artifact excluded them,
         -- which is what the equality below is for.
         SELECT DISTINCT contractor_eik AS eik FROM contracts
          WHERE consortium_role = 'carrier' AND tag = 'contract'
            AND contractor_eik NOT LIKE 'ph-%' AND contractor_eik NOT LIKE 'np-%'
       ), unseated AS (
         SELECT c.eik FROM carriers c
          LEFT JOIN tr_company_place p ON p.uic = c.eik
          WHERE p.oblast IS NULL
       )
       SELECT (SELECT count(*)::text FROM unseated) AS seatless,
              (SELECT count(DISTINCT c.consortium_eik)::text
                 FROM contracts c
                 JOIN tr_company_place p ON p.uic = c.contractor_eik
                WHERE c.consortium_role = 'member' AND c.tag = 'contract'
                  AND c.consortium_eik IN (SELECT eik FROM unseated)) AS placed`,
    );
    assert.equal(
      lead.consortia + lead.unplaced,
      Number(row.seatless),
      `carrierLead counts ${lead.consortia + lead.unplaced} seatless carriers against ` +
        `${row.seatless} in the corpus — the counts and the money are over different populations`,
    );
    assert.equal(lead.consortia, Number(row.placed));

    // The multi-oblast count is the honesty field: it says how often the lead DISCARDS a true
    // answer. It cannot exceed the groups it is drawn from, and it must not be zero — a zero
    // would mean every consortium sits in one oblast, which would make the whole caveat
    // unnecessary and is the shape a broken query returns.
    assert.ok(
      lead.multiOblast > 0 && lead.multiOblast <= lead.consortia,
      `multiOblast ${lead.multiOblast} against ${lead.consortia} placed groups`,
    );
    // Non-vacuity: the attribution must actually be doing something.
    assert.ok(
      lead.consortia > 100 && lead.eur > 1e9,
      `the carrier attribution placed ${lead.consortia} groups / €${lead.eur} — it has stopped working`,
    );
  },
);

test.skipIf(skip)(
  "the matrix still refuses an unplaced contractor",
  async () => {
    // The mutation check for T3.3: the lead join must ADD carriers, never admit everything. If
    // `COALESCE(p.oblast, cl.oblast)` ever stopped filtering, the matrix would absorb the
    // `trNoSeat` and `notInTr` money too and `bothPlacedEur` would approach `buyerPlacedEur`.
    const cov = artifact!.flows.coverage;
    assert.ok(
      cov.bothPlacedEur < cov.buyerPlacedEur * 0.75,
      `both-placed ${cov.bothPlacedEur} is within 75% of buyer-placed ${cov.buyerPlacedEur} — ` +
        `the contractor join has stopped discriminating`,
    );
    // …and the residue must survive: a corpus in which nothing is unplaced is not this one.
    assert.ok(
      cov.unplaced.trNoSeat > 1e10 && cov.unplaced.notInTr > 1e10,
      "the unplaced buckets have collapsed — the contractor side is no longer being tested",
    );
  },
);

test.skipIf(skip)(
  "the matrix draws exactly what the bothPlaced bucket counts",
  async () => {
    // ⚠️ COMPARED BEFORE ROUNDING, which the sibling assertion above cannot do: it allows
    // ±392 M€ for M€ rounding across 784 cells, and the leak it needed to catch was 19.9 M€ —
    // twenty times smaller than its own tolerance. The two quantities are selected by two
    // DIFFERENT predicates (the matrix's WHERE, the coverage's CASE), and T3.3 made them
    // disagree by adding a placement route to one and not the other. In euros they must be
    // identical.
    const [r] = await allRows<{ matrix: string; bucket: string }>(
      `WITH c AS (
         SELECT c.amount_eur::numeric AS eur,
                (s.eik IS NOT NULL) AS buyer_placed,
                (COALESCE(p.oblast, cl.oblast) IS NOT NULL) AS con_placed,
                c.contractor_eik AS eik
           FROM contracts c
           LEFT JOIN awarder_seats s ON s.eik = c.awarder_eik
           LEFT JOIN tr_company_place p ON p.uic = c.contractor_eik
           LEFT JOIN (
             SELECT DISTINCT ON (m.consortium_eik) m.consortium_eik AS carrier_eik, q.oblast
               FROM contracts m
               JOIN tr_company_place q ON q.uic = m.contractor_eik AND q.oblast IS NOT NULL
               LEFT JOIN (SELECT contractor_eik AS eik, sum(amount_eur::numeric) AS own_eur
                            FROM contracts WHERE tag = 'contract' GROUP BY 1) mm
                      ON mm.eik = m.contractor_eik
              WHERE m.consortium_role = 'member' AND m.tag = 'contract'
              ORDER BY m.consortium_eik, COALESCE(mm.own_eur, 0) DESC,
                       m.contractor_eik COLLATE "C"
           ) cl ON cl.carrier_eik = c.contractor_eik
               AND c.consortium_role = 'carrier'
               AND c.contractor_eik NOT LIKE 'ph-%'
               AND c.contractor_eik NOT LIKE 'np-%'
          WHERE c.tag = 'contract'
       )
       SELECT round(sum(eur) FILTER (WHERE con_placed AND buyer_placed))::text AS matrix,
              round(sum(eur) FILTER (
                WHERE NOT (eik LIKE 'ph-%' OR eik LIKE 'np-%')
                  AND con_placed AND buyer_placed))::text AS bucket
         FROM c`,
    );
    assert.equal(
      r.matrix,
      r.bucket,
      "the matrix draws money the coverage calls unplaced — a placement route bypassed the CASE",
    );
    assert.equal(
      Number(r.bucket),
      artifact!.flows.coverage.bothPlacedEur,
      "bothPlacedEur disagrees with its own recount",
    );
  },
);

test.skipIf(skip)(
  "the lead attribution counts only carriers a member set can stand for",
  async () => {
    // ⚠️ THE EQUALITY ABOVE CANNOT SEE THIS. `consortia + unplaced == seatless` is true of any
    // partition of the same set — including one that admits `ph-`/`np-` keys on both sides,
    // which is the state that shipped. This asserts the COMPOSITION rather than the split.
    const [r] = await allRows<{ synthetic: string; obed: string; reg: string }>(
      `SELECT count(*) FILTER (WHERE eik LIKE 'ph-%' OR eik LIKE 'np-%')::text AS synthetic,
              count(*) FILTER (WHERE eik LIKE 'obed-%')::text AS obed,
              count(*) FILTER (WHERE eik NOT LIKE 'obed-%' AND eik NOT LIKE 'ph-%'
                                 AND eik NOT LIKE 'np-%')::text AS reg
         FROM (
           SELECT DISTINCT c.contractor_eik AS eik
             FROM contracts c
             LEFT JOIN tr_company_place p ON p.uic = c.contractor_eik
            WHERE c.consortium_role = 'carrier' AND c.tag = 'contract' AND p.oblast IS NULL
              AND c.contractor_eik NOT LIKE 'ph-%' AND c.contractor_eik NOT LIKE 'np-%'
         ) q`,
    );
    assert.equal(
      Number(r.synthetic),
      0,
      "a filler id or a natural person is not a consortium — the lead join lost the synthetic guard",
    );
    // Both real kinds must be present, or the guard has become a filter on everything: the
    // synthetic `obed-` keys AND the registered ДЗЗД that carry an ordinary 9-digit EIK.
    assert.ok(
      Number(r.obed) > 1_000 && Number(r.reg) > 100,
      `seatless carriers split ${r.obed} obed- / ${r.reg} registered — one kind has vanished`,
    );
  },
);

test.skipIf(skip)(
  "carrierLead.eur is recounted, not merely bounded",
  async () => {
    // The caption renders this as `leadBn`. Every other published figure gets an independent
    // recount; this one had an inequality with €34bn of slack, which is why 19.9 M€ of
    // contamination sat inside it unnoticed.
    const [r] = await allRows<{ eur: string }>(
      `WITH mm AS (SELECT contractor_eik AS eik, sum(amount_eur::numeric) AS own_eur
                     FROM contracts WHERE tag = 'contract' GROUP BY 1),
            cl AS (SELECT DISTINCT ON (m.consortium_eik) m.consortium_eik AS carrier_eik, q.oblast
                     FROM contracts m
                     JOIN tr_company_place q ON q.uic = m.contractor_eik AND q.oblast IS NOT NULL
                     LEFT JOIN mm ON mm.eik = m.contractor_eik
                    WHERE m.consortium_role = 'member' AND m.tag = 'contract'
                    ORDER BY m.consortium_eik, COALESCE(mm.own_eur, 0) DESC,
                             m.contractor_eik COLLATE "C")
       SELECT round(sum(c.amount_eur::numeric))::text AS eur
         FROM contracts c
         JOIN cl ON cl.carrier_eik = c.contractor_eik
         LEFT JOIN tr_company_place p ON p.uic = c.contractor_eik
        WHERE c.tag = 'contract' AND c.consortium_role = 'carrier'
          AND c.contractor_eik NOT LIKE 'ph-%' AND c.contractor_eik NOT LIKE 'np-%'
          AND p.oblast IS NULL AND cl.oblast IS NOT NULL`,
    );
    assert.ok(
      Math.abs(Number(r.eur) - artifact!.flows.carrierLead.eur) <= 1,
      `carrierLead.eur is ${artifact!.flows.carrierLead.eur} against a recount of ${r.eur}`,
    );
  },
);

test.skipIf(skip)(
  "multiOblast is a subset of the placed groups, recounted",
  async () => {
    // The caption says „При {{multi}} от тях" — of THOSE groups — so containment is a claim
    // about the published pair and not a bound. The generator's `spread` CTE ranges over every
    // seatless carrier, placed or not, so the claim held only while no `tr_company_place` row
    // carried a null oblast; this recounts it against the placed set.
    const [r] = await allRows<{ multi: string }>(
      `WITH mm AS (SELECT contractor_eik AS eik, sum(amount_eur::numeric) AS own_eur
                     FROM contracts WHERE tag = 'contract' GROUP BY 1),
            cl AS (SELECT DISTINCT ON (m.consortium_eik) m.consortium_eik AS carrier_eik, q.oblast
                     FROM contracts m
                     JOIN tr_company_place q ON q.uic = m.contractor_eik AND q.oblast IS NOT NULL
                     LEFT JOIN mm ON mm.eik = m.contractor_eik
                    WHERE m.consortium_role = 'member' AND m.tag = 'contract'
                    ORDER BY m.consortium_eik, COALESCE(mm.own_eur, 0) DESC,
                             m.contractor_eik COLLATE "C"),
            seatless AS (
              SELECT DISTINCT c.contractor_eik AS eik
                FROM contracts c
                LEFT JOIN tr_company_place p ON p.uic = c.contractor_eik
               WHERE c.consortium_role = 'carrier' AND c.tag = 'contract' AND p.oblast IS NULL
                 AND c.contractor_eik NOT LIKE 'ph-%' AND c.contractor_eik NOT LIKE 'np-%')
       SELECT count(*)::text AS multi FROM (
         SELECT m.consortium_eik
           FROM contracts m
           JOIN tr_company_place q ON q.uic = m.contractor_eik AND q.oblast IS NOT NULL
          WHERE m.consortium_role = 'member' AND m.tag = 'contract'
            AND m.consortium_eik IN (SELECT eik FROM seatless)
            AND m.consortium_eik IN (SELECT carrier_eik FROM cl WHERE oblast IS NOT NULL)
          GROUP BY 1 HAVING count(DISTINCT q.oblast) > 1) s`,
    );
    assert.equal(
      Number(r.multi),
      artifact!.flows.carrierLead.multiOblast,
      `multiOblast is ${artifact!.flows.carrierLead.multiOblast} against a recount of ${r.multi} ` +
        `over the PLACED groups — the caption's „of those" is not true of the published pair`,
    );
  },
);
