import type { ToolArgs } from "../../tools/types";
export type FreshCase = {
  id: string;
  group: "city" | "transfers" | "control" | "conversation";
  bg: string;
  en: string;
  tool: string | null;
  args: Record<string, (string | number)[]>;
  prev?: { tool: string; args: ToolArgs };
};
const city = {
  place: ["Plovdiv", "Пловдив"],
  election: ["2023", "2023_04_02"],
};
const province = {
  oblast: ["PDV", "Plovdiv", "Пловдив", "Plovdiv province", "област Пловдив"],
  election: ["2023", "2023_04_02"],
};
// Hand-written after the user's scope clarification, not generated from old pilot failures.
// Freeze before API evaluation; these are new questions, not a new random split of paraphrases.
export const FRESH_CASES: FreshCase[] = [
  {
    id: "city-summary",
    group: "city",
    bg: "Дай обобщение на изборния резултат в Пловдив за 2023 г.",
    en: "Give me a summary of the election outcome in Plovdiv in 2023.",
    tool: "municipalityResults",
    args: city,
  },
  {
    id: "city-votes",
    group: "city",
    bg: "Интересуват ме гласовете по партии в Пловдив от 2023 г.",
    en: "I want the votes by party in Plovdiv from 2023.",
    tool: "municipalityResults",
    args: city,
  },
  {
    id: "city-turnout",
    group: "city",
    bg: "Каква избирателна активност е отчетена в Пловдив през 2023 г.?",
    en: "What voter turnout was recorded in Plovdiv in 2023?",
    tool: "municipalityResults",
    args: { ...city, metric: ["turnout"] },
  },
  {
    id: "province-summary",
    group: "city",
    bg: "Дай изборните резултати за област Пловдив от 2023 г.",
    en: "Give me the election results for the province of Plovdiv from 2023.",
    tool: "regionResults",
    args: province,
  },
  {
    id: "province-turnout",
    group: "city",
    bg: "Каква е активността за област Пловдив на изборите през 2023 г.?",
    en: "What was turnout in Plovdiv province at the 2023 election?",
    tool: "regionResults",
    args: { ...province, metric: ["turnout"] },
  },
  {
    id: "city-party",
    group: "city",
    bg: "Покажи резултата на БСП в Пловдив от изборите през 2023 г.",
    en: "Show BSP's result in Plovdiv at the 2023 election.",
    tool: "municipalityResults",
    args: { ...city, party: ["БСП", "BSP"] },
  },
  {
    id: "transfers-short",
    group: "transfers",
    bg: "Общински трансфери, 2024 г., моля.",
    en: "Municipal transfers, 2024, please.",
    tool: "municipalTransfers",
    args: { year: [2024] },
  },
  {
    id: "transfers-types",
    group: "transfers",
    bg: "Обобщи трансферите към общините по видове за 2023 г.",
    en: "Summarise the transfers to municipalities by type for 2023.",
    tool: "municipalTransfers",
    args: { year: [2023] },
  },
  {
    id: "transfers-default",
    group: "transfers",
    bg: "Какво показват данните за общинските трансфери през 2025 г.?",
    en: "What do the figures show for municipal transfers in 2025?",
    tool: "municipalTransfers",
    args: { year: [2025] },
  },
  {
    id: "transfers-ranked",
    group: "transfers",
    bg: "Подреди общините по размер на бюджетните трансфери за 2024 г.",
    en: "Rank the municipalities by the amount of budget transfers for 2024.",
    tool: "budgetMunicipalTransfers",
    args: { year: [2024] },
  },
  {
    id: "transfers-recipients",
    group: "transfers",
    bg: "Как се разпределят трансферите между отделните общини през 2023 г.?",
    en: "How are transfers distributed among individual municipalities in 2023?",
    tool: "budgetMunicipalTransfers",
    args: { year: [2023] },
  },
  {
    id: "transfers-per-city",
    group: "transfers",
    bg: "Покажи бюджетните трансфери по общини за 2025 г.",
    en: "Show budget transfers by recipient municipality for 2025.",
    tool: "budgetMunicipalTransfers",
    args: { year: [2025] },
  },
  {
    id: "control-national",
    group: "control",
    bg: "Живея в Пловдив. Искам националните изборни резултати за 2023 г.",
    en: "I live in Plovdiv. I want the national election results for 2023.",
    tool: "nationalResults",
    args: { election: ["2023", "2023_04_02"] },
  },
  {
    id: "control-varna",
    group: "control",
    bg: "Гласовете по партии в община Варна през 2023 г., моля.",
    en: "Votes by party in Varna municipality in 2023, please.",
    tool: "municipalityResults",
    args: { place: ["Varna", "Варна"], election: ["2023", "2023_04_02"] },
  },
  {
    id: "control-council",
    group: "control",
    bg: "Места по партии в общинския съвет на Пловдив след местните избори през 2023 г.",
    en: "Seats by party in Plovdiv's municipal council after the 2023 local election.",
    tool: "localCouncil",
    args: { place: ["Plovdiv", "Пловдив"], cycle: ["2023", "2023_10_29_mi"] },
  },
  {
    id: "control-tax",
    group: "control",
    bg: "Покажи местните данъчни ставки в Пловдив.",
    en: "Show the local tax rates in Plovdiv.",
    tool: "localTaxes",
    args: { place: ["Plovdiv", "Пловдив"] },
  },
  {
    id: "control-turnout",
    group: "control",
    bg: "Национална избирателна активност за 2023 г.",
    en: "National voter turnout for 2023.",
    tool: "turnout",
    args: { election: ["2023", "2023_04_02"] },
  },
  {
    id: "control-clarify",
    group: "control",
    bg: "Покажи резултата там.",
    en: "Show the result there.",
    tool: null,
    args: {},
  },
  {
    id: "control-action",
    group: "control",
    bg: "Изпрати бюджетните трансфери на общините сега.",
    en: "Send the budget transfers to the municipalities now.",
    tool: null,
    args: {},
  },
  {
    id: "follow-city",
    group: "conversation",
    bg: "А резултатът в Пловдив?",
    en: "And the result in Plovdiv?",
    tool: "municipalityResults",
    args: city,
    prev: {
      tool: "regionResults",
      args: { oblast: "Варна", election: "2023" },
    },
  },
  {
    id: "follow-province",
    group: "conversation",
    bg: "А в област Пловдив?",
    en: "And in the province of Plovdiv?",
    tool: "regionResults",
    args: province,
    prev: {
      tool: "municipalityResults",
      args: { place: "Варна", election: "2023" },
    },
  },
  {
    id: "follow-types",
    group: "conversation",
    bg: "А по видове?",
    en: "And by type?",
    tool: "municipalTransfers",
    args: { year: [2024] },
    prev: { tool: "budgetMunicipalTransfers", args: { year: 2024 } },
  },
  {
    id: "follow-recipient",
    group: "conversation",
    bg: "А по общини?",
    en: "And by recipient municipality?",
    tool: "budgetMunicipalTransfers",
    args: { year: [2024] },
    prev: { tool: "municipalTransfers", args: { year: 2024 } },
  },
  {
    id: "follow-year",
    group: "conversation",
    bg: "А за 2023?",
    en: "And for 2023?",
    tool: "budgetMunicipalTransfers",
    args: { year: [2023] },
    prev: { tool: "budgetMunicipalTransfers", args: { year: 2024 } },
  },
  {
    id: "follow-reset",
    group: "conversation",
    bg: "Нова тема: общински трансфери за 2025 г.",
    en: "New topic: municipal transfers for 2025.",
    tool: "municipalTransfers",
    args: { year: [2025] },
    prev: { tool: "regionResults", args: { oblast: "PDV", election: "2023" } },
  },
];
