const settlementNames: { old: string; new: string; oblast: string }[] = [
  { old: "с.Касъка", new: "с.Късак", oblast: "SML" },
  { old: "с.Гара Орешец", new: "с.Орешец", oblast: "VID" },
  { old: "с. Киряево", new: "с. Киреево", oblast: "VID" },
  { old: "с.Куклен", new: "гр.Куклен", oblast: "PDV" },
  { old: "с.Добринище", new: "гр.Добринище", oblast: "BLG" },
  { old: "с. Зелен дол", new: "с. Зелендол", oblast: "BLG" },
  {
    old: "с. Ср. рът и с. Марк. рще",
    new: "с. Средни рът и с. Марково равнище",
    oblast: "VRC",
  },
  { old: "с. Митиново", new: "с. Митино", oblast: "BLG" },
  { old: "с. Долно Спанчово", new: "с. Долно Спанчево", oblast: "BLG" },
  { old: "с. Рибин дол", new: "с. Рибен дол", oblast: "SML" },
  { old: "с. Жребово", new: "с. Жребево", oblast: "SML" },
  { old: "с.Стоманово", new: "с.Стоманево", oblast: "SML" },
  { old: "с. Чуреково", new: "с. Чуруково", oblast: "SML" },
  { old: "с.Змейца", new: "с.Змеица", oblast: "SML" },
  { old: "с. Чуричене", new: "с. Чуричени", oblast: "BLG" },
  { old: "с.Ляска", new: "с.Леска", oblast: "SML" },
  { old: "с.Печинско", new: "с.Печинска", oblast: "SML" },
  { old: "с.Долен Върли дол", new: "с.Върли дол", oblast: "SML" },
  { old: "с.Горен Върли дол", new: "с.Върли дол", oblast: "SML" },
  { old: "с. Мочура", new: "с. Мочуре", oblast: "SML" },
  { old: "с.Корита", new: "с.Коритата", oblast: "SML" },
  { old: "с.Сопота", new: "с.Сопотот", oblast: "SML" },
  { old: "с. Голешево", new: "с. Голешово", oblast: "BLG" },
  { old: "с. Горни Кортен", new: "с. Горни Коритен", oblast: "KNL" },
  { old: "с.Ряка", new: "с.Река", oblast: "SML" },
  { old: "м.Еленска", new: "с.Еленска", oblast: "SML" },
  { old: "с. Кокарово", new: "с. Кокорово", oblast: "SML" },
  { old: "с. Ново Ляски", new: "с. Ново Лески", oblast: "BLG" },
  { old: "с.Банево", new: "гр.Бургас", oblast: "BGS" },
  { old: "с.Ветрен", new: "гр.Бургас", oblast: "BGS" },
  { old: "с.Рудник", new: "гр.Бургас", oblast: "BGS" },
  { old: "с.Черно море", new: "гр.Бургас", oblast: "BGS" },
  { old: "с.Игнатиево", new: "гр.Игнатиево", oblast: "VAR" },
  { old: "с.Свети Влас", new: "гр.Свети Влас", oblast: "BGS" },
  { old: "с.Ахелой", new: "гр.Ахелой", oblast: "BGS" },
  { old: "с.Каменар", new: "гр.Поморие", oblast: "BGS" },
  { old: "с.Черноморец", new: "гр.Черноморец", oblast: "BGS" },
  { old: "с.Китен", new: "гр.Китен", oblast: "BGS" },
  { old: "с. Вичево", new: "с. Вичово", oblast: "DOB" },
  {
    old: "с. Г. долина, М. брягово",
    new: "с. Голяма долина",
    oblast: "HKV",
  },
  { old: "с. Плачи дол", new: "с. Плачидол", oblast: "DOB" },
  { old: "с. Пор.Гешаново", new: "с. Гешаново", oblast: "DOB" },
  {
    old: "с.Полк Савово  Войниково",
    new: "с. Полковник Савово",
    oblast: "DOB",
  },
  { old: "с. Поп Груево", new: "с. Попгруево", oblast: "DOB" },
  { old: "с. Струйно", new: "с. Струино", oblast: "SHU" },
  { old: "с.Крън", new: "гр.Крън", oblast: "SZR" },
  { old: "с.Мартен", new: "гр.Мартен", oblast: "RSE" },
  { old: "с.Стомонеците", new: "с.Стоманеците", oblast: "GAB" },
  { old: "с.Парчевци", new: "с.Парчовци", oblast: "GAB" },
];

export const lookupSettlements = (
  settlement: string,
  oblast: string,
): string => {
  const lookup = settlementNames.find(
    (n) => n.old === settlement && n.oblast === oblast,
  );
  return lookup?.new || settlement;
};
