// GENERATED by `news/scripts/gen_bucket_ts.py` from `news/scripts/jev_scales.py`
// and `news/scripts/jev_axes.py`. Do not edit by hand.
//
//   python3 news/scripts/gen_bucket_ts.py           # rewrite
//   python3 news/scripts/gen_bucket_ts.py --check   # the staleness gate
//
// The bucketing rule has two consumers that cannot share code — the Python
// producer that stores a score's `value`, and this client that draws the bar
// and the chip. Hand-copying it is how the bar and the number stop agreeing on
// the articles nearest an edge, with both sides rendering happily.
//
// ⚠️ "Generated" means KEPT IN STEP, not "cannot be wrong". This code is a
// hand-written translation of `jev_scales.py`; what binds the two is
// `sentimentScale.vectors.json` — cases computed by the PYTHON implementation
// and replayed against this one by `sentimentScale.test.ts`. A function here
// with no fixture case is unverified. Add the case in `build_vectors` when you
// add the function, and regenerate.
//
// Kept honest by: `gen_bucket_ts.py --check` (a CI step and
// `news/scripts/gen_bucket_ts.test.mjs`), plus the fixture replay above.

/**
 * The bucket boundaries, on the NORMALIZED value (`value / extent`).
 *
 * ⚠️ Normalized, not raw, so a 5-anchor and a 9-anchor answer of the same
 * shape land in the same bucket — `value` lives on ±(levels−1)/2, so a raw cut
 * would mean different things on the two scales.
 */
export const BUCKET_EDGES = [-0.75, -0.25, 0.25, 0.75] as const;

/** How close to an edge counts as ON it. Applied to BOTH sides — see below. */
export const EDGE_TOLERANCE = 1e-9;

export const TONE_BUCKET_ORDER = [
  "strongly_unfavorable",
  "unfavorable",
  "neutral",
  "favorable",
  "strongly_favorable",
] as const;

export const LEANING_BUCKET_ORDER = [
  "strong_progressive",
  "progressive",
  "neutral",
  "conservative",
  "strong_conservative",
] as const;

export const RUSSIA_BUCKET_ORDER = [
  "strong_pro_russia",
  "pro_russia",
  "neutral",
  "anti_russia",
  "strong_anti_russia",
] as const;

/**
 * The largest absolute level value for a scale of `levels` anchors.
 *
 * ⚠️ Refuses a level count the producer would refuse: `jev_scales.Scale`
 * requires 2..24 anchors, and `extentFor(1)` is 0, which makes
 * `normalizeValue` return Infinity or NaN rather than raising.
 */
export const extentFor = (levels: number): number => {
  if (!Number.isInteger(levels) || levels < 2 || levels > 24) {
    throw new Error(`levels must be an integer in 2..24, got ${levels}`);
  }
  return (levels - 1) / 2;
};

/** `value` mapped onto [-1, 1]. */
export const normalizeValue = (value: number, levels: number): number =>
  value / extentFor(levels);

/**
 * Which display bucket a value falls in.
 *
 * ⚠️ THE FLOAT TOLERANCE IS TWO-SIDED. Applying it to the positive edges only
 * makes `bucketIndex(-v)` stop mirroring `bucketIndex(v)` a few ULPs from an
 * edge, which is reachable from an ordinary two-decimal answer:
 * `{1: .20, 2: .10, 3: .70}` has value 0.49999999999999994, so it would land
 * in *favorable* while its exact mirror landed in *neutral*.
 */
export const bucketIndex = (value: number, levels: number): number => {
  const n = normalizeValue(value, levels);
  let idx = 0;
  for (const edge of BUCKET_EDGES) {
    if (Math.abs(n - edge) <= EDGE_TOLERANCE) {
      // Each interval is closed on its OUTER side: -0.25 belongs to the
      // unfavourable bucket, +0.25 to the favourable one.
      if (edge > 0) idx += 1;
      break;
    }
    if (n > edge) idx += 1;
    else break;
  }
  return idx;
};

/**
 * The bucket's label, in a vocabulary of exactly BUCKET_EDGES.length + 1 entries.
 *
 * ⚠️ `levels` IS THE ANCHOR COUNT OF THE SCALE THE VALUE CAME FROM, never the
 * vocabulary's length. They are equal only for a 5-anchor value. A 9-anchor
 * comparison run is bucketed through this same 5-label display vocabulary —
 * `jev_scales.bucket_label` refuses that call outright and points at
 * `bucket_index` — so inferring the count from `order.length` would normalize
 * a ±4 value by 2 and name a bucket one step too strong, on a named subject,
 * at a 200, with nothing failing.
 */
export const bucketLabel = <T extends string>(
  value: number,
  levels: number,
  order: readonly T[],
): T => {
  if (order.length !== BUCKET_EDGES.length + 1) {
    throw new Error(
      `bucketLabel needs ${BUCKET_EDGES.length + 1} labels, got ${order.length}`,
    );
  }
  return order[bucketIndex(value, levels)];
};
