-- Per-annex contract modifications ("анекси") — the itemised record behind each
-- contract's signing→current value move.
--
-- WHY: the corpus already carries the NET move (contracts.signing_amount_eur vs
-- amount_eur, migration 078). That answers "how much did this contract grow?"
-- but not the question docs/plans/procurement-risk-v2.md §0b actually needs to
-- publish the +50% cliff finding: was that one annex at the чл.116 ал.2 cap, or
-- several smaller ones summing to it — and on which ground (ал.2 substantial
-- change vs ал.3 inflation indexation, which stack separately)? That is a
-- per-annex question, so it needs per-annex rows.
--
-- Each row is one published modification, attributed to a contract by the SAME
-- K2→K1 keys + three guards the current-value fold uses (scripts/procurement/
-- lib/annexResolve.ts) — a second notion of "this contract's annexes" would be
-- worse than none. One annex can attach to several contracts (a consortium
-- modification touches each member's row); that is intended, so the identity is
-- (contract_key, notice_id, lot_identifier), not the annex alone.
--
-- Populated by scripts/db/load_annexes_pg.ts from the raw ЦАИС ЕОП cache
-- (raw_data/procurement/anexi, 100% on disk — no re-crawl). Empty by default.

CREATE TABLE IF NOT EXISTS procurement_annexes (
  id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contract_key              text NOT NULL,   -- FK-in-spirit to contracts.key
  match_via                 text NOT NULL,   -- 'unp' | 'contract_no' (linkage provenance)
  notice_id                 int,             -- the annex publication id
  lot_identifier            text,
  publication_date          text,            -- raw ISO; text sorts chronologically
  contract_date             text,
  currency                  text,            -- native published currency
  -- ⚠️ CONTRACT-TOTAL (full) EUR values, exactly as published — NOT the
  -- per-supplier split that contracts.amount_eur carries. For a consortium the
  -- annex reports the whole contract value while contracts.amount_eur is that
  -- value ÷ member count, so DO NOT compare these two columns directly (same
  -- convention as contracts.consortium_full_eur). Within one contract the
  -- annex-to-annex ratio is basis-invariant, which is all the §0b question needs.
  last_value_eur            numeric,         -- value before THIS annex (EUR, full)
  current_value_eur         numeric,         -- value after THIS annex (EUR, full)
  value_diff_eur            numeric,         -- published difference (EUR, full)
  change_reason             text,            -- ЗОП ground code / short label
  change_reason_description text,
  change_description        text,
  direct_award_justification text
);

-- The read path is always "this contract's annexes, in publication order".
CREATE INDEX IF NOT EXISTS idx_procurement_annexes_contract
  ON procurement_annexes (contract_key, publication_date);
GRANT SELECT ON procurement_annexes TO app_readonly;

-- Serving helper: one contract's annexes as an ordered jsonb array, plus the
-- one derived fact the §0b finding turns on — how many DISTINCT annex
-- publications moved this contract (>1 ⇒ "several summing to it", =1 ⇒ "a single
-- annex at the cap"). The contract detail page's per-annex breakdown reads this.
CREATE OR REPLACE FUNCTION contract_annexes(p_key text)
RETURNS jsonb LANGUAGE sql STABLE AS $$
  SELECT jsonb_build_object(
    -- Distinct annex PUBLICATIONS. COALESCE so a NULL notice_id (the feed omits
    -- it on some rows) is not silently dropped by COUNT(DISTINCT), which would
    -- make "one annex vs several" read 0/1 for a contract whose annexes lack ids.
    'annexCount', COUNT(DISTINCT COALESCE(a.notice_id::text, 'row:' || a.id::text)),
    'rows', COALESCE(jsonb_agg(jsonb_build_object(
      'noticeId', a.notice_id,
      'lot', a.lot_identifier,
      'publicationDate', a.publication_date,
      'lastValueEur', a.last_value_eur,
      'currentValueEur', a.current_value_eur,
      'valueDiffEur', a.value_diff_eur,
      'changeReason', a.change_reason,
      'changeReasonDescription', a.change_reason_description,
      'changeDescription', a.change_description
    ) ORDER BY a.publication_date, a.notice_id), '[]'::jsonb)
  )
  FROM procurement_annexes a
  WHERE a.contract_key = p_key;
$$;
