import { COUNTRIES } from "./country_codes";

const code_2009_07_05: {
  [key: string]: string;
} = {
  //Австралия
  "01": COUNTRIES.AUSTRALIA,
  //Австрия
  "02": COUNTRIES.AUSTRIA,
  //Албания
  "03": COUNTRIES.ALBANIA,
  //Алжир
  "04": COUNTRIES.ALGERIA,
  //Афганистан
  "05": COUNTRIES.AFGHANISTAN,
  //Белгия
  "06": COUNTRIES.BELGIUM,
  //Босна и Херцеговина
  "07": COUNTRIES.BOSNIA_HERZEGOVINA,
  //Великобритания
  "08": COUNTRIES.UNITED_KINGDOM,
  //Гърция
  "09": COUNTRIES.GREECE,
  //Дания
  "10": COUNTRIES.DENMARK,
  //Израел
  "11": COUNTRIES.ISRAEL,
  //Иран
  "12": COUNTRIES.IRAN,
  //Ирландия
  "13": COUNTRIES.IRELAND,
  //Испания
  "14": COUNTRIES.SPAIN,
  //Италия
  "15": COUNTRIES.ITALY,
  //Казахстан
  "16": COUNTRIES.KAZAKHSTAN,
  //Канада
  "17": COUNTRIES.CANADA,
  //Кипър
  "18": COUNTRIES.CYPRUS,
  //Китай
  "19": COUNTRIES.CHINA,
  //Корея
  "20": COUNTRIES.KOREA,
  //Косово
  "21": COUNTRIES.KOSOVO,
  //Кувейт
  "22": COUNTRIES.KUWAIT,
  //Либия
  "23": COUNTRIES.LIBYA,
  //Ливан
  "24": COUNTRIES.LEBANON,
  //Литва
  "25": COUNTRIES.LITHUANIA,
  //Люксембург
  "26": COUNTRIES.LUXEMBOURG,
  //Република Македония
  "27": COUNTRIES.NORTH_MACEDONIA,
  //Малта
  "28": COUNTRIES.MALTA,
  //Мароко
  "29": COUNTRIES.MOROCCO,
  //Молдова
  "30": COUNTRIES.MOLDOVA,
  //Нигерия
  "31": COUNTRIES.NIGERIA,
  //Нидерландия
  "32": COUNTRIES.NETHERLANDS,
  //Норвегия
  "33": COUNTRIES.NORWAY,
  //ОАЕ
  "34": COUNTRIES.UAE,
  //Полша
  "35": COUNTRIES.POLAND,
  //Португалия
  "36": COUNTRIES.PORTUGAL,
  //Румъния
  "37": COUNTRIES.ROMANIA,
  //Русия
  "38": COUNTRIES.RUSSIA,
  //САЩ
  "39": COUNTRIES.USA,
  //Сирия
  "40": COUNTRIES.SYRIA,
  //Словакия
  "41": COUNTRIES.SLOVAKIA,
  //Словения
  "42": COUNTRIES.SLOVENIA,
  //Сърбия
  "43": COUNTRIES.SERBIA,
  //Тайланд
  "44": COUNTRIES.THAILAND,
  //Тунис
  "45": COUNTRIES.TUNISIA,
  //Турция
  "46": COUNTRIES.TURKEY,
  //Украйна
  "47": COUNTRIES.UKRAINE,
  //Унгария
  "48": COUNTRIES.HUNGARY,
  //ФР Германия
  "49": COUNTRIES.GERMANY,
  //Финландия
  "50": COUNTRIES.FINLAND,
  //Франция
  "51": COUNTRIES.FRANCE,
  //Хърватия
  "52": COUNTRIES.CROATIA,
  //Чешка република
  "53": COUNTRIES.CZECH_REPUBLIC,
  //Чили
  "54": COUNTRIES.CHILE,
  //Швейцария
  "55": COUNTRIES.SWITZERLAND,
  //Швеция
  "56": COUNTRIES.SWEDEN,
  //Република Южна Африка
  "57": COUNTRIES.SOUTH_AFRICA,
  //Япония
  "58": COUNTRIES.JAPAN,
  //Нова Зеландия
  "59": COUNTRIES.NEW_ZEALAND,
};
const code_2013_05_12: {
  [key: string]: string;
} = {
  "01": COUNTRIES.AUSTRALIA,
  "02": COUNTRIES.AUSTRIA,
  "03": COUNTRIES.AZERBAIJAN,
  "04": COUNTRIES.ALBANIA,
  "05": COUNTRIES.ARGENTINA,
  "06": COUNTRIES.AFGHANISTAN,
  "07": COUNTRIES.BELGIUM,
  "08": COUNTRIES.BOSNIA_HERZEGOVINA,
  "09": COUNTRIES.UNITED_KINGDOM,
  "10": COUNTRIES.GEORGIA,
  "11": COUNTRIES.GREECE,
  "12": COUNTRIES.DENMARK,
  "13": COUNTRIES.EGYPT,
  "14": COUNTRIES.ISRAEL,
  "15": COUNTRIES.IRELAND,
  "16": COUNTRIES.SPAIN,
  "17": COUNTRIES.ITALY,
  "18": COUNTRIES.JORDAN,
  "19": COUNTRIES.CANADA,
  "20": COUNTRIES.QATAR,
  "21": COUNTRIES.CYPRUS,
  "22": COUNTRIES.CHINA,
  "23": COUNTRIES.KOREA,
  "24": COUNTRIES.KOSOVO,
  "25": COUNTRIES.KUWAIT,
  "26": COUNTRIES.LEBANON,
  "27": COUNTRIES.LUXEMBOURG,
  "28": COUNTRIES.NORTH_MACEDONIA,
  "29": COUNTRIES.MALTA,
  "30": COUNTRIES.MOROCCO,
  "31": COUNTRIES.MOLDOVA,
  "32": COUNTRIES.NIGERIA,
  "33": COUNTRIES.NETHERLANDS,
  "34": COUNTRIES.NORWAY,
  "35": COUNTRIES.UAE,
  "37": COUNTRIES.POLAND,
  "38": COUNTRIES.PORTUGAL,
  "39": COUNTRIES.ROMANIA,
  "40": COUNTRIES.RUSSIA,
  "41": COUNTRIES.SOUTH_AFRICA,
  "42": COUNTRIES.USA,
  "43": COUNTRIES.SLOVAKIA,
  "44": COUNTRIES.SLOVENIA,
  "45": COUNTRIES.SERBIA,
  "46": COUNTRIES.TUNISIA,
  "47": COUNTRIES.TURKEY,
  "48": COUNTRIES.UKRAINE,
  "49": COUNTRIES.HUNGARY,
  "50": COUNTRIES.FINLAND,
  "51": COUNTRIES.GERMANY,
  "52": COUNTRIES.FRANCE,
  "53": COUNTRIES.CROATIA,
  "54": COUNTRIES.CZECH_REPUBLIC,
  "55": COUNTRIES.SWITZERLAND,
  "56": COUNTRIES.SWEDEN,
  "57": COUNTRIES.JAPAN,
};

const code_2014_10_05: {
  [key: string]: string;
} = {
  "01": COUNTRIES.AUSTRALIA,
  "02": COUNTRIES.AUSTRIA,
  "03": COUNTRIES.ALBANIA,
  "04": COUNTRIES.ARGENTINA,
  "05": COUNTRIES.AFGHANISTAN,
  "06": COUNTRIES.BELGIUM,
  "07": COUNTRIES.BOSNIA_HERZEGOVINA,
  "08": COUNTRIES.BRAZIL,
  "09": COUNTRIES.UNITED_KINGDOM,
  "10": COUNTRIES.GEORGIA,
  "11": COUNTRIES.GREECE,
  "12": COUNTRIES.DENMARK,
  "13": COUNTRIES.EGYPT,
  "14": COUNTRIES.IRAN,
  "15": COUNTRIES.ISRAEL,
  "16": COUNTRIES.IRELAND,
  "17": COUNTRIES.SPAIN,
  "18": COUNTRIES.ITALY,
  "19": COUNTRIES.JORDAN,
  "20": COUNTRIES.KAZAKHSTAN,
  "21": COUNTRIES.QATAR,
  "22": COUNTRIES.CANADA,
  "23": COUNTRIES.CHINA,
  "24": COUNTRIES.CYPRUS,
  "25": COUNTRIES.KOREA,
  "26": COUNTRIES.KOSOVO,
  "27": COUNTRIES.KUWAIT,
  "28": COUNTRIES.LEBANON,
  "29": COUNTRIES.LUXEMBOURG,
  "30": COUNTRIES.NORTH_MACEDONIA,
  "31": COUNTRIES.MALTA,
  "32": COUNTRIES.MOROCCO,
  "33": COUNTRIES.MOLDOVA,
  "34": COUNTRIES.NETHERLANDS,
  "35": COUNTRIES.NIGERIA,
  "36": COUNTRIES.NEW_ZEALAND,
  "37": COUNTRIES.NORWAY,
  "38": COUNTRIES.UAE,
  "39": COUNTRIES.POLAND,
  "40": COUNTRIES.PORTUGAL,
  "41": COUNTRIES.SOUTH_AFRICA,
  "42": COUNTRIES.ROMANIA,
  "43": COUNTRIES.RUSSIA,
  "44": COUNTRIES.USA,
  "45": COUNTRIES.SINGAPORE,
  "46": COUNTRIES.SLOVAKIA,
  "47": COUNTRIES.SLOVENIA,
  "48": COUNTRIES.SERBIA,
  "49": COUNTRIES.TURKEY,
  "50": COUNTRIES.UKRAINE,
  "51": COUNTRIES.HUNGARY,
  "52": COUNTRIES.FINLAND,
  "53": COUNTRIES.GERMANY,
  "54": COUNTRIES.FRANCE,
  "55": COUNTRIES.CROATIA,
  "56": COUNTRIES.CZECH_REPUBLIC,
  "57": COUNTRIES.SWITZERLAND,
  "58": COUNTRIES.SWEDEN,
  "59": COUNTRIES.JAPAN,
  "60": COUNTRIES.TUNISIA,
};

const code_2017_03_26: {
  [key: string]: string;
} = {
  "01": COUNTRIES.AUSTRALIA,
  "02": COUNTRIES.AUSTRIA,
  "03": COUNTRIES.AZERBAIJAN,
  "04": COUNTRIES.ALBANIA,
  "05": COUNTRIES.ALGERIA,
  "06": COUNTRIES.ARGENTINA,
  "07": COUNTRIES.ARMENIA,
  "08": COUNTRIES.BELARUS,
  "09": COUNTRIES.BELGIUM,
  "10": COUNTRIES.BOSNIA_HERZEGOVINA,
  "11": COUNTRIES.BRAZIL,
  "12": COUNTRIES.UNITED_KINGDOM,
  "13": COUNTRIES.VIETNAM,
  "14": COUNTRIES.GERMANY,
  "15": COUNTRIES.GEORGIA,
  "16": COUNTRIES.GREECE,
  "17": COUNTRIES.DENMARK,
  "18": COUNTRIES.EGYPT,
  "19": COUNTRIES.ISRAEL,
  "20": COUNTRIES.INDIA,
  "21": COUNTRIES.IRAN,
  "22": COUNTRIES.IRELAND,
  "23": COUNTRIES.SPAIN,
  "24": COUNTRIES.ITALY,
  "25": COUNTRIES.JORDAN,
  "26": COUNTRIES.KAZAKHSTAN,
  "27": COUNTRIES.CANADA,
  "28": COUNTRIES.QATAR,
  "29": COUNTRIES.CYPRUS,
  "30": COUNTRIES.CHINA,
  "31": COUNTRIES.KOSOVO,
  "32": COUNTRIES.CUBA,
  "33": COUNTRIES.KUWAIT,
  "34": COUNTRIES.LEBANON,
  "35": COUNTRIES.LUXEMBOURG,
  "36": COUNTRIES.MALTA,
  "37": COUNTRIES.MOROCCO,
  "38": COUNTRIES.MEXICO,
  "39": COUNTRIES.MOLDOVA,
  "40": COUNTRIES.NIGERIA,
  "41": COUNTRIES.NETHERLANDS,
  "42": COUNTRIES.NEW_ZEALAND,
  "43": COUNTRIES.NORWAY,
  "44": COUNTRIES.UAE,
  "45": COUNTRIES.PALESTINE_TERRITORY,
  "46": COUNTRIES.POLAND,
  "47": COUNTRIES.PORTUGAL,
  "48": COUNTRIES.KOREA,
  "49": COUNTRIES.NORTH_MACEDONIA,
  "50": COUNTRIES.SOUTH_AFRICA,
  "51": COUNTRIES.ROMANIA,
  "52": COUNTRIES.RUSSIA,
  "53": COUNTRIES.USA,
  "54": COUNTRIES.SINGAPORE,
  "55": COUNTRIES.SLOVAKIA,
  "56": COUNTRIES.SLOVENIA,
  "57": COUNTRIES.SERBIA,
  "58": COUNTRIES.TUNISIA,
  "59": COUNTRIES.TURKEY,
  "60": COUNTRIES.UZBEKISTAN,
  "61": COUNTRIES.UKRAINE,
  "62": COUNTRIES.HUNGARY,
  "63": COUNTRIES.FINLAND,
  "64": COUNTRIES.FRANCE,
  "65": COUNTRIES.CROATIA,
  "66": COUNTRIES.MONTENEGRO,
  "67": COUNTRIES.CZECH_REPUBLIC,
  "68": COUNTRIES.SWITZERLAND,
  "69": COUNTRIES.SWEDEN,
  "70": COUNTRIES.JAPAN,
};
const code_2021_04_04: {
  [key: string]: string;
} = {
  "01": COUNTRIES.AUSTRALIA,
  "02": COUNTRIES.AUSTRIA,
  "03": COUNTRIES.AZERBAIJAN,
  "04": COUNTRIES.ALBANIA,
  "05": COUNTRIES.ALGERIA,
  "06": COUNTRIES.ARGENTINA,
  "07": COUNTRIES.ARMENIA,
  "08": COUNTRIES.BELARUS,
  "09": COUNTRIES.BELGIUM,
  "10": COUNTRIES.BOSNIA_HERZEGOVINA,
  "11": COUNTRIES.BRAZIL,
  "12": COUNTRIES.UNITED_KINGDOM,
  "13": COUNTRIES.GERMANY,
  "14": COUNTRIES.GEORGIA,
  "15": COUNTRIES.GREECE,
  "16": COUNTRIES.DENMARK,
  "17": COUNTRIES.EGYPT,
  "18": COUNTRIES.ISRAEL,
  "19": COUNTRIES.INDIA,
  "20": COUNTRIES.IRAN,
  "21": COUNTRIES.IRELAND,
  "22": COUNTRIES.ICELAND,
  "23": COUNTRIES.SPAIN,
  "24": COUNTRIES.ITALY,
  "25": COUNTRIES.JORDAN,
  "26": COUNTRIES.CANADA,
  "27": COUNTRIES.QATAR,
  "28": COUNTRIES.CYPRUS,
  "29": COUNTRIES.CHINA,
  "30": COUNTRIES.KOSOVO,
  "31": COUNTRIES.CUBA,
  "32": COUNTRIES.KUWAIT,
  "33": COUNTRIES.LEBANON,
  "34": COUNTRIES.LUXEMBOURG,
  "35": COUNTRIES.MALAYSIA,
  "36": COUNTRIES.MALTA,
  "37": COUNTRIES.MOROCCO,
  "38": COUNTRIES.MEXICO,
  "39": COUNTRIES.MOLDOVA,
  "40": COUNTRIES.NIGERIA,
  "41": COUNTRIES.NETHERLANDS,
  "42": COUNTRIES.NEW_ZEALAND,
  "43": COUNTRIES.NORWAY,
  "44": COUNTRIES.UAE,
  "45": COUNTRIES.POLAND,
  "46": COUNTRIES.PORTUGAL,
  "47": COUNTRIES.KOREA,
  "48": COUNTRIES.NORTH_MACEDONIA,
  "49": COUNTRIES.SOUTH_AFRICA,
  "50": COUNTRIES.ROMANIA,
  "51": COUNTRIES.RUSSIA,
  "52": COUNTRIES.SAUDI_ARABIA,
  "53": COUNTRIES.USA,
  "54": COUNTRIES.SINGAPORE,
  "55": COUNTRIES.SLOVAKIA,
  "56": COUNTRIES.SLOVENIA,
  "57": COUNTRIES.SERBIA,
  "58": COUNTRIES.TUNISIA,
  "59": COUNTRIES.TURKEY,
  "60": COUNTRIES.UKRAINE,
  "61": COUNTRIES.HUNGARY,
  "62": COUNTRIES.FINLAND,
  "63": COUNTRIES.FRANCE,
  "64": COUNTRIES.CROATIA,
  "65": COUNTRIES.MONTENEGRO,
  "66": COUNTRIES.CZECH_REPUBLIC,
  "67": COUNTRIES.SWITZERLAND,
  "68": COUNTRIES.SWEDEN,
  "69": COUNTRIES.JAPAN,
};

const code_2021_07_11: {
  [key: string]: string;
} = {
  "01": COUNTRIES.AUSTRALIA,
  "02": COUNTRIES.AUSTRIA,
  "03": COUNTRIES.AZERBAIJAN,
  "04": COUNTRIES.ALBANIA,
  "05": COUNTRIES.ALGERIA,
  "06": COUNTRIES.ARGENTINA,
  "07": COUNTRIES.ARMENIA,
  "08": COUNTRIES.BELARUS,
  "09": COUNTRIES.BELGIUM,
  "10": COUNTRIES.BOSNIA_HERZEGOVINA,
  "11": COUNTRIES.BRAZIL,
  "12": COUNTRIES.GERMANY,
  "13": COUNTRIES.GEORGIA,
  "14": COUNTRIES.GREECE,
  "15": COUNTRIES.DENMARK,
  "16": COUNTRIES.DOMINICAN_REPUBLIC,
  "17": COUNTRIES.EGYPT,
  "18": COUNTRIES.ISRAEL,
  "19": COUNTRIES.IRAN,
  "20": COUNTRIES.IRELAND,
  "21": COUNTRIES.ICELAND,
  "22": COUNTRIES.SPAIN,
  "23": COUNTRIES.ITALY,
  "24": COUNTRIES.JORDAN,
  "25": COUNTRIES.CANADA,
  "26": COUNTRIES.QATAR,
  "27": COUNTRIES.CYPRUS,
  "28": COUNTRIES.CHINA,
  "29": COUNTRIES.KOSOVO,
  "30": COUNTRIES.KUWAIT,
  "31": COUNTRIES.CUBA,
  "32": COUNTRIES.LEBANON,
  "33": COUNTRIES.LUXEMBOURG,
  "34": COUNTRIES.MALTA,
  "35": COUNTRIES.MOROCCO,
  "36": COUNTRIES.MEXICO,
  "37": COUNTRIES.MOLDOVA,
  "38": COUNTRIES.NIGERIA,
  "39": COUNTRIES.NETHERLANDS,
  "40": COUNTRIES.NEW_ZEALAND,
  "41": COUNTRIES.NORWAY,
  "42": COUNTRIES.UAE,
  "43": COUNTRIES.UNITED_KINGDOM,
  "44": COUNTRIES.POLAND,
  "45": COUNTRIES.PORTUGAL,
  "46": COUNTRIES.KOREA,
  "47": COUNTRIES.NORTH_MACEDONIA,
  "48": COUNTRIES.SOUTH_AFRICA,
  "49": COUNTRIES.ROMANIA,
  "50": COUNTRIES.RUSSIA,
  "51": COUNTRIES.SAUDI_ARABIA,
  "52": COUNTRIES.USA,
  "53": COUNTRIES.SINGAPORE,
  "54": COUNTRIES.SLOVAKIA,
  "55": COUNTRIES.SLOVENIA,
  "56": COUNTRIES.SERBIA,
  "57": COUNTRIES.TUNISIA,
  "58": COUNTRIES.TURKEY,
  "59": COUNTRIES.UKRAINE,
  "60": COUNTRIES.HUNGARY,
  "61": COUNTRIES.FINLAND,
  "62": COUNTRIES.FRANCE,
  "63": COUNTRIES.CROATIA,
  "64": COUNTRIES.MONTENEGRO,
  "65": COUNTRIES.CZECH_REPUBLIC,
  "66": COUNTRIES.SWITZERLAND,
  "67": COUNTRIES.SWEDEN,
  "68": COUNTRIES.JAPAN,
};

const code_2022_10_02: {
  [key: string]: string;
} = {
  "01": COUNTRIES.AUSTRALIA,
  "02": COUNTRIES.AUSTRIA,
  "03": COUNTRIES.AZERBAIJAN,
  "04": COUNTRIES.ALBANIA,
  "05": COUNTRIES.ALGERIA,
  "06": COUNTRIES.ARMENIA,
  "07": COUNTRIES.BELARUS,
  "08": COUNTRIES.BELGIUM,
  "09": COUNTRIES.BOSNIA_HERZEGOVINA,
  "10": COUNTRIES.BRAZIL,
  "11": COUNTRIES.GERMANY,
  "12": COUNTRIES.GEORGIA,
  "13": COUNTRIES.GREECE,
  "14": COUNTRIES.DENMARK,
  "15": COUNTRIES.EGYPT,
  "16": COUNTRIES.ISRAEL,
  "17": COUNTRIES.IRAN,
  "18": COUNTRIES.IRELAND,
  "19": COUNTRIES.ICELAND,
  "20": COUNTRIES.SPAIN,
  "21": COUNTRIES.ITALY,
  "22": COUNTRIES.JORDAN,
  "23": COUNTRIES.CANADA,
  "24": COUNTRIES.QATAR,
  "25": COUNTRIES.CYPRUS,
  "26": COUNTRIES.CHINA,
  "27": COUNTRIES.KOSOVO,
  "28": COUNTRIES.KUWAIT,
  "29": COUNTRIES.LEBANON,
  "30": COUNTRIES.LUXEMBOURG,
  "31": COUNTRIES.MALTA,
  "32": COUNTRIES.MOROCCO,
  "33": COUNTRIES.MOLDOVA,
  "34": COUNTRIES.NETHERLANDS,
  "35": COUNTRIES.NEW_ZEALAND,
  "36": COUNTRIES.NORWAY,
  "37": COUNTRIES.UAE,
  "38": COUNTRIES.UNITED_KINGDOM,
  "39": COUNTRIES.POLAND,
  "40": COUNTRIES.PORTUGAL,
  "41": COUNTRIES.KOREA,
  "42": COUNTRIES.NORTH_MACEDONIA,
  "43": COUNTRIES.SOUTH_AFRICA,
  "44": COUNTRIES.ROMANIA,
  "45": COUNTRIES.RUSSIA,
  "46": COUNTRIES.SAUDI_ARABIA,
  "47": COUNTRIES.USA,
  "48": COUNTRIES.SINGAPORE,
  "49": COUNTRIES.SLOVAKIA,
  "50": COUNTRIES.SLOVENIA,
  "51": COUNTRIES.SERBIA,
  "52": COUNTRIES.TUNISIA,
  "53": COUNTRIES.TURKEY,
  "54": COUNTRIES.HUNGARY,
  "55": COUNTRIES.FINLAND,
  "56": COUNTRIES.FRANCE,
  "57": COUNTRIES.CROATIA,
  "58": COUNTRIES.MONTENEGRO,
  "59": COUNTRIES.CZECH_REPUBLIC,
  "60": COUNTRIES.SWITZERLAND,
  "61": COUNTRIES.SWEDEN,
  "62": COUNTRIES.JAPAN,
};

export const lookupCountryNumbers = (section: string, year: string) => {
  switch (year) {
    case "2009_07_05":
      return code_2009_07_05[section.substring(2, 4)];
    case "2013_05_12":
      return code_2013_05_12[section.substring(2, 4)];
    case "2014_10_05":
      return code_2014_10_05[section.substring(2, 4)];
    case "2017_03_26":
      return code_2017_03_26[section.substring(2, 4)];
    case "2021_04_04":
      return code_2021_04_04[section.substring(2, 4)];
    case "2021_07_11":
    case "2021_11_14":
      return code_2021_07_11[section.substring(2, 4)];
    case "2022_10_02":
      return code_2022_10_02[section.substring(2, 4)];
    default: {
      const code = section.substring(2, 5);
      //Egypt fix
      if (year === "2024_06_09" && code === "037") {
        return COUNTRIES.EGYPT;
      }
      return code;
    }
  }
};
