// One-time in-place re-normalisation of beneficiary names in already-written
// JSON shards under data/funds/. Used after introducing scripts/funds/
// normalize_name.ts so we don't need to re-download the multi-MB projects
// XLSX to canonicalise casing — the function is idempotent, so a second
// projects ingest run later won't churn the disk.
//
// Walks every JSON file under data/funds/, recursively normalises any
// string value whose key is `name`, `beneficiaryName`, `programName`,
// `top1Name`, or `label`, and writes back only when the content changes.
//
// Skips:
//   - data/funds/beneficiaries-by-eik/  (gitignored, regenerated by ingest)
//   - data/funds/projects/by-eik/       (gitignored)
//   - data/funds/themes.json            (editorial source, hand-maintained)
//
// Run with: npx tsx scripts/funds/__renormalise_inplace.ts

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { normaliseOrgName } from "./normalize_name";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const FUNDS_DIR = path.resolve(__dirname, "../../data/funds");

// Field names whose string value is an org name we should normalise.
const NAME_FIELDS = new Set([
  "name",
  "beneficiaryName",
  "programName",
  "top1Name",
]);

// Directories to skip — gitignored bulk shards plus the editorial source.
const SKIP_PATHS = new Set<string>([
  path.join(FUNDS_DIR, "beneficiaries-by-eik"),
  path.join(FUNDS_DIR, "projects/by-eik"),
  path.join(FUNDS_DIR, "themes.json"),
]);

let changed = 0;
let walked = 0;

const normaliseInPlace = (
  value: unknown,
  parentKey?: string,
): { value: unknown; changed: boolean } => {
  if (typeof value === "string") {
    if (parentKey && NAME_FIELDS.has(parentKey)) {
      const out = normaliseOrgName(value);
      if (out !== value) return { value: out, changed: true };
    }
    return { value, changed: false };
  }
  if (Array.isArray(value)) {
    let anyChanged = false;
    const out = value.map((v) => {
      const r = normaliseInPlace(v, parentKey);
      if (r.changed) anyChanged = true;
      return r.value;
    });
    return { value: anyChanged ? out : value, changed: anyChanged };
  }
  if (value && typeof value === "object") {
    const obj = value as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    let anyChanged = false;
    for (const [k, v] of Object.entries(obj)) {
      const r = normaliseInPlace(v, k);
      if (r.changed) anyChanged = true;
      out[k] = r.value;
    }
    return { value: anyChanged ? out : value, changed: anyChanged };
  }
  return { value, changed: false };
};

const walk = (dir: string): void => {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (SKIP_PATHS.has(full)) continue;
    if (entry.isDirectory()) {
      walk(full);
      continue;
    }
    if (!entry.name.endsWith(".json")) continue;
    walked += 1;
    let raw: string;
    try {
      raw = fs.readFileSync(full, "utf8");
    } catch {
      continue;
    }
    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch {
      continue;
    }
    const result = normaliseInPlace(parsed);
    if (!result.changed) continue;
    const out = JSON.stringify(result.value, null, 2) + "\n";
    fs.writeFileSync(full, out);
    changed += 1;
    if (changed % 200 === 0) {
      console.log(`  … re-normalised ${changed} files`);
    }
  }
};

console.log(`→ re-normalising beneficiary names under ${FUNDS_DIR}`);
walk(FUNDS_DIR);
console.log(`✓ walked ${walked} JSON files, re-wrote ${changed}`);
