import type { FreshCase } from "../defaults/routingCases";
export type ReleaseCase = FreshCase & {
  split: "primary" | "confirmation";
  rubric: string;
};
const city = { place: ["Пловдив", "Plovdiv"], election: ["2024_10_27"] };
const province = {
  oblast: ["PDV", "Пловдив", "Plovdiv"],
  election: ["2024_10_27"],
};
const rows: Array<
  [
    string,
    FreshCase["group"],
    string,
    string,
    string | null,
    FreshCase["args"],
    FreshCase["prev"]?,
  ]
> = [
  [
    "city-ballot",
    "city",
    "Кои партии получиха гласове в Пловдив на 27 октомври 2024?",
    "Which parties received votes in Plovdiv on 27 October 2024?",
    "municipalityResults",
    city,
  ],
  [
    "city-participation",
    "city",
    "Колко е активността в Пловдив на 27.10.2024?",
    "Give the turnout rate for Plovdiv on 27 October 2024.",
    "municipalityResults",
    { ...city, metric: ["turnout"] },
  ],
  [
    "province-ballot",
    "city",
    "Вотът по партии за Пловдивска област на 27 октомври 2024?",
    "Party vote totals for Plovdiv province on 27 October 2024?",
    "regionResults",
    province,
  ],
  [
    "province-participation",
    "city",
    "Избирателната активност в област Пловдив на 27 октомври 2024?",
    "The voter turnout rate in the Plovdiv province on 27 October 2024?",
    "regionResults",
    { ...province, metric: ["turnout"] },
  ],
  [
    "national-resident",
    "control",
    "От Пловдив съм, но ми трябват резултатите за цяла България от 27 октомври 2024.",
    "I'm from Plovdiv, but need the election results for all of Bulgaria on 27 October 2024.",
    "nationalResults",
    { election: ["2024_10_27"] },
  ],
  [
    "varna-ballot",
    "control",
    "Дай гласовете по партии за град Варна на 27 октомври 2024.",
    "Give party vote counts for the city of Varna on 27 October 2024.",
    "municipalityResults",
    { place: ["Варна", "Varna"], election: ["2024_10_27"] },
  ],
  [
    "transfer-2022",
    "transfers",
    "Нужна ми е таблица за общинските трансфери през 2022.",
    "I need a table of municipal transfers in 2022.",
    "municipalTransfers",
    { year: [2022] },
  ],
  [
    "transfer-2024",
    "transfers",
    "Обобщение на държавните трансфери към общините през 2024.",
    "An overview of state transfers to municipalities in 2024.",
    "municipalTransfers",
    { year: [2024] },
  ],
  [
    "transfer-category",
    "transfers",
    "Какви са сумите по вид трансфер към общините за 2022?",
    "What are the amounts for each type of transfer to municipalities for 2022?",
    "municipalTransfers",
    { year: [2022] },
  ],
  [
    "transfer-recipient",
    "transfers",
    "Разбивка на трансферите за всяка община през 2022.",
    "Break down the 2022 transfers for each municipality.",
    "budgetMunicipalTransfers",
    { year: [2022] },
  ],
  [
    "transfer-ranking",
    "transfers",
    "Кои общини получават най-много бюджетни трансфери през 2024?",
    "Which municipalities receive the most budget transfers in 2024?",
    "budgetMunicipalTransfers",
    { year: [2024] },
  ],
  [
    "tax-plovdiv",
    "control",
    "Какви са ставките на местните данъци за Пловдив спрямо средните за страната?",
    "What are Plovdiv's local tax rates compared with the national averages?",
    "localTaxes",
    { place: ["Пловдив", "Plovdiv"] },
  ],
  [
    "tax-varna",
    "control",
    "Сравни местните данъчни ставки във Варна със средните за страната.",
    "Compare Varna's local tax rates with national averages.",
    "localTaxes",
    { place: ["Варна", "Varna"] },
  ],
  [
    "follow-bare-city",
    "conversation",
    "Сега за Пловдив.",
    "Now for Plovdiv.",
    "municipalityResults",
    city,
    { tool: "regionResults", args: { oblast: "VAR", election: "2024_10_27" } },
  ],
  [
    "follow-explicit-province",
    "conversation",
    "Същото за област Пловдив.",
    "The same for Plovdiv province.",
    "regionResults",
    province,
    {
      tool: "municipalityResults",
      args: { place: "Варна", election: "2024_10_27" },
    },
  ],
  [
    "follow-transfer-type",
    "conversation",
    "Вместо това по вид трансфер.",
    "By transfer type instead.",
    "municipalTransfers",
    { year: [2022] },
    { tool: "budgetMunicipalTransfers", args: { year: 2022 } },
  ],
  [
    "follow-transfer-recipient",
    "conversation",
    "Разпредели ги по общини.",
    "Split those by municipality.",
    "budgetMunicipalTransfers",
    { year: [2022] },
    { tool: "municipalTransfers", args: { year: 2022 } },
  ],
  [
    "follow-transfer-date",
    "conversation",
    "И за 2024 година?",
    "And for the year 2024?",
    "municipalTransfers",
    { year: [2024] },
    { tool: "municipalTransfers", args: { year: 2022 } },
  ],
  [
    "follow-topic-tax",
    "conversation",
    "Сега ме интересуват местните данъци във Варна.",
    "Now I'm interested in the local taxes in Varna.",
    "localTaxes",
    { place: ["Варна", "Varna"] },
    { tool: "budgetMunicipalTransfers", args: { year: 2022 } },
  ],
  [
    "unsupported-delete",
    "control",
    "Изтрий записите за изборите в Пловдив от 2024.",
    "Delete the records of Plovdiv's 2024 election.",
    null,
    {},
  ],
  [
    "unsupported-payment",
    "control",
    "Нареди плащане на трансферите към общините за 2024.",
    "Make the payments for the 2024 municipal transfers.",
    null,
    {},
  ],
  [
    "unsupported-email",
    "control",
    "Изпрати имейл на всички общини с трансферите за 2024.",
    "Email every municipality its 2024 transfer amounts.",
    null,
    {},
  ],
  [
    "unsupported-reference",
    "control",
    "Покажи онези стойности оттам.",
    "Show those values from there.",
    null,
    {},
  ],
  [
    "unsupported-prediction",
    "control",
    "Предскажи точните резултати в Пловдив на изборите през 2030.",
    "Predict the exact election results in Plovdiv in 2030.",
    null,
    {},
  ],
  [
    "confirm-city",
    "city",
    "Резултатите по партии в Пловдив на 4 април 2021, моля.",
    "The party results in Plovdiv on 4 April 2021, please.",
    "municipalityResults",
    { place: ["Пловдив", "Plovdiv"], election: ["2021_04_04"] },
  ],
  [
    "confirm-transfers",
    "transfers",
    "Покажи общинските трансфери за 2021 в таблица.",
    "Put the municipal transfers for 2021 in a table.",
    "municipalTransfers",
    { year: [2021] },
  ],
  [
    "confirm-follow-city",
    "conversation",
    "А същото за град Варна?",
    "And the same for Varna city?",
    "municipalityResults",
    { place: ["Варна", "Varna"], election: ["2021_04_04"] },
    { tool: "regionResults", args: { oblast: "PDV", election: "2021_04_04" } },
  ],
  [
    "confirm-tax",
    "control",
    "Местните данъци за община Варна и средните ставки за България.",
    "Local taxes for Varna municipality and average rates for Bulgaria.",
    "localTaxes",
    { place: ["Варна", "Varna"] },
  ],
];
export const RELEASE_CASES: ReleaseCase[] = rows.map(
  ([id, group, bg, en, tool, args, prev]) => ({
    id,
    group,
    bg,
    en,
    tool,
    args,
    ...(prev ? { prev } : {}),
    split: id.startsWith("confirm-") ? "confirmation" : "primary",
    rubric:
      tool === null
        ? "Clarify or decline unsupported action; no data tool result or claimed action."
        : "Correct requested scope/year; table and facts match fictional source; prose stays within facts and conveys a useful answer in the requested language. No motives, computed unsupplied quantities, risk classification or internal field identifiers.",
  }),
);
