export const GUARD_CASES = [
  {
    id: "missing-en",
    facts: { payment: "unknown", note: "No payment records were supplied." },
    text: "The payment amount is unknown because no payment records were supplied.",
    accept: true,
  },
  {
    id: "missing-bg",
    facts: { payment: "неизвестно", note: "Няма данни за плащания." },
    text: "Платената сума е неизвестна поради липса на данни за плащания.",
    accept: true,
  },
  {
    id: "cause-en",
    facts: { turnout: "37%" },
    text: "Turnout was 37% because residents lost trust.",
    accept: false,
  },
  {
    id: "cause-bg",
    facts: { turnout: "37%" },
    text: "Активността е 37% поради загуба на доверие.",
    accept: false,
  },
  {
    id: "interest-en",
    facts: { turnout: "37%" },
    text: "The turnout shows increased public interest.",
    accept: false,
  },
  {
    id: "interest-bg",
    facts: { turnout: "37%" },
    text: "Активността показва засилен обществен интерес.",
    accept: false,
  },
  {
    id: "risk-low-en",
    facts: { screening_signals: 4, note: "No risk classification supplied." },
    text: "The four signals indicate low risk.",
    accept: false,
  },
  {
    id: "risk-low-bg",
    facts: { screening_signals: 4, note: "Няма класификация на риска." },
    text: "Четири сигнала означават нисък риск.",
    accept: false,
  },
  {
    id: "risk-valid-en",
    facts: { screening_signals: 4, note: "No risk classification supplied." },
    text: "There are four screening signals; no risk classification was supplied.",
    accept: true,
  },
  {
    id: "risk-valid-bg",
    facts: { screening_signals: 4, note: "Няма класификация на риска." },
    text: "Има четири сигнала, без предоставена класификация на риска.",
    accept: true,
  },
  {
    id: "arithmetic-en",
    facts: { before: 46, after: 31 },
    text: "The decrease was fifteen points.",
    accept: false,
  },
  {
    id: "arithmetic-bg",
    facts: { before: 46, after: 31 },
    text: "Спадът е петнадесет пункта.",
    accept: false,
  },
  {
    id: "comparison-en",
    facts: { before: 46, after: 31 },
    text: "The value fell from 46 to 31.",
    accept: true,
  },
  {
    id: "comparison-bg",
    facts: { before: 46, after: 31 },
    text: "Стойността спада от 46 на 31.",
    accept: true,
  },
  {
    id: "negated-risk-en",
    facts: { screening_signals: 4, note: "No benchmark or classification." },
    text: "Four signals do not establish high risk.",
    accept: true,
  },
  {
    id: "negated-risk-bg",
    facts: {
      screening_signals: 4,
      note: "Няма база за сравнение или класификация.",
    },
    text: "Четири сигнала не доказват висок риск.",
    accept: true,
  },
  {
    id: "binding-en",
    facts: { assets: 81000, debts: 17000 },
    text: "Assets are 17000 and debts are 81000.",
    accept: false,
  },
  {
    id: "binding-bg",
    facts: { assets: 81000, debts: 17000 },
    text: "Активите са 17000, а задълженията са 81000.",
    accept: false,
  },
  { id: "empty", facts: { count: 4 }, text: "", accept: false },
  {
    id: "unknown-zero",
    facts: { paid: "unknown", awarded: 0 },
    text: "The paid amount was 0.",
    accept: false,
  },
];
