/** Fiscal serving contracts shared by chat discovery and SQL recipes. */
export const BUDGET_QUESTIONS = [
  {
    id: "budgetVariance",
    route: "budget-variance",
    relation: "budget_variance",
    leaf: "budget",
    section: "rows",
    year: 2024,
    bg: "Къде изпълнението на бюджета се различава от закона и актуализирания план?",
    en: "Where does budget execution differ from the law and amended plan?",
  },
  {
    id: "budgetPersonnel",
    route: "budget-personnel",
    relation: "budget_personnel_series",
    leaf: "personnel",
    section: "points",
    bg: "Как се променят щатните бройки и заетите в администрацията?",
    en: "How have established posts and employment in the administration changed?",
  },
  {
    id: "budgetPersonnelByMinistry",
    route: "budget-personnel",
    relation: "budget_personnel_series",
    leaf: "personnel",
    section: "units",
    year: 2024,
    bg: "Какви са разходите за персонал по министерства?",
    en: "What are personnel costs by ministry?",
  },
  {
    id: "budgetDocuments",
    route: "budget-law",
    relation: "budget_documents",
    leaf: "documents",
    section: "rows",
    year: 2026,
    bg: "Къде са бюджетните закони и приложенията за годината?",
    en: "Where are the budget laws and annexes for the year?",
  },
  {
    id: "budgetMinistries",
    route: "budget-ministries",
    relation: "budget_admin_list",
    leaf: "ministries",
    section: "rows",
    year: 2024,
    bg: "Какъв е бюджетът на всяко министерство?",
    en: "What is each ministry’s budget?",
  },
  {
    id: "budgetMunicipalTransfers",
    route: "budget-municipal",
    relation: "budget_muni_list",
    leaf: "municipal",
    section: "rows",
    year: 2024,
    bg: "Как се разпределят бюджетните трансфери между общините?",
    en: "How are budget transfers distributed across municipalities?",
  },
  {
    id: "budgetCapitalByMunicipality",
    route: "budget-municipal-capital",
    relation: "budget_muni_capital",
    leaf: "capital",
    section: "rows",
    year: 2025,
    bg: "Какви капиталови проекти и източници на финансиране имат общините?",
    en: "What capital projects and financing sources do municipalities have?",
  },
  {
    id: "budgetInvestmentPayments",
    route: "budget-municipal-ipop",
    relation: "budget_muni_ipop",
    leaf: "capital",
    section: "rows",
    bg: "Колко е платено по инвестиционната програма за общините?",
    en: "How much has been paid under the municipal investment programme?",
  },
] as const;
