// The home dashboard's figures — ONE blob for the KPI band AND every tile metric.
//
// ⚠️ GCS, NEVER `/api/db`. `/` is the site's entry page, so nothing on it may depend on
// Cloud SQL being warm: `/api/db/*` is a Cloud Function over a pooled connection with a
// 10 s statement timeout and a cold start, while a bucket object is a static GET with no
// compute behind it — and, at `max-age=300, must-revalidate` against the API's
// `s-maxage=3600`, actually the FRESHER of the two. The only route to Postgres from this
// page is the finder, and `HubSearch` arms that on focus or first keystroke. (One GCS fetch
// today; the change feed will be the second when it lands.)
//
// `undefined` is an ANSWER, not a loading state: a checkout that never ran the generator,
// and any figure whose source did not answer, renders descriptor-only. A zero would be a
// claim — „inflation is 0%" — which is the one thing the head must never say.
//
// Plan: docs/plans/home-dashboard-implementation-v1.md §9.3a.

import { useQuery } from "@tanstack/react-query";
import { dataUrl } from "@/data/dataUrl";
import type { HomeHubStatsV1 } from "./homeTypes";

/**
 * 30 minutes rather than `staleTime: Infinity`.
 *
 * The artifact is regenerated by the watcher, and this is the page a reader is most likely
 * to leave open. ⚠️ On its own `staleTime` is a PERMISSION, not a trigger — the app-wide
 * client sets `refetchOnWindowFocus: false` and `refetchOnReconnect: false`, so an idle
 * mounted query has no asker at all. `refetchOnWindowFocus` below is what makes the number
 * actually refresh; without it this constant only shortens the navigate-away-and-back case.
 */
export const HOME_STATS_STALE_MS = 30 * 60 * 1000;

const queryFn = async (): Promise<HomeHubStatsV1 | null> => {
  const r = await fetch(dataUrl("/home/hub_stats.json"));
  if (!r.ok) return null;
  return (await r.json()) as HomeHubStatsV1;
};

export const useHomeHubStats = (): {
  stats: HomeHubStatsV1 | undefined;
  /** The metric for a tile id, or `undefined` — which the tile renders as descriptor-only. */
  tile: (id: string) => HomeHubStatsV1["tiles"][string] | undefined;
  /** True once the request has settled, so the head can tell "loading" from "unavailable"
   *  rather than showing an unavailable note while the fetch is still in flight. */
  settled: boolean;
} => {
  const { data, isFetched } = useQuery({
    queryKey: ["home", "hub-stats"] as const,
    queryFn,
    staleTime: HOME_STATS_STALE_MS,
    // See the note on HOME_STATS_STALE_MS: without this the stale time has no trigger.
    refetchOnWindowFocus: true,
  });
  return {
    stats: data ?? undefined,
    tile: (id) => data?.tiles?.[id],
    settled: isFetched,
  };
};
