// Build the exact same validator for the independently deployed CommonJS bundle.
import { build } from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";

const root = fileURLToPath(new URL("../../", import.meta.url));
export async function buildProcurementQuery(write = false): Promise<void> {
  const result = await build({
    absWorkingDir: root,
    entryPoints: ["src/lib/procurementQuery.ts"],
    bundle: true,
    write: false,
    platform: "node",
    format: "cjs",
    target: "node22",
    banner: {
      js: "// Generated by scripts/ai/buildProcurementQuery.ts. Do not edit.",
    },
  });
  const content = result.outputFiles[0].text;
  const output = resolve(root, "functions/generated/procurement_query.js");
  if (write) {
    mkdirSync(resolve(root, "functions/generated"), { recursive: true });
    writeFileSync(output, content);
  } else if (readFileSync(output, "utf8") !== content)
    throw new Error(
      "Stale procurement validator: run node --import tsx scripts/ai/buildProcurementQuery.ts --write",
    );
}
if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
)
  await buildProcurementQuery(process.argv.includes("--write"));
