// Country names (BG/EN) for the European geos rendered by EuChoroplethMap,
// keyed by Eurostat geo code (EL = Greece, UK/GB = United Kingdom). Kept as a
// small standalone dict so the geometry asset can stay pure (`{geo}` only) and
// any EU-comparison surface can label countries consistently.

export const euGeoNames: Record<string, { bg: string; en: string }> = {
  EU27_2020: { bg: "ЕС27", en: "EU27" },
  EA: { bg: "Еврозона", en: "Euro area" },
  BE: { bg: "Белгия", en: "Belgium" },
  BG: { bg: "България", en: "Bulgaria" },
  CZ: { bg: "Чехия", en: "Czechia" },
  DK: { bg: "Дания", en: "Denmark" },
  DE: { bg: "Германия", en: "Germany" },
  EE: { bg: "Естония", en: "Estonia" },
  IE: { bg: "Ирландия", en: "Ireland" },
  EL: { bg: "Гърция", en: "Greece" },
  ES: { bg: "Испания", en: "Spain" },
  FR: { bg: "Франция", en: "France" },
  HR: { bg: "Хърватия", en: "Croatia" },
  IT: { bg: "Италия", en: "Italy" },
  CY: { bg: "Кипър", en: "Cyprus" },
  LV: { bg: "Латвия", en: "Latvia" },
  LT: { bg: "Литва", en: "Lithuania" },
  LU: { bg: "Люксембург", en: "Luxembourg" },
  HU: { bg: "Унгария", en: "Hungary" },
  MT: { bg: "Малта", en: "Malta" },
  NL: { bg: "Нидерландия", en: "Netherlands" },
  AT: { bg: "Австрия", en: "Austria" },
  PL: { bg: "Полша", en: "Poland" },
  PT: { bg: "Португалия", en: "Portugal" },
  RO: { bg: "Румъния", en: "Romania" },
  SI: { bg: "Словения", en: "Slovenia" },
  SK: { bg: "Словакия", en: "Slovakia" },
  FI: { bg: "Финландия", en: "Finland" },
  SE: { bg: "Швеция", en: "Sweden" },
  IS: { bg: "Исландия", en: "Iceland" },
  LI: { bg: "Лихтенщайн", en: "Liechtenstein" },
  NO: { bg: "Норвегия", en: "Norway" },
  CH: { bg: "Швейцария", en: "Switzerland" },
  AL: { bg: "Албания", en: "Albania" },
  BA: { bg: "Босна и Херцеговина", en: "Bosnia and Herzegovina" },
  ME: { bg: "Черна гора", en: "Montenegro" },
  MK: { bg: "Северна Македония", en: "North Macedonia" },
  RS: { bg: "Сърбия", en: "Serbia" },
  TR: { bg: "Турция", en: "Türkiye" },
  XK: { bg: "Косово", en: "Kosovo" },
  UA: { bg: "Украйна", en: "Ukraine" },
  MD: { bg: "Молдова", en: "Moldova" },
  GB: { bg: "Обединено кралство", en: "United Kingdom" },
  UK: { bg: "Обединено кралство", en: "United Kingdom" },
  BY: { bg: "Беларус", en: "Belarus" },
};

export const euGeoName = (geo: string, bg: boolean): string =>
  euGeoNames[geo]?.[bg ? "bg" : "en"] ?? geo;

// The 27 EU member states (Eurostat geo codes, EL = Greece). Handy as a
// colour-scale domain when a map's story is EU-only but neighbours are drawn
// grey for context.
export const EU27_GEOS: string[] = [
  "BE",
  "BG",
  "CZ",
  "DK",
  "DE",
  "EE",
  "IE",
  "EL",
  "ES",
  "FR",
  "HR",
  "IT",
  "CY",
  "LV",
  "LT",
  "LU",
  "HU",
  "MT",
  "NL",
  "AT",
  "PL",
  "PT",
  "RO",
  "SI",
  "SK",
  "FI",
  "SE",
];
