// Loads the small `mp_party.json` lookup that maps every known MP id to a
// bare parliamentary-group short label (e.g. 2237 → "ГЕРБ-СДС"). Used by the
// procurement tiles to colour the party chip on every MP row, including
// former MPs whose parliament/index.json `currentPartyGroupShort` is null.
//
// File generated by scripts/procurement/mp_party.ts.

import { useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { dataUrl } from "@/data/dataUrl";

interface MpPartyFile {
  generatedAt: string;
  total: number;
  partyByMpId: Record<string, string>;
}

const fetchMpParty = async (): Promise<MpPartyFile | null> => {
  const r = await fetch(dataUrl("/procurement/derived/mp_party.json"));
  if (r.status === 404) return null;
  if (!r.ok) throw new Error(`fetch failed: ${r.status} ${r.url}`);
  return (await r.json()) as MpPartyFile;
};

export const useMpParty = () => {
  const { data } = useQuery({
    queryKey: ["procurement", "mp_party"] as const,
    queryFn: fetchMpParty,
    staleTime: Infinity,
  });

  const lookup = useMemo(
    () =>
      (mpId: number): string | undefined =>
        data?.partyByMpId[String(mpId)],
    [data],
  );

  return { partyForMp: lookup };
};
